### ISSUE TITLE
Specify jsbeautify settings via the Visual Studio Code settings

### ISSUE THREAD

**Issue by bojand** [HookyQR/VSCodeBeautify#103]
* **Operating System (+Version)**: OSX 10.11.6
* **VS Code Version**: 1.9.1
* **beautify Version**: 0.8.0

Provide the settings you use: 
(VS Code workspace and user settings, .jsbeautifyrc, .editorconfig)
eg.:
VS Code:
```javascript
// Place your settings in this file to overwrite the default settings
{
    "vsicons.projectDetection.disableDetect": true,
    "editor.scrollBeyondLastLine": false,
    "editor.rulers": [
        100
    ],
    "files.insertFinalNewline": true,
    "npm-intellisense.scanDevDependencies": true,
    "npm-intellisense.importLinebreak": "",
    "auto-close-tag.activationOnLanguage": [
        "html",
        "xml",
        "php",
        "javascriptreact",
        "vue"
    ]
}
```
.jsbeautifyrc
- None

Is it possible to specify actual jsbeautify settings (as they would be within `.jsbeautifyrc`) but actually in the Visual Studio Code `settings.json` for this extension? If it is I can't seem to get it to work. If this option doesn't exist would it be possible to add that? I almost feel like `beautify.config` setting could be either a `string` for a path or an `object` for actual config settings, so for example:

```json
{
  "js": {
    "indent_size": 5
  },
  "css": {
    "indent_size": 4
  },
  "html": {
    "indent_size": 3
  },
  "eol": "\r\n",
  "indent_with_tabs": false,
  "indent_size": 2
}
```

I am not sure but from quickly looking at the code it seems like it may not be too much work. Just adding additional check for [config detection](https://github.com/HookyQR/VSCodeBeautify/blob/master/options.js#L126) and then probably refactoring some of the [setup code](https://github.com/HookyQR/VSCodeBeautify/blob/master/options.js#L140) once we have config settings?

Any thoughts? I can try and do a PR if this is acceptable for the design / vision of the extension.

Thanks.

**Comment by HookyQR** [comment]
Good point. And the new `beautify.config` setting definitely makes this easier. Perhaps @IgorNovozhilov would like to have a crack at this, it may even be a better option for the team sharing functionally you were after?

I'm happy to implement this, but probably won't have time in the next few weeks.

**Comment by IgorNovozhilov** [comment]
Do you like it #104 :smile:

**Comment by IgorNovozhilov** [comment]
By the way, I'm more comfortable file .jsbeautifyrc, so as it can be used in different IDE.
Settings inside the VSCode, can only be used for the VSCode.

**Comment by IgorNovozhilov** [comment]
But, the idea is to support greater flexibility, I like it :+1:

**Comment by HookyQR** [comment]
PR applied and version 0.8.1 published.

**Comment by santhony7** [comment]
Anyone have an example of this working? I tried to set properties other than indent_size but they don't seem to take. 

This is what I have in my settings file...

`"beautify.options": {
        "indent_size": 4,
        "html": {
            "end_with_newline": true,
            "js": {
                "indent_size": 2
            },
            "css": {
                "indent_size": 2
            }
        },
        "css": {
            "indent_size": 4,
            "newline_between_rules": true,
            "end_with_newline": true,
            "selector_separator_newline": true
        },
        "js": {
            "preserve-newlines": true
        }
    }`
