### ISSUE TITLE
Copy paste issue

### ISSUE THREAD

**Issue by DuncanFaulkner** [HookyQR/VSCodeBeautify#106]
* **Operating System (+Version)**:  Ubuntu
* **VS Code Version**: 1.9.1
* **beautify Version**: 0.8.3

default settings used.

Will test this with 0.8.4 to see if this is reproducing, but I had noticed that if I selected a piece of text from a sass file to copy and paste elsewhere in the sass file it brought over the complete line not just the selected text.

As I said I will test this again with 0.8.3 and 0.8.4, as it may just be a one off issue.

**Comment by HookyQR** [comment]
Copy and paste isn't affected by this extension.

**Comment by spencerhakim** [comment]
@HookyQR No, it definitely is. I'm seeing this issue with v0.8.7. As soon as I disable the extension and reload, the issue goes away. Just started happening to me.

**Comment by HookyQR** [comment]
It's the js-beautify `preserve_newlines` bug that's just come up. I'm setting up a release now against the reverted version.

**Comment by HookyQR** [comment]
0.8.8 released. Let me know how it goes.

**Comment by lrstanley** [comment]
I seem to have this same issue, with vscode 1.10.1, and beautify 0.8.8. Seems as though with this extension enabled, when I paste, it still copies and pastes the entire line, not just the highlighted original text.

I've looked over the settings, and I am not seeing and old references to `preserve_newlines`, either.

**Comment by HookyQR** [comment]
Found a bug ☹️. That means I can fix it 🎉 😄. Should have a new release out today.

**Comment by HookyQR** [comment]
@DuncanFaulkner, let me know how it is with the new version. (0.8.9)

**Comment by lrstanley** [comment]
No longer seems to be occurring for me, with 0.8.9.
