### ISSUE TITLE
CSS: Preserve Newlines

### ISSUE THREAD

**Issue by manojdcoder** [HookyQR/VSCodeBeautify#107]
[js-beautify](https://github.com/beautify-web/js-beautify/) fixed the issue [#537](https://github.com/beautify-web/js-beautify/issues/537) in their [recent release](https://github.com/beautify-web/js-beautify/blob/master/CHANGELOG.md#v1610). Can you please upgrade to latest?

**Comment by HookyQR** [comment]
Released now.

**Comment by schmuli** [comment]
@HookyQR can you also update `Settings.md`?

**Comment by HookyQR** [comment]
I knew I'd miss something!! Will do now.

**Comment by HookyQR** [comment]
0.8.6 released. Only doc changes.
