### ISSUE TITLE
Feature request: All HTML tags in a new-line.

### ISSUE THREAD

**Issue by 5achinJani** [HookyQR/VSCodeBeautify#109]
* **Operating System (+Version)**: Windows 8.1
* **VS Code Version**:  1.9.1
* **beautify Version**: 0.8.8

.jsbeautifyrc
```javascript
{
 "wrap_attributes": "force"
}
```
## Action performed
Didn't find an option to do it in [Settings.md](https://github.com/HookyQR/VSCodeBeautify/blob/master/Settings.md) 

No answers on a question in  [stackoverflow: Beautify: Force line-break for every or specific tags](http://stackoverflow.com/questions/42455727/beautify-force-line-break-for-every-or-specific-tags)

## Sample HTML
```html
 <div><user-detail><div><user-icon></user-icon><span>John doe</span></div></user-detail>
</div>
```
## Expected result
```html
<div>
    <user-detail>
        <div>
            <user-icon>
            </user-icon>
            <span>
                John doe
            </span>
        </div>
    </user-detail>
</div>
```

**Comment by acmilank22** [comment]
me too ...

**Comment by jcphlux** [comment]
This is a Feature I would like to have also.

**Comment by HookyQR** [comment]
This would be a request for the `js-beautify` project.
