### ISSUE TITLE
Use file spacing preferences by default

### ISSUE THREAD

**Issue by ScottKaye** [HookyQR/VSCodeBeautify#11]
I prefer tabs with everything I edit, but Beautify converts these to spaces when I beautify my file.  Most of the time I am editing loose files around my filesystem, so I can't create a `.jsbeautifyrc`.

Is there a way/can there be a feature to use the spacing preferences set up within VS Code?

![image](https://cloud.githubusercontent.com/assets/2024318/13883750/5217373e-ed01-11e5-9822-7e3e01dc50a1.png)

Either this, or a way to have default preferences set up in settings.json?

**Comment by HookyQR** [comment]
Nice call @ScottKaye. I have run into the same issue and I should have addressed this earlier. Will hopefully get to take a look this weekend.

**Comment by HookyQR** [comment]
v0.1.2 published. Default is to use workspace/user settings for space/tab indentation.

**Comment by ScottKaye** [comment]
Great work, thank you!
