### ISSUE TITLE
i use es6 , need import and from in single line

### ISSUE THREAD

**Issue by zhiqiang21** [HookyQR/VSCodeBeautify#110]
* **Operating System (+Version)**: 
* **VS Code Version**: 1.9.1
* **beautify Version**: v0.8.8

Provide the settings you use: 

my  `editorconfig` is 

```
/editorconfig.org
  1 root = true
  2
  3 [*]
  4 indent_style = space
  5 indent_size = 4
  6 tab_width = 4
  7 end_of_line = lf
  8 charset = utf-8
  9 trim_trailing_whitespace = true
 10 insert_final_newline = true
```

my `.jsbeautifyrc` is

```
{
    "js":{
        "operator_position":false
    }
}

```

i use `es6`  ，my  code is

```javascript
import {abc} from './test2';
```

when i run command `beautify file`  it's will become this 

```javascript
import {
    abc
} from './test2';

function adc() {
    console.log('adc');
    abc();
}
```

i only need this  `import ` and `from `  in single line

![image](https://cloud.githubusercontent.com/assets/3990411/23449753/d2862986-fe92-11e6-8a32-26532388332b.png)

**Comment by HookyQR** [comment]
Not currently supported in js-beautify.

**Comment by wbhob** [comment]
Can you open this and add support for one-line imports please @HookyQR

**Comment by johnunclesam** [comment]
Can we please have one line import? Any news on this? Why is it so difficult?

Any alternative to this plugin for VSCode?

**Comment by ajoslin103** [comment]
how can this be done ?

VSCodeBeautify works so well on everything -- except this !!
