### ISSUE TITLE
"Beautify selection" doesn't work with Multi Select

### ISSUE THREAD

**Issue by bennyschaefer** [HookyQR/VSCodeBeautify#112]
* **Operating System (+Version)**: Windows 10 Pro
* **VS Code Version**: 1.10.1
* **beautify Version**: 0.8.8

## Action performed
* Open HTML file
* Select part of the code
* While holding ALT, select more code somewhere else in the file (=VSCode's multi-select feature)
* "Beautify selection"

## Expected results
* both sections should be beautified

## Actual results
* only the section selected first is beautified

**Comment by HookyQR** [comment]
Not something I thought anyone would want to do, but sounds totally legit. Fixing a range formatting error today. Will give this a whirl as well.

**Comment by bennyschaefer** [comment]
Awesome! I really appreciate the extension and your quick response!

**Comment by HookyQR** [comment]
I can make it 'beautify selection' on multiple selection, but 'format selection' doesn't allow this. So, the way you tried to do it should work, but the 'built in' `format selection` wont.

**Comment by bennyschaefer** [comment]
Yeah, that seems alright! Thank you!

**Comment by bennyschaefer** [comment]
Confirmed working with 0.8.9.

Also opened a separate issue for `format selection` in the vscode rep.

**Comment by HookyQR** [comment]
@bennyschaefer, let me know how it is with the new version. (0.8.9)

**Comment by bennyschaefer** [comment]
Yes, it works, thank you for the quick fix!
