### ISSUE TITLE
extra_liners for <br> doesn't work

### ISSUE THREAD

**Issue by SamSlate** [HookyQR/VSCodeBeautify#117]
`"extra_liners": ["br"]` doesn't work

infact almost any element you'd find in a `p` tag (a, em, b, strong, span ...ect) won't work with this rule, but I thought `<br>` was a particularly odd omission for this rule/styling.

**Comment by HookyQR** [comment]
You want a break before `"br"` remove it from the `"unformatted"` list (which it is in by default). It won't work with `"extra_liners"` because it's a single, no content tag.

**Comment by SamSlate** [comment]
How do I remove it from the unformatted list?

**Comment by HookyQR** [comment]
If your just using VS Code settings, in your user or workspace settings, edit: `"html.format.unformatted"`.
