### ISSUE TITLE
[request] indent and line break text nodes

### ISSUE THREAD

**Issue by SamSlate** [HookyQR/VSCodeBeautify#118]
`<p>some text</p>` 

would become 

`<p>`
&nbsp;&nbsp;&nbsp;&nbsp;`some text`
`</p>`

same for h1, and other elements with text nodes. *pretty please!*

**Comment by 5achinJani** [comment]
Possible duplicate of [#109](https://github.com/HookyQR/VSCodeBeautify/issues/109)

**Comment by HookyQR** [comment]
Closed as duplicate of #109
