### ISSUE TITLE
Typescript spaces with generic type

### ISSUE THREAD

**Issue by Riuujin** [HookyQR/VSCodeBeautify#12]
I don't know if this can be solved within the scope of this project,  since it seems to be typescript specific. But whenever i place a use something like: `let myArray :Array<string> = []` and i beatify it it changes to 'let myArray :Array < string >  = []'

**Comment by HookyQR** [comment]
Sorry @Riuujin, seems this isn't supported by js-beautify, which is the tool we use behind the scenes. Not sure what other options are out there for ts formatting.
