### ISSUE TITLE
command 'HookyQR.beautify' not found

### ISSUE THREAD

**Issue by nekkon** [HookyQR/VSCodeBeautify#120]
* **Operating System (+Version)**: Mac OS X El Capitan
* **VS Code Version**: Version 1.10.2 (1.10.2)
* **beautify Version**: 1.0.1: 13 Mar 2017

Just installed the extension in latest version of VS Code and the warning "command 'HookyQR.beautify' not found" pops up when I try to beautify (command+b). Also "Beautify" does not exist in the list of commands when pressing F1.

**Comment by nekkon** [comment]
Had this warning and didn't work at beginning. Now it is fixed. Don't know what caused this to happen.

**Comment by HookyQR** [comment]
Interesting, maybe the extension loader crashed before it loaded beautify the first time around.
