### ISSUE TITLE
force-expand-multiline indentation incorrect

### ISSUE THREAD

**Issue by markv** [HookyQR/VSCodeBeautify#121]
* **Operating System (+Version)**: MacOS 10.12.3
* **VS Code Version**:  1.10.2
* **beautify Version**: 1.0.2

There is an issue with `"wrap_attributes": "force-expand-multiline"` it seems to have happened after this bug was resolved: https://github.com/beautify-web/js-beautify/issues/1103

VS Code:
```javascript
{
  "beautify.editorconfig": null,
  "editor.formatOnSave": true
}
```
.jsbeautifyrc
```javascript
{
  "wrap_attributes": "force-expand-multiline",
  "indent_size": 2
}
```
## Action performed
Format javascript file with `HookyQR.beautifyFile` command
```HTML
<div id="test1" class="test">
<div id="test2" class="test">
<div id="test3" class="test">
<div id="test4" class="test"></div>
</div>
</div>
</div>
```

## Expected results
```HTML
<div
  id="test1"
  class="test"
>
  <div
    id="test2"
    class="test"
  >
    <div
      id="test3"
      class="test"
    >
      <div
        id="test4"
        class="test"
      ></div>
    </div>
  </div>
</div>
```

## Actual results
```HTML
<div
  id="test1"
  class="test"
>
  <div
    id="test2"
    class="test"
  >
    <div
      id="test3"
      class="test"
    >
      <div
        id="test4"
        class="test"
      ></div>
        </div>
        </div>
        </div>
```

**Comment by HookyQR** [comment]
Well that doesn't look right.

**Comment by HookyQR** [comment]
There's definitely an un-indent missing there, will take a look.

**Comment by markv** [comment]
@HookyQR are there any updates upstream on this issue?

**Comment by Wykks** [comment]
https://github.com/beautify-web/js-beautify/issues/1186
