### ISSUE TITLE
TS Support

### ISSUE THREAD

**Issue by jaronwright** [HookyQR/VSCodeBeautify#122]
Would it be possible to get support for typescript.

**Comment by dkobia** [comment]
@jaronwright Install [Typescript Hero](https://marketplace.visualstudio.com/items?itemName=rbbit.typescript-hero) for VSCode which gives you this nice menu item:

<img width="586" alt="screenshot 2017-03-31 09 11 13" src="https://cloud.githubusercontent.com/assets/184092/24551830/16fdf46a-15f2-11e7-9d8a-b92837fd37f6.png">

**Comment by HookyQR** [comment]
@jaronwright, @dkobia `Typescript Hero` doesn't provide the document formatting you're seeing there, it's actually built in to VS Code.

If you want to use `js-beautify` for typescript formatting you can add typescript to the list of document types it will format. Note that it is strictly a javascript beautifier, so you may not get what you want at this stage.

In you VSCode settings (workspace or global):
```javascript
  "beautify.language": {
    "js": {
      "type": ["javascript", "json", "typescript"],
  }
```

**Comment by wbhob** [comment]
Will improved TypeScript support ever happen?

**Comment by HookyQR** [comment]
Probably not, you should not that this is not a typescript beautifier. You're better off relying on the built in system and poking them for improvements.

**Comment by RouR** [comment]
The code formatting is available in VS Code without any extensions (for TS too)
https://stackoverflow.com/questions/29973357/how-do-you-format-code-in-visual-studio-code-vscode
