### ISSUE TITLE
How to disable newline effect when formatting destructured items?

### ISSUE THREAD

**Issue by ryannealmes** [HookyQR/VSCodeBeautify#123]
This is not so much a bug, but rather a query if there is a setting that I can't find.

I am trying to force destructuring to stay on 1 line when using beatify.

e.g.

function someMethod({  attributes }) {
    return attributes.someAttribute;
}

transforms to

function someMethod({  
    attributes 
}) {
    return attributes.someAttribute;
}

Is there something to disable formatting items that are desctructured?

* **Operating System (+Version)**: 
OSX El Capitan 10.11.6

* **VS Code Version**: 
Version 1.10.2 (1.10.2)

* **beautify Version**: 
1.0.2

Provide the settings you use: 
Default settings
```javascript
// Place your settings in this file to overwrite the default settings
{
    "editor.tabSize": 2,
    "search.exclude": {
        "**/.git": true,
        "**/bower_components": true,
        "**/node_modules": true,
        "**/tmp": true,
        "**/build": true,
        "**/android": true
    },
    "window.zoomLevel": -1,
    "workbench.iconTheme": "vscode-icons",
    "extensions.autoUpdate": true
}
```

**Comment by HookyQR** [comment]
js-beautify doesn't really understand the difference between an object and a block. It just treats everything the same unfortunately. There's no setting to make this happen. 😞
