### ISSUE TITLE
Question: How can I disable formatting of comments?

### ISSUE THREAD

**Issue by sqnkov** [HookyQR/VSCodeBeautify#125]
@HookyQR 

For example, this simple SCSS:

```
portfolio-inner {
    @include flex;
    @include flex-direction(column);
    service-footer {
        padding-left: 7rem;
        // Sidebar prefs
    }
}
```
Translates into this on autoFormat:

```
portfolio-inner {
    @include flex;
    @include flex-direction(column);
    service-footer {
        padding-left: 7rem;
        /* Sidebar prefs*/
    }
}
```

How can I disable this? It causes multiple `Ctrl+Z` instances for me.

**Comment by HookyQR** [comment]
Unfortunately the beautifier is specifically a `css` beautifier which has been _extended*_ to format `scss`. The extension allows it to _read_ single line comments, but not write them. I'm not sure there's anything that can be done there.

*I use the term *extended* quite loosely here.
