### ISSUE TITLE
Please add: ""remove_trailing_whitespace" option.

### ISSUE THREAD

**Issue by jluisgarcia** [HookyQR/VSCodeBeautify#126]
This is NOT a bug, just a feature request.

Please add: ""remove_trailing_whitespace" option.

Thank you.

**Comment by HookyQR** [comment]
This should happen automatically during any formatting run.

**Comment by jluisgarcia** [comment]
Thank for answering.
It works with html, but I am setting "php" as "html" in the settings.json file and it does not remove trailing spaces. Is there a workaround for this?
See screenshot.
![screenshot](https://cloud.githubusercontent.com/assets/24752182/24766472/c235abf8-1afb-11e7-9a35-b319291f3401.png)

**Comment by jluisgarcia** [comment]
I have found Coding Standards Fixer as the standard solution.
closed
