### ISSUE TITLE
Add "brace_style" to vs code settings

### ISSUE THREAD

**Issue by Deilan** [HookyQR/VSCodeBeautify#127]
Didn't find `brace_style` in the settings mapping section so a request to add it is here. :)

**Comment by mikevaleriano** [comment]
Yes, since .jsbeautifyrc (the only place you can set `brace_style` as of now) is not incremental to the plugin settings, the option needs to be added to the plugin configuration.

**Comment by HookyQR** [comment]
There's no `brace_style` equivalent in the VS Code settings, so, as @mikevaleriano said, you'll have to use a `.jsbeautifyrc` file to use this setting.
