### ISSUE TITLE
Feature Request: Ember formatting

### ISSUE THREAD

**Issue by elpeterson** [HookyQR/VSCodeBeautify#128]
Beautify formats the following:

`{{#if someThing}}`
`      <div>some code</div>`
` {{/if}}`
`{{#if someThing}}`
`      <div>some code</div>`
` {{/if}}`

to this:

`{{#if someThing}}`
`      <div>some code</div>`
 `{{/if}} {{#if someThing}}`
`      <div>some code</div>`
` {{/if}}`

These two tags are unrelated with their code function and their respective closing/opening tags should be on separate lines the same way any other tag would be.

**Comment by HookyQR** [comment]
Try `indent_handlebars": true` in your .jsbeautifyrc file.

**Comment by okachynskyy** [comment]
I have the same issue.
I have added a "html.format.indentHandlebars": true to my settings.json
And beautify works for handlebars, but it has some formatting issues.

**Comment by HookyQR** [comment]
It does, I agree. It looks like the upstream `js-beautify` isn't getting much attention of late, and I no longer have the time to fix their problems. Sorry for the inconvenience.
