### ISSUE TITLE
Can't identify xml file even if defined in .jsbeautifyrc file

### ISSUE THREAD

**Issue by brentonhouse** [HookyQR/VSCodeBeautify#13]
If I have this section in my `.jsbeautifyrc` file:

```json
	"html": {
		"allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg"]
         }
````

I still get prompted every time I try to format an xml file:

>Couldn't determine type to beautify, please choose.

**Comment by HookyQR** [comment]
This extension doesn't read the setting you have provided above. Beautify for VS Code reads the 'extra' extensions from the user/workspace settings. The settings available (and their defaults) are:
```json
"beautify.JSfiles": ["js", "json", "jsbeautifyrc", "jshintrc"],
"beautify.HTMLfiles": ["htm", "html"],
"beautify.CSSfiles": ["css"]
```

I realise this isn't mentioned anywhere in the README, and I'll ensure it does for the next release.
