### ISSUE TITLE
[Q] How to ignore lines incl curly braces to avoid format them in HTML files?

### ISSUE THREAD

**Issue by dehghani-mehdi** [HookyQR/VSCodeBeautify#130]
Hello,

I'm using latest version of `VSCode` and `Beautify`. in the root of my project I added `.jsbeautifyrc` file (_I tested some option and it works_), in my html file, I have something like follow:

    {{ something }}
    {{ something }}
    {{ something }}

OR

    {{ something }}
        {{ another one something }}
            <div>Hello !!!</div>
        {{ end }}
    {{ end }}

When I try to format my file, above line changed to:

    {{ something }} {{ something }} {{ something }}

I changed `.jsbeautifyrc` as follow:

    {
        "html": {
            "unformatted": ["{", "}", "{{", "}}"]
        }
    }

I think that's not correct (it doesn't work), but I have not another idea about that, is that possible?

Thanks

**Comment by HookyQR** [comment]
Unfortunately you can't at the moment. It was caused by a combination of changes in `js-beautify` which did some weird things. I'll take a look at fixing it today, but don't hold your breath.

**Comment by HookyQR** [comment]
Is not fixed, but is an upstream issue. Perhaps related to https://github.com/beautify-web/js-beautify/issues/1127 or https://github.com/beautify-web/js-beautify/issues/1123

**Comment by dennbagas** [comment]
Is this fixed now?
