### ISSUE TITLE
problem formatting jsx

### ISSUE THREAD

**Issue by mksuper1** [HookyQR/VSCodeBeautify#132]
* **Operating System (+Version)**:  windows 10
* **VS Code Version**: 1.11.2
* **beautify Version**: 1.0.2

It seems that the beautify is not formatting those code in the render for react code.

e.g.
import React, { Component } from 'react';

class Welcome3 extends Component {
    constructor(props) {
        super(props);

        this.state = {            data: 'initial data',
            test: 1
        }
    }

    render() {
        return (
            <div>              Welcome3 {this.props.name }                <button onClick=  {this.updateState}>Click to update data</button>
                <h4>state.data: {this.state.data}</h4>
            </div>
        );
    }
}

after formatting
import React, { Component } from 'react';

class Welcome3 extends Component {
    constructor(props) {
        super(props);

        this.state = {
            data: 'initial data',
            test: 1
        }
    }

    render() {
        return (
            <div>              Welcome3 {this.props.name }                <button onClick=  {this.updateState}>Click to update data</button>
                <h4>state.data: {this.state.data}</h4>
            </div>
        );
    }

}

code in the render are not formatted.
Any settings to solve the problem?

my .jsbeautifyrc
{
    "e4x": true, // Pass E4X xml literals through untouched
    // "brace_style": "collapse-preserve-inline",
    "brace_style": "collapse,preserve-inline",
    "break_chained_methods": false, // Break chained method calls across subsequent lines
    "end_with_newline": true, // End output with newline, default false
    // "indent_char": " ", // Indentation character
    // "indent_level": 0, // Initial indentation level
    // "indent_size": 4, // Indentation size
    "indent_with_tabs": false, // Indent with tabs, overrides `indent_size` and `indent_char`
    "jslint_happy": false, // If true, then jslint-stricter mode is enforced
    "keep_function_indentation": false, // Preserve function indentation
    "max_preserve_newlines": 10, // Maximum number of line breaks to be preserved in one chunk (0 disables)
    "preserve_newlines": true, // Whether existing line breaks should be preserved
    "space_after_anon_function": false, // Should the space before an anonymous function's parens be added, "function()" vs "function ()"
    "space_before_conditional": true, // Should the space before conditional statement be added, "if(true)" vs "if (true)"
    "space_in_empty_paren": false, // Add padding spaces within empty paren, "f()" vs "f( )"
    "space_in_paren": false, // Add padding spaces within paren, ie. f( a, b )
    "unescape_strings": false, // Should printable characters in strings encoded in \xNN notation be unescaped, "example" vs "\x65\x78\x61\x6d\x70\x6c\x65"
    "wrap_line_length": 0, // Lines should wrap at next opportunity after this number of characters (0 disables)

    // common settings used by both jsbeautify and prettydiff
    "keep_array_indentation": true // Preserve array indentation
}

**Comment by ItsLeeOwen** [comment]
adding a .jsbeautifyrc file with 
```
{
    "e4x": true
}
```
fixed my issues where beautify was breaking jsx formats in my .js files.

**Comment by HookyQR** [comment]
Good to hear.

**Comment by donpinkus** [comment]
Does not work for me. 

1.18.1

**Before:**
<img width="693" alt="screen shot 2017-12-03 at 10 13 14 am" src="https://user-images.githubusercontent.com/987092/33528288-b2c50310-d812-11e7-807e-047558727460.png">

**After:**
<img width="693" alt="screen shot 2017-12-03 at 10 13 24 am" src="https://user-images.githubusercontent.com/987092/33528287-adef6eac-d812-11e7-869c-021a6c2eb6e7.png">

**Comment by behrouz-s** [comment]
It doesn't work :(

**Comment by tluanga34** [comment]
I switched to another formatter -  https://github.com/prettier/prettier-vscode 
because of this issue.
