### ISSUE TITLE
formatOnSave not using `.jsbeautifyrc`

### ISSUE THREAD

**Issue by alexsasharegan** [HookyQR/VSCodeBeautify#133]
**Operating System (+Version)**: Mac 10.11.6
**VS Code Version**: 1.11.2
**beautify Version**: 1.0.2

**Issue:** I would like to use vscode's built in formatOnSave hook to trigger the beautify extension's reformatting of `.js`, `.css`, and `.html` files. While running beautify from the command palette works fine, formatOnSave falls back to vscode formatting config and not my `.jsbeautifyrc`.

VSCode:
```json
{
    "editor.formatOnSave": true
    , "beautify.config": "~/.jsbeautifyrc"
}
```
I've also tried using an absolute path for `beautify.confg`.

`~/.jsbeautifyrc`
```json
{
    "end_with_newline": true
    , "indent_char": " "
    , "indent_size": 4
    , "indent_with_tabs": false
    , "max_preserve_newlines": 2
    , "wrap_line_length": 120
    , "indent_body_inner_html": false
    , "indent_scripts": "normal"
    , "wrap_attributes": "force-aligned"
    , "newline_between_rules": false
    , "break_chained_methods": false
    , "comma_first": true
    , "keep_array_indentation": false
    , "keep_function_indentation": false
    , "operator_position": "after-newline"
    , "space_before_conditional": true
    , "space_in_paren": true
    , "space_in_empty_paren": false
}
```
## Action performed
Save file

## Expected results
Expect the above formatting config to be respected.

## Actual results
Plain vscode formatting applied. Obvious differences from config include chained method call line breaks, no spaces in function parens

**Comment by wbuck** [comment]
I'm having the same issue.
I also tried setting the `"editor.formatOnSave"`  to false, which was totally ignored.
My config - ~/.jsbeautifyrc

`{
    "js": {
        "allowed_file_extensions": ["js", "json", "jshintrc", "jsbeautifyrc"],
        "brace_style": "collapse", // [collapse|expand|end-expand|none] Put braces on the same line as control statements (default), or put braces on own line (Allman / ANSI style), or just put end braces on own line, or attempt to keep them where they are
        "break_chained_methods": false, // Break chained method calls across subsequent lines
        "e4x": false, // Pass E4X xml literals through untouched
        "end_with_newline": false, // End output with newline
        "indent_char": " ", // Indentation character
        "indent_level": 0, // Initial indentation level
        "indent_size": 4, // Indentation size
        "indent_with_tabs": false, // Indent with tabs, overrides `indent_size` and `indent_char`
        "jslint_happy": false, // If true, then jslint-stricter mode is enforced
        "keep_array_indentation": false, // Preserve array indentation
        "keep_function_indentation": false, // Preserve function indentation
        "max_preserve_newlines": 0, // Maximum number of line breaks to be preserved in one chunk (0 disables)
        "preserve_newlines": true, // Whether existing line breaks should be preserved
        "space_after_anon_function": false, // Should the space before an anonymous function's parens be added, "function()" vs "function ()"
        "space_before_conditional": false, // Should the space before conditional statement be added, "if(true)" vs "if (true)"
        "space_in_empty_paren": true, // Add padding spaces within empty paren, "f()" vs "f( )"
        "space_in_paren": true, // Add padding spaces within paren, ie. f( a, b )
        "unescape_strings": false, // Should printable characters in strings encoded in \xNN notation be unescaped, "example" vs "\x65\x78\x61\x6d\x70\x6c\x65"
        "wrap_line_length": 0 // Lines should wrap at next opportunity after this number of characters (0 disables)
    }
}`

**Comment by HookyQR** [comment]
Hey @alexsasharegan and @wbuck, I've been away for a while. Taking a look now. Seems like it's a VS Code issue. There's no difference in the extension code on how it handles regular formatting and format on save. I may have missed an API change, or they could have broken the formatter lookup order.

Hold tight. I'm on it.

**Comment by HookyQR** [comment]
So, the code is being called, and is providing the expected response, but the edits are being ignored somewhere down the line. Seems like a VS Code issue rather than a Beautify problem. Sorry. Check the VS Code repo, I'd be guessing it has been logged already somewhere.

I think they changed their internal formatter recently, that may have had some effect.

**Comment by alexsasharegan** [comment]
Bummer! I mean, good on you, @HookyQR, but I figure you would be able to push a fix faster than the VS Code team. I'll see if I can track an issue down or create a new one. @wbuck, I'll post back here if I post/find anything.

**Comment by alexsasharegan** [comment]
So I downloaded the nightly build, and I don't seem to be having any trouble with this. Maybe it will be fixed on their next release...

**Comment by wbuck** [comment]
Thanks for looking in to it. I had a feeling it was a VS Code issue.
