### ISSUE TITLE
JS Beautify version is incorrect in README.md

### ISSUE THREAD

**Issue by AmandaFoster** [HookyQR/VSCodeBeautify#134]
* **Operating System (+Version)**: Windows 10
* **VS Code Version**: 1.0.2
* **beautify Version**: 1.6.12

**NOTE:** Please provide code snippets instead of screen shots. Your issue needs to be replicated, and we need the failing code (text) to do this.

`README.md` references the wrong version of JS-Beautify:
```
Embedded version of js-beautify is v1.6.11
```
https://github.com/HookyQR/VSCodeBeautify/commit/f6fb7b8d10774537b3aaeeb3eeb1c7e3f52c260b
shows the new version to be 1.6.12

## Action performed
None

## Expected results
Expected version to be v1.6.12

## Actual results
Version is v1.6.11
`Embedded version of js-beautify is v1.6.11`

**Comment by HookyQR** [comment]
Fixed. Will do a release soon.
