### ISSUE TITLE
HTML Support in .php file

### ISSUE THREAD

**Issue by Nikodermus** [HookyQR/VSCodeBeautify#137]
* **macOS (10.12.4)**: 
* **VSCode 1.12**: 
* **beautify Version 1.0.2**: 

**NOTE:** Add support for html code within a .php file, as in Brackets/ Atom

VS Code:
```javascript
{
 
    "editor.formatOnSave": "true",
    "files.autoSave": "onWindowChange",	
}
```
.jsbeautifyrc
```javascript
{
	
}
```
## Action performed
Format PHP file with `HookyQR.beautifyFile` command
```
<? php echo 'hola' ?>
<div>
<figure>
<p>Hey</p></figure>
</div>
```

## Expected results
```
<? php echo 'hola' ?>
<div>
   <figure>
       <p>Hey</p>
    </figure>
</div>
```

## Actual results
```
<? php echo 'hola' ?>
<div>
<figure>
<p>Hey</p></figure>
</div>
```

**Comment by HookyQR** [comment]
You can add php support yourself by adding the following to your VS code settings:
```javascript
"beautify.language": {
    "html": [ "htm", "html", "php" ]
}
```
