### ISSUE TITLE
Support for flow type exact syntax.

### ISSUE THREAD

**Issue by dhogborg** [HookyQR/VSCodeBeautify#138]
* **Operating System (+Version)**: macOS Sierra 10.12.4
* **VS Code Version**: 1.12.1 
* **beautify Version**: 1.7.2

Flow ([flow.org](https://flow.org/)) is static type analysis for js. It's powerful and it's syntax is close to typescript, and in general beautify works just fine with types. Except for exact types, documented here: https://flow.org/en/docs/types/objects/#toc-exact-object-types. 

Syntax of exact type definition:
```js
type Props = {|
  propA: boolean,
  propB: string
|}
```

## Settings:
No custom settings, all defaults. No .beaufityjs file.
Tab size: 2 (spaces).

## Action performed
Running command from command palette or ctrl+shift+f yields the same result.

## Expected results
```js
// @flow

import { actionA, actionB } from './actions'

type Props = {|
  propA: boolean,
  propB: string
|}

type Actions = {|
  showMenu: typeof showMenu,
  hideMenu: typeof hideMenu,
|}

export class SomeComponent extends React.Component {

  props: {|
    ...Props,
    ...Actions,
  |}

  constructor(props: any) {
    super(props)
  }

  componentDidMount() {

  }
}

```

## Actual results
Rows following the type definitions are indented wrong.

```js
// @flow

import { actionA, actionB } from './actions'

type Props = {|
  propA: boolean,
    propB: string
      |}

type Actions = {|
  showMenu: typeof showMenu,
    hideMenu: typeof hideMenu,
|}

export class SomeComponent extends React.Component {

  props: {|
    ...Props,
    ...Actions,
  |}

constructor(props: any) {
  super(props)
}

componentDidMount() {

}
}

```

**Comment by HookyQR** [comment]
Can't be done with js-beautify. Sorry. I'm looking into some other formatters though, so you might get lucky, but it will probably be a while.
