### ISSUE TITLE
 a bug when fomat style tag

### ISSUE THREAD

**Issue by gengxuelei** [HookyQR/VSCodeBeautify#142]
* **Operating System (+Version)**: win10 x64
* **VS Code Version**: 1.12.2
* **beautify Version**: 1.0.2

**NOTE:** Please provide code snippets instead of screen shots. Your issue needs to be replicated, and we need the failing code (text) to do this.

Provide the settings you use: 
(VS Code workspace and user settings, .jsbeautifyrc, .editorconfig)
eg.:
Create a file which language been set to 'html',then type these code:

```html
<style>
/*something*/

.a {
  width: 100px;
}

/*something*/

.a {
  width: 100px;
}

</style>

```
.jsbeautifyrc
```javascript
{
  "indent_size": 2,
  "indent_char": " ",
  "end_with_newline": true,
  "indent_with_tabs": false,
  "preserve_newlines": true,
  "max_preserve_newlines": 2,
  "html": {
    "allowed_file_extensions": ["htm", "html", "xhtml", "shtml", "xml", "svg", "vue"],
    "brace_style": "collapse",
    "indent_handlebars": false,
    "indent_inner_html": false,
    "indent_scripts": "keep",
    "max_preserve_newlines": 2,
    "preserve_newlines": true,
    "unformatted": ["a", "span", "img", "code", "pre", "sub", "sup", "em", "strong", "b", "i", "u", "strike", "big", "small", "pre", "h1", "h2", "h3", "h4", "h5", "h6"],
    "wrap_line_length": 0
  },
  "css": {
    "allowed_file_extensions": ["css", "scss", "sass", "less"],
    "newline_between_rules": true,
    "selector_separator": " ",
    "selector_separator_newline": true
  },
  "js": {
    "allowed_file_extensions": ["js", "json", "jshintrc", "jsbeautifyrc"],
    "brace_style": "collapse",
    "break_chained_methods": false,
    "e4x": false,
    "indent_level": 0,
    "jslint_happy": false,
    "keep_array_indentation": true,
    "keep_function_indentation": true,
    "space_after_anon_function": false, // Should the space before an anonymous function's parens be added, "function()" vs "function ()"
    "space_before_conditional": true, // Should the space before conditional statement be added, "if(true)" vs "if (true)"
    "space_in_empty_paren": false,
    "space_in_paren": false,
    "unescape_strings": false,
    "wrap_line_length": 0
  }
}

```
## Action performed
Format javascript file with `HookyQR.beautifyFile` command
_provide example code_

Right Click-->format document

## Expected results
Expected ... to ...
_provide example (expected) output_

## Actual results
Details of what happened ...
_provide example (actual) output_
![image](https://cloud.githubusercontent.com/assets/11707936/26150242/259e2400-3b30-11e7-96d1-e1c2619ee712.png)
Error line when format many times

**Comment by robsonrosa** [comment]
Same here. But adding a few more details, it  behaves differently depending on how you add your comment. 

`block comment` **outside** brackets adds an extra line before and after the comment each time you format.
`block comment` **inside** brackets works fine.
`inline comment` **outside** brackets works fine.
`inline comment` **inside** removes all spaces between comment and last character.

Example before formatting:

![image](https://cloud.githubusercontent.com/assets/2868031/26420810/31054692-409a-11e7-8e6d-040507b239a0.png)

Example after formatting:
![image](https://cloud.githubusercontent.com/assets/2868031/26420985/c22def5c-409a-11e7-9d81-58c4287e4274.png)

It's weird. If you use `inline comment` **outside** brackets and `block comment` **inside** brackets, everything works fine.

**Comment by HookyQR** [comment]
This is an upstream bug unfortunately: https://github.com/beautify-web/js-beautify/issues/1185

**Comment by nuintun** [comment]
Same problem！

**Comment by JoeEarly** [comment]
A right pain in the rear!

**Comment by selrond** [comment]
Same problem

**Comment by HookyQR** [comment]
Again, I refer you to https://github.com/beautify-web/js-beautify/issues/1185
