### ISSUE TITLE
Computed Object Properties trigger new line

### ISSUE THREAD

**Issue by alexsasharegan** [HookyQR/VSCodeBeautify#143]
* **Operating System**: OS X 10.11.6
* **VS Code Version**: 1.12.2
* **beautify Version**: 1.0.2

**NOTE:** Please provide code snippets instead of screen shots. Your issue needs to be replicated, and we need the failing code (text) to do this.

Provide the settings you use: 
(VS Code workspace and user settings, .jsbeautifyrc, .editorconfig)
eg.:
VS Code:
```javascript
{
    "editor.formatOnSave": false,
    "beautify.config": "~/.jsbeautifyrc",
}
```
.jsbeautifyrc
```javascript
{
    "end_with_newline": true,
    "indent_char": " ",
    "indent_size": 4,
    "indent_with_tabs": false,
    "max_preserve_newlines": 2,
    "wrap_line_length": 120,
    "indent_body_inner_html": false,
    "indent_scripts": "normal",
    "wrap_attributes": "force-aligned",
    "newline_between_rules": false,
    "break_chained_methods": false,
    "comma_first": false,
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "operator_position": "after-newline",
    "space_before_conditional": true,
    "space_in_paren": false,
    "space_in_empty_paren": false,
    "js": {
        "brace_style": "collapse,preserve-inline"
    }
}
```
## Action performed
Format javascript file with `HookyQR.beautifyFile` command

Beautify working on this code:
```js
export default {
    filesById({ files }, getters) {
        return files.reduce((memo, f) => Object.assign(memo, { [f.id]: f }), {})
    },
}
```

## Expected results
The above code is already formatted as desired.

## Actual results
Beautify introduces a new line after this object literal's opening curly brace:

```js
export default {
    filesById({ files }, getters) {
        return files.reduce((memo, f) => Object.assign(memo, {
            [f.id]: f }), {})
    },
}
```

**Comment by HookyQR** [comment]
It seems `js-beautify` doesn't understand computed property keys and messes with the format as a result. Check on the [js-beautify](https://github.com/beautify-web/js-beautify) repo to see if it has already been brought up there.

**Comment by alexsasharegan** [comment]
Will do. Thank you!

**Comment by alexsasharegan** [comment]
Follow the upstream issue here: https://github.com/beautify-web/js-beautify/issues/1200

**Comment by alexsasharegan** [comment]
@HookyQR, looks like the fix for this has been merged. Not sure if it's released yet or not.
