### ISSUE TITLE
[question/enhancement] Change Log?

### ISSUE THREAD

**Issue by alexsasharegan** [HookyQR/VSCodeBeautify#145]
Just curious if you have a change log visible somewhere. I updated my extension this morning and was curious what was updated. Checked the releases here, but it looks like every vscode update doesn't correlate with a release.

Just a simple change log posted anywhere (as long as there are breadcrumbs to find it) would be nice. I wouldn't care if it just copied the commit messages between updates.

Thanks for the sweet plugin!

**Comment by ChrisW-B** [comment]
in the vs code extensions page there should be a 'Changelog' header for each extension when you view its details-
In this case it says:

>1.1.0: 31 May 2017

>>Add ignore option for VS Code formatting
>>Update to version 1.6.14 of js-beautify
>>This adds the void_elements option for html.

**Comment by alexsasharegan** [comment]
Well snap, I didn't see the changelog was built into the extension viewer! Thank you! Still new to vscode.
