### ISSUE TITLE
delete js object bracket inside space

### ISSUE THREAD

**Issue by zhiqiang21** [HookyQR/VSCodeBeautify#147]
* **Operating System (+Version)**: macos 10.12.5
* **VS Code Version**: 1.12
* **beautify Version**: 1.1.1

my code is 
```javascript
var aaa = { a: 1, b: 2 };
```

i want use jsbeautify format after is 

```javascript
var aaa = {a: 1, b: 2};
```

it delete bracket  around  space .how can i config my jsbeautifyrc file.

**Comment by HookyQR** [comment]
What are your current settings?

**Comment by HookyQR** [comment]
There's no setting to do this. Sorry. It can only change the spaces inside regular braces `()`.
