### ISSUE TITLE
Powershell available?

### ISSUE THREAD

**Issue by dimmyr** [HookyQR/VSCodeBeautify#149]
Is there a way to use this for Powershell beautification?

Thank you!

**Comment by dizzi90** [comment]
Beautification of Powershell scripts is available with [DTW-DanWard/PowerShell-Beautifier](https://github.com/DTW-DanWard/PowerShell-Beautifier ).

**Comment by dimmyr** [comment]
That one seems to run independently.  Is there a version of it that works as an extension to VS Code?

**Comment by HookyQR** [comment]
This extension only deals with js, html and css. You'll have to find something else. Good luck.
