### ISSUE TITLE
Fail to correctly use workspace setting for file types

### ISSUE THREAD

**Issue by RonanDex** [HookyQR/VSCodeBeautify#15]
![d8464a6e-4076-4c6a-a964-ea9415b547bf](https://cloud.githubusercontent.com/assets/4251021/15102811/91c8feaa-15d6-11e6-84f2-414579da2477.png)

Why my'.hbs'can not be beautify... please help.

**Comment by HookyQR** [comment]
Sorry @RonanDex, my bad. I have fixed the problem and issued version 0.1.4.

**Comment by RonanDex** [comment]
Wow, it's been updated! Thank you very much! I'm super rely on this plugin. ^^
