### ISSUE TITLE
command 'HookyQR.beautifyFile' not found

### ISSUE THREAD

**Issue by saha6984** [HookyQR/VSCodeBeautify#152]
* **macOS sierra 10.12.5**: 
* **Version 1.13.1 (1.13.1)**: 
* **1.1.1: 01 Jun 2017**: 

**NOTE:**while runnint beautify getting command 'HookyQR.beautifyFile' not found.

I didn't change the setting its default presently.

## Action performed
command 'HookyQR.beautifyFile' not found

## Expected results
Need to beautify HTML File

## Actual results
nothing just throwing error

**Comment by HookyQR** [comment]
Do you still have this problem?

**Comment by aishwaryr** [comment]
I faced this issue from last few days, maybe started after installing the latest VSCode on Ubuntu 16.04. Opened the extensions Beautify was showing up as Recommended ie not installed. I don't remember removing it. Reinstalled it. Working fine now.

**Comment by HookyQR** [comment]
Thanks @aishwaryr
