### ISSUE TITLE
Request: ignore `end_with_newline` when formatting selection

### ISSUE THREAD

**Issue by vvs** [HookyQR/VSCodeBeautify#153]
- VSCode Version: Code - Insiders 1.14.0-insider (73015a5e052e6de8ecd60eed2670bea81fad8cac, 2017-06-16T05:13:31.107Z)
- OS Version: Windows_NT ia32 10.0.15063
- Beautify 1.1.1

I have the following line in `.editorconfig`:

```
insert_final_newline = true
```

This causes the problem with formatting selected text. Essentially, a new line is always appended after beautifying any selection.

Just select any (valid and properly formatted) line, invoke "beautify selection" and watch as an empty line appended after the selected line.

I don't think that `insert_final_newline` setting should affect the beautifying the selection, and it certainly shouldn't add new lines after each beautification of any selection.

**Comment by HookyQR** [comment]
The beautify selection command just calls the relevant formatter with the selected text. If you've got that setting, it will get applied. I'll keep this open as a request though.

**Comment by HookyQR** [comment]
Sorry for the delay. It is done.
