### ISSUE TITLE
Formatting ECR files as html

### ISSUE THREAD

**Issue by villzor** [HookyQR/VSCodeBeautify#156]
Hey! I read in earlier issues that Beautify should ignore <% %> tags, and therefore format .ERB documents correctly (other than not formatting <% %> tags). I can however not get this to work when associating .ECR files (embedded crystal), which uses the same syntax.
```javscript
    "beautify.language": {
        "js": {
            "type": [
                "javascript",
                "json"
            ],
            "filename": [
                ".jshintrc",
                ".jsbeautify"
            ]
        },
        "css": [
            "css",
            "scss"
        ],
        "html": [
            "htm",
            "html",
            "ecr"
        ]
    },
```
```erb
<div class="flex">
  <% (1..5).to_a.each do |i| %>
    <% posts.each do |post| %>
      <div class="post">
        <div class="post-title">
          <%= post.title %>
        </div>
      </div>
      <% end %>
        <% end %>
</div>
```

If I add "%" to unformatted, Beautify stops formatting the entire document. Any ideas how to get this to work?

Thank you!

**Comment by HookyQR** [comment]
Beautify stops formatting the document because it's looking for an end tag `</%>` which is not what you want. You should be able to just leave that out. You'll get the funky extra indenting no matter what. It doesn't know that `<% end %>` should be unindented.
