### ISSUE TITLE
Github repo not up-to-date with extension on VScode market?

### ISSUE THREAD

**Issue by laggingreflex** [HookyQR/VSCodeBeautify#157]
I cloned this repo in my ~/.vscode/extensions but this repo currently is at v1.1.0 and VScode keeps updating to a newer version v1.1.1 

PS: Excellent extension! Been using js-beautify since Sublime and couldn't have made the switch to VScode without it.

**Comment by HookyQR** [comment]
Oops. I haven't had time to do things with this recently. Will try to bring the issue count down over the next week. Should trigger an update. Will make sure I push upstream. 😊

**Comment by HookyQR** [comment]
Fixing this up now. It's been a while. :(
