### ISSUE TITLE
function indent

### ISSUE THREAD

**Issue by transtone** [HookyQR/VSCodeBeautify#16]
![15](https://cloud.githubusercontent.com/assets/46688/15105804/45a59652-15f7-11e6-9d6f-5b97f0991fc3.png)
the chekEmail function and checkPhone function in the same level, but have indent. 
how can I do with it?

**Comment by HookyQR** [comment]
@transtone: can you please provide the whole file so I can check if there is a specific syntax causing the problem.

**Comment by transtone** [comment]
yes, please try this file:
https://gist.github.com/transtone/4176476f4e8feca4c521cc39ed150156

**Comment by HookyQR** [comment]
@transtone: js-beautify is used in the back end. It seems this is a known issue: beautify-web/js-beautify#889

I keep abreast of what's happening with their software, so as soon as a release is out to solve it, you will see it active in this extension.
