### ISSUE TITLE
Bugs when formatting TypeScript documents

### ISSUE THREAD

**Issue by briman0094** [HookyQR/VSCodeBeautify#162]
* **Operating System (+Version)**: Windows 10 x64
* **VS Code Version**: 1.14.1
* **beautify Version**: 1.1.1

Provide the settings you use: 
VS Code:
```javascript
{
    "beautify.language": {
        "js": {
            "type": [
                "javascript",
                "json",
                "typescript"
            ],
            "filename": [
                ".jshintrc",
                ".jsbeautify"
            ]
        },
        "css": [
            "css",
            "scss"
        ],
        "html": [
            "htm",
            "html"
        ]
    }
}
```
.jsbeautifyrc
```javascript
{
    "preserve_newlines": true,
    "brace_style": "collapse-preserve-inline",
    "space_in_paren": true,
    "css": {
        "preserve_newlines": true,
        "selector_separator_newline": false,
        "newline_between_rules": true
    }
}
```
## Action performed
Format TypeScript file with `HookyQR.beautifyFile` command

```typescript
export async function getThing(): Promise<Thing> {
    let stuff = await getStuff();

    return {
        id: stuff.type,
        text: stuff.name
    } as Thing;
}
```

## Expected results
Expected code to not change at all (properly formatted already)

## Actual results
Code is formatted to uncompilable TypeScript code

```typescript
export async function getThing(): Promise < Thing > { // spaces before/in carets are not invalid, but look ugly
    let stuff = await getStuff();

    return {
        id: stuff.type,
        text: stuff.name
    }
    as Thing; // line break between closing curly brace and "as" keyword causes compilation error
}
```

These two quirks are the only things I can tell that need fixing when using Beautify with TypeScript. Otherwise the plugin works just as well for TS as it does for JS.

**Comment by briman0094** [comment]
Oop, I found one more minor discrepancy. It appears that Beautify treats optional object properties as ternary operators instead, and puts unnecessary and unsightly spaces in the `?:` token:

![image](https://user-images.githubusercontent.com/816612/28245389-24b2f97a-69cb-11e7-83a7-16bddeea1d8a.png)

**Comment by HookyQR** [comment]
js-beautify is not a typescript formatter. I suggest you use the builtin formatter for typescript.
