### ISSUE TITLE
Beautify doesn't format HTML with Twig correctly

### ISSUE THREAD

**Issue by hendrikeng** [HookyQR/VSCodeBeautify#163]
* **Operating System (+Version)**:  macOS 10.12.5
* **VS Code Version**:  1.14.1
* **beautify Version**: 1.1.1

Provide the settings you use: 
(VS Code workspace and user settings, .jsbeautifyrc, .editorconfig)
eg.:
VS Code:
```javascript
"beautify.language": {
    "html": {
      "type": ["htm", "html", "twig"],
      "ext": ["twig"]
    }
  },
```
.jsbeautifyrc
```javascript
{
  "html": {
	"indent_with_tabs": false,
	"max_preserve_newlines": 2,
	"preserve_newlines": true,
	"keep_array_indentation": true,
	"break_chained_methods": true,
	"wrap_line_length": 120,
	"end_with_newline": true,
	"brace_style": "collapse,preserve-inline",
	"unformatted": ["a", "abbr", "area", "audio", "b", "bdi", "bdo", "br", "button", "canvas", "cite", 
"code", "data",
		"datalist", "del", "dfn", "em", "embed", "i", "iframe", "img", "input", "ins", "kbd", "keygen", "label", "map",
		"mark", "math", "meter", "noscript", "object", "output", "progress", "q", "ruby", "s", "samp", "select", "small",
		"span", "strong", "sub", "sup", "template", "textarea", "time", "u", "var", "video", "wbr", "text", "acronym",
		"address", "big", "dt", "ins", "small", "strike", "tt", "pre", "h1", "h2", "h3", "h4", "h5", "h6"]
  },
```
## Action performed
Format javascript file with `HookyQR.beautifyFile` command

## Expected results
beautify is breaking the Twig code, it's not formatted and indented correctly 

## Actual results

![image](https://user-images.githubusercontent.com/18122799/28330058-713087c2-6bec-11e7-8d56-4f05f5cfe048.png)

is there a way to ignore twig tags when formatting html documents including twig or a similar workaround? thanks a lot

**Comment by sarim** [comment]
I'm also affected by this.

**Comment by lerit** [comment]
yes,i also affected by this problem,if i remove template or replace with div tag,work fine

**Comment by york-xtrem** [comment]
Some solution or another beautifier?

**Comment by york-xtrem** [comment]
Hi @hendrikeng!
You could change the title to:
## Support to Jinja template (Twig & Nunjucks)

That way it has more weight because it is not only support a specific language.

**Comment by alexmironof** [comment]
same for `Handlebars`.
`preserve_new_lines` and `indent_handlebars` are ignored

**Comment by guillecro** [comment]
I am going to ask for this again cause its been like 2 years and i still dont have support for this kind of sintax :(

**Comment by camposcristianeze** [comment]
I'm still looking for this too

**Comment by HookyQR** [comment]
I haven't looked at this yet, but specifically, this extension is designed to support `HTML`, `JS` and `CSS`. Some other things happen as a consequence, but if it doesn't work, it' s because it's not designed to.

Having said that, I intend to update the included formatter this weekend, but I suggest you don't hold your breath, from what I can tell, it still won't do what you want.

**Comment by HookyQR** [comment]
You're all welcome to contribute on https://github.com/beautify-web/js-beautify if you want it that bad. That's the internal engine that I use in this extension.

**Comment by lerit** [comment]
i solve it by add settings in jsbeautifyrc file:
{
"unformatted": []
}

**Comment by HookyQR** [comment]
There you go folks ^^^

**Comment by guillecro** [comment]
Ugh.. sorry @HookyQR, I cannot make it work, not even adding the `unformatted` option
So sorry cause I know how much work you've done for the extension :(

**Comment by HookyQR** [comment]
Sorry it's not working, but it's not supported by this extension. Good luck.
