### ISSUE TITLE
Incorrect indentation for single-line arrow function returning JSX markup

### ISSUE THREAD

**Issue by ecbrodie** [HookyQR/VSCodeBeautify#164]
* **Operating System (+Version)**: MacOS 10.12.5
* **VS Code Version**: 1.14.2
* **beautify Version**: 1.1.1

## Description
There is a conflict between beautify and eslint in terms of the level of indent for a single-line arrow function (such as a React component) that is returning JSX markup. I believe that eslint is more correct in this case, thus I want to see if there is a config that I need to set in beautify to match eslint's configuration, of if there is a legit bug in beautify.

## Settings

```json
{
    "editor.minimap.enabled": false,
    "editor.renderWhitespace": "boundary",
    "editor.tabSize": 2,
    "editor.wordWrap": "on",
    "files.autoSave": "onFocusChange",
    "gitlens.blame.line.enabled": false,
    "telemetry.enableTelemetry": false,
    "vim.disableAnnoyingNeovimMessage": true,
    "workbench.colorTheme": "Solarized Light",
    "workbench.editor.enablePreviewFromQuickOpen": false,
    "workbench.iconTheme": "vscode-icons",
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/CVS": true,
        "**/.DS_Store": true,
        "**/.idea": true,
        "**/.tmp": true
    },
    "gitlens.codeLens.enabled": false,
    "vsicons.dontShowNewVersionMessage": true,
    "ruby.specCommand": "rspec",
    "window.zoomLevel": 0,
    "window.openFoldersInNewWindow": "on",
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
    "vim.enableNeovim": true
}
```

## Action performed

Format a file that looks similar to below:

```jsx
const MyComponent = ({
  requiredPropA,
  requiredPropB,
}) => (
  <div>
    INSERT MARKUP HERE
  </div>
);
```

## Expected results

No changes. The indentation level was already correct (function body should be indented 1 level deeper than the function declaration.

## Actual results

```jsx
const MyComponent = ({
  requiredPropA,
  requiredPropB,
}) => (
    <div>
      INSERT MARKUP HERE
    </div>
  );
```

Not only is the function body now being indented 2 levels deeper than the function's declaration, the closing parenthesis of the function body has also been indented itself. This beautified code now conflicts with my eslint rules:

> Expected indentation of 2 space characters but found 4  react/jsx-indent

Until this issue is resolved, I've had to set `editor.formatOnSave` to false.

**Comment by ecbrodie** [comment]
Note that this bug is a rewrite of https://github.com/beautify-web/js-beautify/issues/1216. I had accidentally filed it in the wrong repo.

**Comment by HookyQR** [comment]
Nope, that was the right place.
