### ISSUE TITLE
Adding additional file types

### ISSUE THREAD

**Issue by Slulego** [HookyQR/VSCodeBeautify#167]
* **Windows 10 v1703**: 
* **VS Code v1.14.2**: 
* **Beautify v1.1.1**: 

Changing the settings doesn't work. 
.jsbeautifyrc or in VS Code settings:
```javascript
{
    "beautify.language": {
        "js": {
            "type": [
                "javascript",
                "json"
            ],
            "filename": [
                ".jshintrc",
                ".jsbeautify"
            ]
        },
        "css": [
            "css",
            "scss"
        ],
        "html": [
            "htm",
            "html",
            "xml",
            "php",
            "cfm"
        ]
    }
}
```
## Action performed
Open xml, php, or any other type of file that I've tried to add.
Run `Beautify file` command with [Ctr] + [Shift] + [p]

## Expected results
Expected to automatically determine which type of file is open and beautify the document.

## Actual results
A message is displayed, "Could not determine type to beautify, please choose."
I have to select every time.

Keep in mind I've tried reinstalled VS Code and the Beautify extension

**Comment by atom0s** [comment]
I am having this same issue. I cannot get it to pickup new ext's for things like html and js. It always gives the "Could not determine type to beautify" error.

**Comment by Slulego** [comment]
Ah ha! You're right atom0s! I had tried using something like "coldfusion" which didn't work, but I found out that it's called "lang-cfml" because the extension creators named it that way for some reason. Thanks!
