### ISSUE TITLE
Is VSCodeBeautify supposed to break HTML text into 128 character lines?

### ISSUE THREAD

**Issue by PatriotRDX** [HookyQR/VSCodeBeautify#168]
* **Operating System (+Version)**: OSX 10.12.6
* **VS Code Version**: 1.15.1
* **beautify Version**: 1.1.1

**NOTE:** Please provide code snippets instead of screen shots. Your issue needs to be replicated, and we need the failing code (text) to do this.

Provide the settings you use:

* All stock Beautify config settings in settings.json.
* No custom configuration files, plain folder, only document is  `index.html`.
* Stock HTML formatter disabled

## Action performed
Format HTML document with CMD+Shift+P and typing Beautify into command palette.

## Expected results
I distinctly remember this not happening a month or two ago with this extension, but it seems instead of keeping all text within a \<p\> tag together, it breaks everything into 128 character lines.

This is not consistent with beautify extensions for Atom and Sublime leading me to assume this is some sort of bug?

Expected the following two \<p\> tags to format all content within tag to single line:

```html
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel semper justo. Fusce cursus pretium turpis et maximus. Suspendisse ut aliquet eros, a luctus dui. Ut vel bibendum augue. Etiam pulvinar ac justo sed facilisis. Nam semper libero metus, sodales eleifend nibh cursus ut. Fusce consectetur convallis elit, eu congue tellus pellentesque at. Vivamus egestas pulvinar lectus. Duis facilisis tortor dui, vitae faucibus ipsum vestibulum nec. Sed suscipit arcu commodo varius rhoncus. Nullam auctor fringilla ex at molestie. Fusce pretium arcu ac lectus cursus tristique. Vestibulum aliquet dolor quis tempus placerat.</p> 
<p>Mauris fringilla, nunc in tempor scelerisque, dolor sem consequat massa, ac tincidunt lorem lorem venenatis quam. Nunc id augue vitae ipsum dignissim iaculis non eu turpis. Nunc fringilla blandit nibh, ut convallis est condimentum ac. Etiam eleifend, enim a dapibus pharetra, turpis dui congue magna, non commodo neque eros sed ipsum. Sed consectetur purus magna, vel ultrices lectus volutpat quis. Curabitur nunc odio, consectetur a placerat aliquam, facilisis id dui. Vivamus posuere iaculis tempor. Praesent bibendum convallis velit eget efficitur. Quisque a viverra purus. Suspendisse consectetur hendrerit velit, sit amet finibus arcu mollis eget. Nulla lobortis at risus ac lobortis.</p> 
```

## Actual results
Actual output was each \<p\> tag broken into 128 character length lines:

```html
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel semper justo. Fusce cursus pretium turpis et maximus. Suspendisse
  ut aliquet eros, a luctus dui. Ut vel bibendum augue. Etiam pulvinar ac justo sed facilisis. Nam semper libero metus, sodales
  eleifend nibh cursus ut. Fusce consectetur convallis elit, eu congue tellus pellentesque at. Vivamus egestas pulvinar lectus.
  Duis facilisis tortor dui, vitae faucibus ipsum vestibulum nec. Sed suscipit arcu commodo varius rhoncus. Nullam auctor
  fringilla ex at molestie. Fusce pretium arcu ac lectus cursus tristique. Vestibulum aliquet dolor quis tempus placerat.</p>
<p>Mauris fringilla, nunc in tempor scelerisque, dolor sem consequat massa, ac tincidunt lorem lorem venenatis quam. Nunc id
  augue vitae ipsum dignissim iaculis non eu turpis. Nunc fringilla blandit nibh, ut convallis est condimentum ac. Etiam
  eleifend, enim a dapibus pharetra, turpis dui congue magna, non commodo neque eros sed ipsum. Sed consectetur purus magna,
  vel ultrices lectus volutpat quis. Curabitur nunc odio, consectetur a placerat aliquam, facilisis id dui. Vivamus posuere
  iaculis tempor. Praesent bibendum convallis velit eget efficitur. Quisque a viverra purus. Suspendisse consectetur hendrerit
  velit, sit amet finibus arcu mollis eget. Nulla lobortis at risus ac lobortis.</p>
```

Display in editor looks objectively terrible as per this screenshot:

<img width="1075" alt="screen shot 2017-08-21 at 10 52 53 am" src="https://user-images.githubusercontent.com/23663019/29524841-eeb0fc5e-865e-11e7-9fe3-8d911241dcd5.png">

**Comment by doggy8088** [comment]
@PatriotRDX You can change your user settings into the following setting in order to ignore wrapping.

```
{
    "beautify.config": {
        "wrap_line_length": 0
    }
}
```

**Comment by PatriotRDX** [comment]
@doggy8088 that Settings.md file you linked shows the defaults as 0. Which should disable line-wrapping.

This doesn't make sense since I've not changed any defaults and my lines are _still_ wrapping to 128 characters?

**Comment by doggy8088** [comment]
@PatriotRDX The **Visual Studio Code** has an `"html.format.wrapLineLength": 120` setting which 120 characters are default value.  This could overwrite **Beautify**'s default value.

**Comment by doggy8088** [comment]
@PatriotRDX  I've been change my settings to the following:

```
    "html.format.wrapLineLength": 0,
    "html.format.wrapAttributes": "auto",
```

See here: https://github.com/HookyQR/VSCodeBeautify/issues/170

**Comment by PatriotRDX** [comment]
@doggy8088 I think that is for the default Beautify function. I've already disabled that with this setting:

```json
// Enable/disable default HTML formatter (requires restart)
"html.format.enable": true,
```

**Comment by doggy8088** [comment]
@PatriotRDX Your setting is `true` for `"html.format.enable"`.  What are you disabled for?

**Comment by PatriotRDX** [comment]
@doggy8088 I meant `false`. Updated the above code. I accidentally copied the default code.

**Comment by HookyQR** [comment]
The VS code setting gets merged in if you haven't set anything.
```
  // Maximum amount of characters per line (0 = disable).
  "html.format.wrapLineLength": 120,
```
Either set that to zero, or set the `"wrap_line_length"` setting in a `.jsbeautifyrc` file, or set 
```
    "beautify.config": {
        "html": {
            "wrap_line_length": 0,
            "wrap_attributes": "auto"
        }
    }
```
in your VS Code user/workspace settings.
