### ISSUE TITLE
A bug when format javascript file

### ISSUE THREAD

**Issue by snovey** [HookyQR/VSCodeBeautify#169]
* **Operating System (+Version)**: Windows 7
* **VS Code Version**: 1.15.1 x64
* **beautify Version**: 1.1.1

Create a file which language been set to 'js', then type these code:
```javascript
console.log(a)
!a ? a = true : a = false
```

VS Code:
```javascript
{
	"beautify.ignore": [],
	"beautify.config": null
}
```
.jsbeautifyrc:
The default configration. It's too long and I will add it if needed.

## Action performed
Press F1 and choose Beautify file

## Expected results
Expected ... to ...
```javascript
a = true
console.log(a)
!a ? a = true : a = false
```

## Actual results
Details of what happened ...
```javascript
a = true
console.log(a) !a ? a = true : a = false
```
This will leading to runtime error.

**Comment by HookyQR** [comment]
You'll want to log this as a bug in the `js-beautify` project. Of course, you could just use a semicolon, like you really should. ;)
