### ISSUE TITLE
[Feature request] Add support for C# code.

### ISSUE THREAD

**Issue by charlesmilette** [HookyQR/VSCodeBeautify#17]
Basically, it's the same as JS, with some exceptions:

`private const int SPIF_SENDWININICHANGE = 2;` is beautifyied to
```
private
const int SPIF_SENDWININICHANGE = 2;
```
but should remain the same.

Same thing for `@"Control Panel\Desktop"` beautifyied as `@ "Control Panel\Desktop"`

There might be more, but I didn't found them.

**Comment by HookyQR** [comment]
It's not supported because the backend `js-beautify` doesn't support it. I'm looking into creating a whole new backend, which will also enable adding new file structures more easily in the future. I'll keep you posted.

**Comment by lonix1** [comment]
Any update on c# support?
