### ISSUE TITLE
.editorconfig's indent_size doesn't applied on HTML file

### ISSUE THREAD

**Issue by doggy8088** [HookyQR/VSCodeBeautify#170]
**Detailed Description**

The `.editorconfig`'s `indent_size` doesn't applied on HTML file if I configure any of the `.jsbeautifyrc` or VSCode's `"beautify.config"` User Settings.  When I removed all the `.jsbeautifyrc` or VSCode's `"beautify.config"` User Settings, then the **VSCodeBeautify** will obey the `.editorconfig`'s `indent_size` setting.   

If there is no `indent_size` setting in the `.jsbeautifyrc` or VSCode's `"beautify.config"` User Settings, the **VSCodeBeautify** should read `indent_size` from `.editorconfig`.

* **Operating System (+Version)**: Windows 10 (version 1703)
* **VS Code Version**: 1.15.1
* **beautify Version**: 1.1.1

**Reproduce Steps**

Provide the settings you use: 

VS Code:
```javascript
{
    "beautify.config": {
        "html": {
            "wrap_line_length": 0,
            "wrap_attributes": "auto"
        }
    }
}
```
.jsbeautifyrc
```javascript
```
.editorconfig
```
# Editor configuration, see http://editorconfig.org
root = true

[*]
charset = utf-8
indent_style = space
indent_size = 2
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
max_line_length = off
trim_trailing_whitespace = false
```

## Action performed
Format HTML file with `HookyQR.beautifyFile` command
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
</body>
</html>
```

## Expected results
Expected ... to ...
```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>
</body>

</html>
```

## Actual results
Details of what happened ...
```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
</body>

</html>
```

**Comment by KurtGokhan** [comment]
If there is a "beauty.config" setting in the workspace or user settings, .editorconfig will be discarded. Instead of this:

```
{
    "beautify.config": {
        "html": {
            "wrap_line_length": 0,
            "wrap_attributes": "auto"
        }
    }
}
```

Use vscode's format settings:

```
  "html.format.wrapLineLength": 0,
  "html.format.wrapAttributes": "auto",
```

**Comment by HookyQR** [comment]
the existence of an empty `.jsbeautifyrc` file will also cause issues. Some merging does go on, but there are priorities. If you want to use you're editor-config settings, either create the equivilant for the js-beautify settings, or remove all js-beautify settings (which includes empty files).
