### ISSUE TITLE
brace_style and space_after_anon_function in .editorconfig doesn't work.

### ISSUE THREAD

**Issue by johnunclesam** [HookyQR/VSCodeBeautify#171]
Using this in my .editorconfig doesn't work in my js files.

**Why?**

[*.js]
brace_style = collapse,preserve-inline
space_after_anon_function = false

Using instead them in .jsbeautifyrc works good.

But I need them in .editorconfig file only.

**Comment by HookyQR** [comment]
These are not valid editorconfig settings. You can't just put settings of one type into another setting file type and expect it to work. The extension will only read editorconfig settings from the editorconfig file.
