### ISSUE TITLE
Format all files in a folder recursively ?

### ISSUE THREAD

**Issue by DollarAkshay** [HookyQR/VSCodeBeautify#175]
* **Operating System**: Windows 10
* **VS Code Version**: 1.16.1 x64
* **beautify Version**:  1.1.1

How do I format all the files in a folder recursively ?

**Comment by HookyQR** [comment]
Try using the command line `js-beautify` tool. This is just a wrapper for that.

**Comment by DollarAkshay** [comment]
Syntax ?
