### ISSUE TITLE
Twig code not formatted correctly

### ISSUE THREAD

**Issue by bgarrant** [HookyQR/VSCodeBeautify#176]
Whenever I am using a file with Twig code in it and I run through the Beautify (HTML Format) I get results like this:

ORIGINAL CODE
```
{% extends "_layout" %}

{% block content %}

{% for block in entry.carousel %}
    {% set asset = block.carouselImage.first() %}
    <div class="jumbotron">
        blah, blah, blah
    </div>
{% endfor %}
```

FORMATTED WITH "Beautify File" command using Beautify (HTML Format)
```
{% extends "_layout" %} {% block content %} {% for block in entry.carousel %}  {% set asset = block.carouselImage.first() %}
    <div class="jumbotron">
        blah, blah, blah
    </div>
{% endfor %}
```

The extension is not preserving the line breaks for the twig blocks and they get placed inline.  I just various config settings and nothing works.  Any idea how to fix this?

**Comment by bgarrant** [comment]
Any chance you can look at this @HookyQR? Sublime, and Atom both have it working now. I see Like 4 other issues open for Twig formatting. Thanks.

**Comment by bgarrant** [comment]
I have been trying to custom format these twig blocks with no luck.  Any luck finding anything @HookyQR?

**Comment by bgarrant** [comment]
@HookyQR Any chance you can check this out?  There must be a fix for it now as Atom has it fixed also using JS Beautify.

**Comment by guillecro** [comment]
@bgarrant This has been a requested feature for a long time
There is a topic already discussing this, you should give it a look too and participate!
https://github.com/HookyQR/VSCodeBeautify/issues/163

**Comment by HookyQR** [comment]
Sorry folks, I've been far too busy with other projects, and - unfortunately - actual work. I may get a chance to take a look over the coming weekend.

**Comment by HookyQR** [comment]
Have updated to the latest `js-beautify` on my machine. It doesn't solve your problem I'm afraid. Seems `js-beautify` doesn't work nicely with twig. You're welcome to contribute on the [js-beautify](https://github.com/beautify-web/js-beautify) project that I use internally to make this work.

**Comment by HookyQR** [comment]
Not supported by this extension.
