### ISSUE TITLE
Option to not indent methods?

### ISSUE THREAD

**Issue by likewei92** [HookyQR/VSCodeBeautify#177]
Just wondering if there's an option to not indent methods, such as in promise chaining? For example
```javascript
new ServerFactory(config).create()
.then(server => server.start());
```
is indented to
```javascript
new ServerFactory(config).create()
    .then(server => server.start());
```
but I'd like it not to

**Comment by wenkanglin** [comment]
+1
Why not add option `unindent-chained-methods` to it? This option has already exists in [js-beautify](https://github.com/beautify-web/js-beautify#options).

**Comment by HookyQR** [comment]
unindent_chained_methods is coming in the next release.

**Comment by HookyQR** [comment]
Is released.
