### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by joshuaharrison** [HookyQR/VSCodeBeautify#18]
When formatting code via context menu > 'Format Code', the last line of the file is being duplicated. 

This was occurring in both html and js files.

Had to uninstall the extension so can't provide any examples

**Comment by HookyQR** [comment]
It's not likely that this extension is the cause as VS Code runs it's own formatter for js files. When was the last time you updated the extension? A new version was issued a few days ago.

**Comment by joshuaharrison** [comment]
Well i noticed this issue yesterday, I had thought the context menu was running the built-in formatter so didn't think it was the extension. But after removing this extension the issue was gone (tested on same files). 

Sorry can't confirm what version i was using... not much help i know :)

**Comment by HookyQR** [comment]
Are you running the insider version (1.1.0) of VS Code? There has been a change in the way the system handles ranges. The extension has been updated in the last few days to allow for the change. If you haven't (re-)installed the extension since Sunday you may be catching that issue.

**Comment by joshuaharrison** [comment]
I've reinstalled the extension and I'm getting the issue i described

VS Code 1.1.0
Beautify: 0.1.4

If you can point me to 

![image](https://cloud.githubusercontent.com/assets/12277459/15177916/8102d222-176a-11e6-9f71-898d0492889d.png)

**Comment by HookyQR** [comment]
My VS Code just updated and I'm now having the same problem. I can look into it now.

**Comment by joshuaharrison** [comment]
Okay thanks.

**Comment by themre** [comment]
Hi,
I was also having this problem and I did uninstall some plugins and also beautify and then reinstalled beautify and now it works ok. So maybe there is some clash with some of the existing extensions.

**Comment by joshuaharrison** [comment]
These are the only extensions i have installed

![Uploading image.png…]()

**Comment by themre** [comment]
oh, I just uninstalled jquery code snippets. try that.

**Comment by themre** [comment]
sorry, javascript snippet pack.

**Comment by joshuaharrison** [comment]
Just uninstalled all1 by 1 same issue until i had no extensions. Reinstalled beautify alone and it came back :cry:

**Comment by themre** [comment]
strange. well, my problem was that it was duplicating a whole stack, which was even more weird. perhaps there is a problem with the HTML. Because i've beautified many htmls and it worked ok. you can send me your html so i can try to beautify it and see if it's a problem in html or beautifier.

**Comment by HookyQR** [comment]
Fixed. New version released.

**Comment by HookyQR** [comment]
The problem was (again) caused by VS Code changing the way it handled infinite ranges. Previously they were set to the final character of the document, they are now set to the first (zero), so when the replacement is called, the new data is ***placed*** (rather than replacing the original segment) at the start of the segment.

Ranges are now validated before being passed to the replace function.
