### ISSUE TITLE
Incorrect Sass map formatting

### ISSUE THREAD

**Issue by chiragbhansali** [HookyQR/VSCodeBeautify#180]
* **Operating System (+Version)**: Windows 10
* **VS Code Version**: 1.16
* **beautify Version**: 1.1.1

Beautify not working as intended in the following case. However, it works perfectly fine with selectors. Probably this is only with variables and since the Sass map is stored in a variable, it formats it to one line. Is there any way to prevent such a behavior?

Note: It behaves the same without the .jsbeautifyrc

VS Code:
```javascript
{
	"editor.formatOnSave": true
}
```
.jsbeautifyrc
```javascript
{
    "scss": {
        "newline_between_rules": true
    }
}
```
## Action performed
Formatted scss file with beautify command

## Expected results(.scss)

```scss
$z-index: (
    header: (
        'rectangle': -1,
    ),
);
```

## Actual results(.scss)

```scss
$z-index: ( header: ( 'rectangle': -1, ), );
```

**Comment by HookyQR** [comment]
Don't think so. It's a CSS beautifier, so it doesn't know anything about these structures.
