### ISSUE TITLE
There is no "space-before-function-parentheses" option 

### ISSUE THREAD

**Issue by Zhangzirui** [HookyQR/VSCodeBeautify#181]
There is no "space-before-function-parentheses" option in the configuration of .jsbeautifyrc file.

just like

VS Code: 
{
    "space-before-function-parentheses": true
}

Expected results:
`
function test () {
    console.log('this is a test.');
}
`

But now
`
function test() {
    console.log('this is a test.');
}
`

**Comment by IOsonoTAN** [comment]
I've the same problem too.

**Comment by HookyQR** [comment]
Correct, there is not. You can contribute to the `js-beautify` project to add it if you like.
