### ISSUE TITLE
Incorrect Indenting Size

### ISSUE THREAD

**Issue by TheBelgiumeseKid** [HookyQR/VSCodeBeautify#186]
* **Windows 10 x64**: 
* **1.18.0**: 
* **1.1.1**: 

Beautify seems to be double indenting all my files. I have my tab size set to 2, and I have detect indentation set to false.

Provide the settings you use: 
VS Code:
```javascript
{
    "editor.detectIndentation": false,
    "editor.tabSize": 2,
    "javascript.format.insertSpaceBeforeFunctionParenthesis": false,
    "javascript.format.insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
    "javascript.format.insertSpaceAfterFunctionKeywordForAnonymousFunctions": false,
    "javascript.format.placeOpenBraceOnNewLineForControlBlocks": false,
    "javascript.format.placeOpenBraceOnNewLineForFunctions": false,
}
```
.jsbeautifyrc
```javascript
{
    "brace_style": "collapse,preserve-inline"
}
```
## Action performed
Format javascript file with `HookyQR.beautifyFile` command
Before format:
`module.exports.getAllQuotes = (req, res) => {
Quote.find((err, quotes) => {
if (err) {
res.send(err);
}
res.json({ quotes: quotes });
});
};`

## Expected results
`module.exports.getAllQuotes = (req, res) => {
  Quote.find((err, quotes) => {
    if (err) {
      res.send(err);
    }
    res.json({ quotes: quotes });
  });
};`

## Actual results
`module.exports.getAllQuotes = (req, res) => {
    Quote.find((err, quotes) => {
        if (err) {
            res.send(err);
        }
        res.json({ quotes: quotes });
    });
};`

EDIT: It's not liking how I've pasted it into github, but essentially there is a 4 space spacing used instead of 2 space.

**Comment by akerd** [comment]
I have the same issue with latest version of VSCode 1.18.0.

It seems like default config "editor.tabSize": 3 is ignore.

I solved by defining a custom .jsbeautifyrc file and specify "indent_size": 3 in specified language section.
