### ISSUE TITLE
js `sfasdff ${sfs} sdfds` is not formatted correct

### ISSUE THREAD

**Issue by leeseean** [HookyQR/VSCodeBeautify#187]
when I beautify a string with "\` "，just like 
```
`sfasdff ${sfs} sdfds`
```
,it does not work correct,
such as 
```
`sfasdff ${sfs.map(a=>return 444)} sdfds`
```
  -> 
```
`  
sfasdff $ { sfs.
map(a =>
return 444) } sdfds
`
```
,this is not the result I want.
can you fix this bug?

**Comment by HookyQR** [comment]
I am unable to replicate this issue.

**Comment by HookyQR** [comment]
Closed due to no response.
