### ISSUE TITLE
Add support for unindent_chained_method

### ISSUE THREAD

**Issue by susemeee** [HookyQR/VSCodeBeautify#188]
* **Operating System (+Version)**:  Windows 10, version 1709
* **VS Code Version**: 1.18.0
* **beautify Version**: 1.1.1

https://github.com/beautify-web/js-beautify/pull/927

**NOTE:** Please provide code snippets instead of screen shots. Your issue needs to be replicated, and we need the failing code (text) to do this.

Provide the settings you use: 
(VS Code workspace and user settings, .jsbeautifyrc, .editorconfig)
eg.:
VS Code:
```javascript
{
	"editor.formatOnSave": false,
	"editor.formatOnPaste": true
}
```
.jsbeautifyrc
```javascript
{
  "eol": "\n",
  "indent_char": " ",
  "indent_size": 2,

  ...

  "js": {
    "end_with_newline": true,
    "space_after_anon_function": true,
    "space_before_conditional": true,
    "unindent_chained_method": true
  }
}
```
## Action performed
Format javascript file with `HookyQR.beautifyFile` command

## Expected results
Expected
```javascript
foo()
.bar()
.baz();
```
to be remained as
```javascript
foo()
.bar()
.baz();
```
as unindent_chained_method is true.

## Actual results
Details of what happened ...
```javascript
foo()
.bar()
.baz();
```
is transformed into
```javascript
foo()
  .bar()
  .baz();
```

It is a recently added feature of js-beautify (See https://github.com/beautify-web/js-beautify/pull/927) and I wonder if there is any modification to support the new option.

**Comment by HookyQR** [comment]
Has not been rolled in yet, but it's on its way.

**Comment by HookyQR** [comment]
It's in.

**Comment by gaby64** [comment]
is it?

not working for me

```js
"beautify.config": {
    "brace_style": "collapse,preserve-inline",
    "break_chained_methods": true,
    "unindent_chained_method": true
}
```
