### ISSUE TITLE
calling beautify clones the code at the end

### ISSUE THREAD

**Issue by cristiandan** [HookyQR/VSCodeBeautify#19]
in my cordova js app, in the index.html file, when I call beautify it copies the entire content from the index.html to the end of file again.
I attached the file with the cloned content
[index.html.zip](https://github.com/HookyQR/VSCodeBeautify/files/259843/index.html.zip)

**Comment by HookyQR** [comment]
Hi @cristiandan, update your beautify extension. This issue came about with a change in VS Code 1.1 and has been addressed. The current extension version is 0.1.5.
