### ISSUE TITLE
HTML format for Laravel Blade

### ISSUE THREAD

**Issue by hjgarcia1** [HookyQR/VSCodeBeautify#190]
* **Mac OS Sierra**: 
* **1.19**: 
* **1.1.1**: 

When you format Laravel Blade files you get the following results. Can we have the plugin ignore (leave as white space) laravel blade tags (@extends @section @stop)? There are more laravel tags. 

Maybe it already does this and i just don't know how to set it up.

VS Code settings:
```javascript
    "beautify.language": {
        "js": {
            "type": [
                "javascript",
                "json"
            ],
            "filename": [
                ".jshintrc",
                ".jsbeautifyrc"
            ]
            // "ext": ["js", "json"]
            // ^^ to set extensions to be beautified using the javascript beautifier
        },
        "css": [
            "css",
            "scss"
        ],
        "html": [
            "htm",
            "html",
            "blade.php"
        ]
    },
    "html.format.endWithNewline": true,
    "html.format.maxPreserveNewLines": 1,
    "html.format.indentHandlebars": true,
    "html.format.preserveNewLines": true,
    "html.format.wrapLineLength": 0    
```

## Expected results
```
@extends('layouts.book') 

@section('hero-image')
<img src="" alt="" class="img-fluid">
@stop 
```

## Actual results
```
@extends('layouts.book') @section('hero-image')
<img src="" alt="" class="img-fluid"> @stop @section('content')
```

**Comment by brnmonteiro** [comment]
+1

**Comment by MarkusPayne** [comment]
Anyone have any ideas?  I've been struggling with this as well and have tried a bunch of extensions and settings with no luck.

**Comment by prasadfutballer** [comment]
same here, any help would be great

**Comment by HookyQR** [comment]
The extension doesn't handle these tags. Sorry.

**Comment by brnmonteiro** [comment]
Im using [this](https://gist.github.com/brnmonteiro/3660b71dbc68691cdc8ac41cec379e2f) mod for jsbeautify

**Comment by MarkusPayne** [comment]
The mod @brnmonteiro mentioned works for me.  It took me a little bit to figure out how to implement it so here are the steps that worked for me (on Ubuntu):

1. cd ~/.vscode/extensions/HookyQR.beautify-1.1.1
2. npm install js-beautify  (needed some additional files to complete the build)
3. open js/lib/beautify-html.js and add the code from the gist
3. open tools/build.sh and comment out "generate tests" in the build_js() function (was throwing an error for me)
5. run ./build js

when that's done add "blade" to the bottom of your User Settings "beautify.language" config:

        "html": [
            "htm",
            "html",
            "blade"
        ]
Then I created a custom keyboard shortcut to trigger the formatting

**Comment by brnmonteiro** [comment]
Install Beautify extension, change
~/.vscode/extensions/HookyQR.beautify-1.1.1/node_modules/js-beautify/js/lib/beautify-html.js
and reload vscode.

**Comment by HookyQR** [comment]
Not related to this extension. See the upstream `js-beautify` project.
