### ISSUE TITLE
comment in css or sass file formatting issue

### ISSUE THREAD

**Issue by gpradeepjain** [HookyQR/VSCodeBeautify#195]
This plugin i great. It works perfect for html and ts code. It works for sass files also. But i have a problem with its formatting i.e. below

code:
```
p{
}

// comment for below
div {
}

```
-------------------------

the comment goes to upper line after formatting like below

```
p{
} // comment for below

div {
}
```

How can i prevent it?

**Comment by HookyQR** [comment]
Yep, comment formatting is an issue. It's a `js-beautify` issue.
