### ISSUE TITLE
Format CSS files with {} on new lines

### ISSUE THREAD

**Issue by angelsix** [HookyQR/VSCodeBeautify#196]
I know the standard format for CSS is

```
.style {
  color: red;
}
```

However I think braces on the same line as the name is very bad and annoying for formatting. Your eye cannot line up missing or matches braces and it doesn't look right either.

I format my CSS like most other languages so its

```
.style
{
  color: red;
}
```

I cannot find any setting for allow this in this add-in. Does it exist? If not can it be added?

**Comment by HookyQR** [comment]
It does not. You could add it in the `js-beautify` project though. Good luck.
