### ISSUE TITLE
CSS如何设置成横排显示

### ISSUE THREAD

**Issue by chongzi5654565** [HookyQR/VSCodeBeautify#197]
CSS格式化之后，显示效果如下：
.headbox{
    display: block;
    width: 10px;
}
我想设置成点格式化之后显示效果如下：（横排，不换行）
.headbox {display:block;width: 10px;}

该如何做

**Comment by chongzi5654565** [comment]
没人知道怎么处理么

**Comment by HookyQR** [comment]
That's minified code. Try the `minify` extension. https://marketplace.visualstudio.com/items?itemName=HookyQR.minify
