### ISSUE TITLE
Display else / else if on a new line instead of on curly brace line.

### ISSUE THREAD

**Issue by ChrisTheEngineer** [HookyQR/VSCodeBeautify#198]
Currently when I format (all default settings), I get the following for conditional statements:

```
if(){

}else {

}
```

or 

```
if(){

}else if(){

}
```

I would like the else and else if to be on a separate line instead of the line of the ending curly brace, how do I do this when I format my JS document?

```
if() {

}
else {

}
```

**Comment by HookyQR** [comment]
There is no setting for this. Consider contributing to https://github.com/beautify-web/js-beautify
