### ISSUE TITLE
case statement and brackets

### ISSUE THREAD

**Issue by tsingwong** [HookyQR/VSCodeBeautify#199]
* **Operating System (+Version)**: Mac OS 10.12.6
* **VS Code Version**:  1.19.2
* **beautify Version**:  1.6.14

.jsbeautifyrc
```javascript

{
    "eol": "\n",
    "end_with_newline": true,
    "indent_char": " ", 
    "indent_size": 4, 
    "indent_with_tabs": false, 
	"indent_handlebars": true,
    "preserve_newlines": true, 
    "brace_style": "collapse, preserve-inline", 
    "max_preserve_newlines": 10, 
    "wrap_line_length": 120, 
    "extra_liners": ["head", "body", "/html"], 
    "indent_body_inner_html": true, 
    "indent_handlebars": false, 
    "indent_inner_html": false, 
    "wrap_attributes": "auto", 
    "wrap_attributes_indent_size": 4,
    "newline_between_rules": true, 
    "selector_separator_newline":true,
    "space_around_combinator": false,
    "break_chained_methods": true, 
    "comma_first": false, 
    "keep_array_indentation": false, 
    "keep_function_indentation": false, 
    "operator_position": "after-newline", 
    "space_after_anon_function": true,
    "space_before_conditional": true, 
    "space_in_empty_paren": false, 
    "space_in_paren": false
}

```
## Action performed
```javascript
switch (test) {
    case true:{
        let a = 1;
        break;
    }  

    default:
        break;
}
```
![image](https://user-images.githubusercontent.com/16622888/35328650-089a2b0a-0138-11e8-9af2-9a7e28411b6e.png)

beause of Eslint rules [no-case-declarations](https://eslint.org/docs/rules/no-case-declarations)

> To ensure that the lexical declaration only applies to the current case clause wrap your clauses in blocks.

## Expected results

![image](https://user-images.githubusercontent.com/16622888/35328650-089a2b0a-0138-11e8-9af2-9a7e28411b6e.png)

I hope it won't change， but...

## Actual results
![image](https://user-images.githubusercontent.com/16622888/35365674-c604bc78-01b0-11e8-94f5-d1233b1b07cc.png)

Thanks for your help~~~

**Comment by HookyQR** [comment]
That seems to be an eslint issue. Your case is still wrapped in braces. I'm unable to replicate. What are your eslint settings?

**Comment by tsingwong** [comment]
Here is my [.eslintrc.js ](https://gist.github.com/tsingwong/cdd8d4fe571d3102c27d8f9f529a2c1d)。

I just want that the braces do not in newline
but when i use beautify, the braces after `case` in newline, QAQ~~

**Comment by HookyQR** [comment]
I agree, it's annoying, but I don't see a way either. Have a look at the js-beautify repo, or check out prettier, that may do what you want. Somewhat less options, but who knows?

**Comment by tsingwong** [comment]
Thanks for your help @HookyQR ~~
