### ISSUE TITLE
.jsbeautifyrc file not being used

### ISSUE THREAD

**Issue by nquintal** [HookyQR/VSCodeBeautify#2]
I am trying to make VSCodeBeautify take my .jsbeautifyrc file into account inside a Node.JS project.
I cannot seem to find the right place.
I've tried putting it at the root of the folder opened in VSCode.
I've tried putting it inside the .vscode folder.
I've tried putting it at the same level as the package.json.
I've tried restarting VSCode couple times.

None of theses locations seems to do anything.

Here's my .jsbeautifyrc file

```javascript
// Documentation: https://github.com/einars/js-beautify/
{
    "indent_size": 2,
    "indent_char": " ",
    "eol": "\n",
    "indent_level": 0,
    "indent_with_tabs": false,
    "preserve_newlines": true,
    "max_preserve_newlines": 10,
    "jslint_happy": false,
    "space_after_anon_function": false,
    "brace_style": "collapse",
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "space_before_conditional": true,
    "break_chained_methods": false,
    "eval_code": false,
    "unescape_strings": false,
    "wrap_line_length": 0,
    "wrap_attributes": "auto",
    "wrap_attributes_indent_size": 4,
    "end_with_newline": false
}
```

**Comment by HookyQR** [comment]
Hi Nicolas,

You should have your `.jsbeautifyrc` file at the root of your workspace, just as you first did. The location is not the problem. The file you have provided isn't technically valid JSON. A JSON file can't have any comments in it. If you remove the comment line from the top of the file, it should work fine. I'll tweak the code to allow a comment at the top for you though, cos it seems like a fair idea to have the documentation reference there.

**Comment by HookyQR** [comment]
version 0.0.5 published to VSCode marketplace.
