### ISSUE TITLE
beautify.onSave saving loop

### ISSUE THREAD

**Issue by kerko** [HookyQR/VSCodeBeautify#20]
When in set 
`"beautify.onSave": true`

on save vscode starts to constantly save and change the file repedeatly times. Only way to stop it, is to switch to another file. 
This is really annoying since the file is constantly marked as saved/nonsaved and also clears the undo history.

**Comment by kerko** [comment]
Apparently this was caused by beautify wanting to remove the final new line and my .editorconfig told vscode to insert an newline on save. So they both removed and added it constantly.

**Comment by abhishekisnot** [comment]
@Keale2 Apparently we are running into this. What was the setting you had to change in .editorconfig and settings.json for vscode?

**Comment by abhishekisnot** [comment]
awesome, adding .jsbeautifyrc with below content solved this issue:

<pre>
{
    "html": {
        "end_with_newline": true
    },
    "css": {
        "end_with_newline": true
    },
    "js": {
        "end_with_newline": true
    }
}
</pre>

**Comment by HookyQR** [comment]
@abhishekisnot, you can put the "end_with_newline" definition in the base JSON block if you're setting it the same for all three, no need to put it in three times.
