### ISSUE TITLE
[Q]What's the difference between prettier and Beautify?

### ISSUE THREAD

**Issue by mrdulin** [HookyQR/VSCodeBeautify#201]
vscode + prettier works fine.

so, what's the difference between prettier and Beautify?

**Comment by HookyQR** [comment]
First off, prettier didn't exist till 11 months after this extension was written, let alone the 8 or so years after js-beautify was written.

This extension was written specifically to enable code formatting for JS, HTML and CSS as provided by  js-beautify, including parsing the config file. VS Code originally used js-beautify internally, but failed to parse the config. Config file use was the intent of this extension.

Prettier looks pretty nice (see what I did there?) but it doesn't have the same configurability as js-beautify.

vscode + beautify works fine too. Assuming you're not trying to use it for languages it wasn't designed for (which is what most of the issues logged here are about).

**Comment by blowsie** [comment]
Prettier is opinionated and not dependant on IDE
Prettier does not support HTML, only JSX

**Comment by mrdulin** [comment]
@HookyQR @blowsie 
Can I use them together? Is there any conflict between them?

I mess up when use `Beautify`(. jsbeautifyrc), `Prettier`(.prettierrc), `.editorconfig`, `vscode internal formatter`.

Beautify says it will merge `editorconfig` settings.

**Comment by HookyQR** [comment]
You're not the only one. ;)
VS Code may apply all, or none of the formatters, depending on best match and/or time it takes to perform the function. Yes `beautify` will merge in the setting from your `.editorconfig` files.

**Comment by clitetailor** [comment]
I have one question, is there any option to turn off beautifier on js file because i prefer prettier for js? :/

**Comment by HookyQR** [comment]
Add `"beautify.language": { "js": [] }` to your VS Code settings.

**Comment by clitetailor** [comment]
That's great, thanks!

**Comment by jasonsbarr** [comment]
@clitetailor if you still have issues with conflicts between prettier and another formatter you can also add this to your VS Code settings:

```json
"[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
}
```

With the value for `editor.defaultFormatter` set to whatever prettier extension you have installed, obviously.

**Comment by mrdulin** [comment]
@jasonsbarr Thanks. I feel bad that there are too many tools and configurations. And these tools' features are often overlapped or conflicted.

**Comment by jasonsbarr** [comment]
So true. The sheer number of options is intimidating.
