### ISSUE TITLE
如何只关闭css格式化

### ISSUE THREAD

**Issue by CGS0408** [HookyQR/VSCodeBeautify#203]
* **Operating System (+Version)**: 
* **VS Code Version**: 
* **beautify Version**: 

**NOTE:** Please provide code snippets instead of screen shots. Your issue needs to be replicated, and we need the failing code (text) to do this.

Provide the settings you use: 
(VS Code workspace and user settings, .jsbeautifyrc, .editorconfig)
eg.:
VS Code:
```javascript
{
	"beautify.editorconfig": false,
	"editor.formatOnSave": true
}
```
.jsbeautifyrc
```javascript
{
	"max_preserve_newlines": 2,
	"preserve_newlines": true,
	"end_with_newline": true,
	"brace_style": "collapse-preserve-inline",
}
```
## Action performed
Format javascript file with `HookyQR.beautifyFile` command
_provide example code_

## Expected results
Expected ... to ...
_provide example (expected) output_

## Actual results
Details of what happened ...
_provide example (actual) output_

**Comment by HookyQR** [comment]
If you want to turn off formatting of one type, set the language array to empty in your VS Code user settings. Eg:
```javascript
"beautify.language.css" = []
```

This will not stop it from formatting css inside html though.
