### ISSUE TITLE
Beautify File Command not working - beautify.confit set to null even though config is object

### ISSUE THREAD

**Issue by wjpurdum** [HookyQR/VSCodeBeautify#204]
* **Operating System (+Version)**: 
* **VS Code Version**: 
* **beautify Version**: 

**NOTE:** Please provide code snippets instead of screen shots. Your issue needs to be replicated, and we need the failing code (text) to do this.

Provide the settings you use: 
(VS Code workspace and user settings, .jsbeautifyrc, .editorconfig)
eg.:
VS Code:
```javascript
In the default settings, my beautify.config is null:
{
	  "beautify.config": null,
}
```
But I have my beautify.config object as not null:
{
	"beautify.config": {
        "brace_style": "collapse,preserve-inline",
        "break_chained_methods": false,
        "e4x": true,
        "end_with_newline": true,
        "end_with_comma": false,
        "indent_char": " ",
        "indent_level": 0,
        "indent_size": 2,
        "indent_with_tabs": false,
        "jslint_happy": false,
        "keep_array_indentation": false,
        "keep_function_indentation": false,
        "preserve_newlines": false,
        "max_preserve_newlines": 4,
        "preserve_ternary_lines": true,
        "space_after_anon_function": true,
        "space_after_named_function": true,
        "space_before_conditional": true,
        "space_in_empty_paren": false,
        "space_in_paren": false,
        "unescape_strings": false,
        "wrap_attributes": "auto",
        "wrap_attributes_indent_size": 2,
        "wrap_line_length": 0
    },
}
```
## Action performed
Select the Beautify File option from the Command pallet

## Expected results
Expected ... to ...
Beautify the file

## Actual results
Details of what happened ...
No formatting occurs (used to format though)

**Comment by HookyQR** [comment]
`"beautify.config"` is set to `null` by default because it has many options, such as filename, or an object, like you have provided. If it is set to `null` it is simply ignored.
