### ISSUE TITLE
Too many line breaks in javascript code 

### ISSUE THREAD

**Issue by bendpx** [HookyQR/VSCodeBeautify#205]
* **Operating System (+Version)**: 
Mac High Sierra
* **VS Code Version**: 
1.20
* **beautify Version**: 
latest 

* **beautifier configs:**
```
{
  "indent_size": 4,
  "wrap_line_length": 1500,
  "brace_style": "collapse"
}
```

for the following code snippet:
``` javascript
            APP_CACHE.put(
                applications[app]["ABCDABCD"] + "_APP",
                applications[app]
            );
```
I'd like it all to be in one line, but my beautifier break it into 4 lines. is it possible to configure?

**Comment by elvinmeza** [comment]
Same question here. Is there any setting that I'm missing that could handle it?

**Comment by HookyQR** [comment]
Hmm, I can't seem to replicate the issue. If I input it as it is, I get 4 lines. If I input it on one line, I get one line.

**Comment by elvinmeza** [comment]
Well, something else messed up with the excessive break lines, so to solve it I did set up the setting wrap_line_length = 0, then with ctrl+j removed all the break lines on the file and run again beautify. The code was formatted as expected. Thanks!
