### ISSUE TITLE
CSS { "brace_style": "expand" }

### ISSUE THREAD

**Issue by StyleShit** [HookyQR/VSCodeBeautify#210]
How can I use `"brace_style": "expand"` for CSS code?

**Comment by HookyQR** [comment]
Can't be done I'm afraid. That's a JS only setting.

**Comment by i4004** [comment]
What's the purpose of this limitation?

**Comment by HookyQR** [comment]
It's not a deliberate limitation. The formatters for HTML, CSS and JS are all seperate. Feel free to fix in the root project: https://github.com/beautify-web/js-beautify
