### ISSUE TITLE
Format include?

### ISSUE THREAD

**Issue by chrisyoong-ri** [HookyQR/VSCodeBeautify#211]
* **Operating System (+Version)**: macOS 10.13.2
* **VS Code Version**: 1.20.1
* **beautify Version**: 1.3.0

**NOTE:** Please provide code snippets instead of screen shots. Your issue needs to be replicated, and we need the failing code (text) to do this.

<img width="745" alt="formqt" src="https://user-images.githubusercontent.com/35263668/36899667-0d02a18e-1e18-11e8-8ab8-b0f081aa5250.png">

How can I format an "include" so that it looks like a normal declaration and not in one line?

**Comment by HookyQR** [comment]
First of all, thanks for providing a screen shot and making me type out all your code myself. 👎

**Comment by HookyQR** [comment]
Secondly, I don't think you can. Beautify is specifically for CSS and doesn't have any options for formatting this kind of stuff. You could work on supporting it by contributing to [js-beautify](https://github.com/beautify-web/js-beautify).

**Comment by chrisyoong-ri** [comment]
Apologies, I mis-read it I thought you _wanted_ it in a screenshot (I thought it was an odd request).  Thanks for your help at any rate.
