### ISSUE TITLE
Breaking lines on import { ... } from "./file.js"

### ISSUE THREAD

**Issue by lealcy** [HookyQR/VSCodeBeautify#212]
* **Operating System (+Version)**: Windows 10
* **VS Code Version**: 1.21.0-insider
* **beautify Version**: 1.3.0

Is there a way to prevent Beautify from break imports in multiple lines?

## Action performed
import { Game } from "./Game/Game.js";
import { Vector } from "./Game/Vector.js";
import { Tile } from "./Game/Tile.js";

## Expected results
import { Game } from "./Game/Game.js";
import { Vector } from "./Game/Vector.js";
import { Tile } from "./Game/Tile.js";

## Actual results
import {
    Game
} from "./Game/Game.js";
import {
    Vector
} from "./Game/Vector.js";
import {
    Tile
} from "./Game/Tile.js";

**Comment by HookyQR** [comment]
In you VS Code settings under `beautify.config` or in your `.jsbeautifyrc` add: `"brace_style": "collapse,preserve-inline"`.
