### ISSUE TITLE
Include editor config

### ISSUE THREAD

**Issue by awebdeveloper** [HookyQR/VSCodeBeautify#22]
add editorconfig support

**Comment by HookyQR** [comment]
Hi @awebdeveloper, I'm not sure what you're asking for. There is support for configuring your beautify options through extended support of the `.jsbeautifyrc` config file. There is even support included in the extension to help with editing that file.

**Comment by awebdeveloper** [comment]
i was referring to http://editorconfig.org

**Comment by HookyQR** [comment]
There is an existing Editor config extension. See: https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

The beautify extension uses the `.jsbeautifyrc` config file which provided a great deal more formatting options, specific to the languages js-beautify supports. Most teams that require these more specific formatting (that js-beautify provides) details will share this file in their repos. Feel free to checkout the EditorConfig extension instead. I doubt there would be a conflict, but if there is let me know.

**Comment by elebetsamer** [comment]
I think this would be great to add as well. The [beautifier](https://github.com/Glavin001/atom-beautify) I use in Atom reads the .editorconfig file in addition to the .jsbeautifyrc file and combines the rules to apply formating. It'd be great if this extension did something similar.

**Comment by herrherrmann** [comment]
Although it's cool to stick to one configuration file (`.jsbeautifyrc` in this case) to limit the scope of the extension and make it more maintainable, I must say that **if** a combined approach (like mentioned by elebetsamer) would work well, I'd also love to see it in this extension. <3

**Comment by HookyQR** [comment]
The command line version of `js-beautify` now supports `. editorconfig`, and I just released 0.2.0 with a change to the default config handling, so I'll look into supporting this at the next iteration.

**Comment by HookyQR** [comment]
Done. Available in Version 0.3.1.
