### ISSUE TITLE
Request: Insert new lines before certain keywords

### ISSUE THREAD

**Issue by tommai78101** [HookyQR/VSCodeBeautify#228]
* **Operating System (+Version)**: Windows 7 Enterprise LTS
* **VS Code Version**:  Stable 1.22
* **beautify Version**:  1.3.0

I'm looking into JS formatters that supports new lines insertions (not spaces, new lines).

I need to find formatters that would insert new lines before certain JS keywords. For example, if we use `else`, once it is formatted, the code will look like this:

```
if (foo()){
  bar();
}
else {
  baz();
}
```

And since this is the popular JS formatter for VS Code, I would like to request to have new lines insertions option for `.jsbeautifyrc` file.

**Comment by HookyQR** [comment]
`"brace_style": "end-expand,preserve-inline"` will do this for you.
