### ISSUE TITLE
Missing settings warning when offline

### ISSUE THREAD

**Issue by aeschli** [HookyQR/VSCodeBeautify#229]
_From @roblourens on April 24, 2018 17:12_

Testing #48391

- Install the beautify extension
- Create an extension with an "application" scope setting, following #48391
- Go offline
- Set that setting in the workspace settings.json
- There is a warning that the beautify json schema can't be downloaded, but no warning about the application scoped setting

If you disable the beautify extension, then the warning is shown properly even when offline. So it seems like the other missing schema is interfering even though it shouldn't matter for this case.

_Copied from original issue: Microsoft/vscode#48572_

**Comment by aeschli** [comment]
_From @sandy081 on April 25, 2018 8:10_

@aeschli Known?

**Comment by aeschli** [comment]
Looks like a bug in the beautify extension.
It uses a external ref in the schema: https://github.com/HookyQR/VSCodeBeautify/blob/63b6a2261efc07af7dd7e9df6920f499da54f97c/package.json#L51

**Comment by aeschli** [comment]
Please do not use $ref in configurations but inline all what is necessary.

**Comment by HookyQR** [comment]
Well, that's double handling and prone to error. Perhaps you (vscode) should download the reference and keep it for offline access, updating when back on line of course.

I'm surprised the extension writer should 'copy and paste' is your answer here. Especially since the system is set up for the `$ref` to work.

**Comment by HookyQR** [comment]
Have embedded the settings. They're now replicated in three places.
