### ISSUE TITLE
React Native: JSX embedded in .js file

### ISSUE THREAD

**Issue by mkdotcom** [HookyQR/VSCodeBeautify#23]
I work with ReactNative, and I see Beautify destroys JSX code when it's embedded in the .js file

**Comment by HookyQR** [comment]
The extension uses js-beautify on the inside. You can look at the [React related issues](https://github.com/beautify-web/js-beautify/search?q=react&type=Issues&utf8=%E2%9C%93) on that project to track what support is available. I update the internal version regularly.
