### ISSUE TITLE
(vsCode 1.23.0) Beautify formatter on save takes precedent over Prettier

### ISSUE THREAD

**Issue by ekfuhrmann** [HookyQR/VSCodeBeautify#230]
It seems that with the most recent update to vsCode (1.23.0), Beautify's `formatOnSave` feature is preventing Prettier from running properly on save.

https://github.com/prettier/prettier-vscode/issues/439
https://github.com/prettier/prettier-vscode/issues/440

**Comment by jamesplease** [comment]
I only use Beautify from the Cmd+P list, so I added this to my user settings to get around this issue:

```
"beautify.ignore": "**/*"
```
