### ISSUE TITLE
SCSS conflict in using :before and :after and @extend

### ISSUE THREAD

**Issue by Joseph-a** [HookyQR/VSCodeBeautify#231]
* **Operating System (+Version)**:  Windows 10
* **VS Code Version**: 1.23.0
* **beautify Version**: 1.3.0

Hi,
In SCSS development we need to extend the before of some pre-defined css. As an example:
```
.class-1{
    color: blue;
    &:before{
        content:'';
        display: block;
        background: red;
    }
}
.class-2{
    &:after{
        @extend .class-1:before;
    }
}
```

By using beautify for formatting this code, it adds **an space before :before** and it will be like below which cause error in compiling the scss files. 
```
.class-2{
    &:after{
        @extend .class-1: before;
    }
}
```
I hope you understand the issue and fix it in the new versions.

Regards,

**Comment by HookyQR** [comment]
It's not an SCSS beautifier by default, it works for some things because of how close it is to CSS. Sorry, no fix is likely.
