### ISSUE TITLE
delete space before and after symbol "?" in typescript file

### ISSUE THREAD

**Issue by mrdulin** [HookyQR/VSCodeBeautify#232]
* **Operating System (+Version)**:  OS X
* **VS Code Version**:  1.22.2 (1.22.2)
* **beautify Version**: 1.3.0

**NOTE:** Please provide code snippets instead of screen shots. Your issue needs to be replicated, and we need the failing code (text) to do this.

Provide the settings you use: 
(VS Code workspace and user settings, .jsbeautifyrc, .editorconfig)
eg.:
VS Code:
```javascript
"beautify.language": {
    "js": {
      "type": [
        "javascript",
        "json",
        "typescript"
      ],
      "filename": [
        ".jshintrc",
        ".jsbeautify"
      ]
    },
    "css": [
      "css",
      "scss"
    ],
    "html": [
      "htm",
      "html"
    ]
  }
```
.jsbeautifyrc
```javascript
{
  "indent_size": 2,
  "brace_style": "none,preserve-inline"
}
```
## Action performed
Format typescript file with `HookyQR.beautifyFile` command

```typescript
interface SquareConfig {
  color?: string;
  width?: number;
  [propName: string]: any;
}
```

## Expected results
Expected ... to ...

```typescript
interface SquareConfig {
  color?: string;
  width?: number;
  [propName: string]: any;
}
```

## Actual results
Details of what happened ...

```typescript
interface SquareConfig {
  color ? : string;
  width ? : number;
  [propName: string]: any;
}
```

notice the space before and after the symbol "?"

**Comment by winstef** [comment]
Same issue when trying to format JS code using an optional chaining operator: 
https://github.com/tc39/proposal-optional-chaining

**Comment by HookyQR** [comment]
It's not a typescript formatter, so there's going to be some issues. This is one of them.
Regarding optional chaining, it's not currently supported.
