### ISSUE TITLE
Messes up JSX 

### ISSUE THREAD

**Issue by ghost** [HookyQR/VSCodeBeautify#235]
VSCodeBeautify seems to mess JSX files.

I have this code:

![1](https://user-images.githubusercontent.com/37333598/40556039-3b585232-605c-11e8-9829-12da642ebc0b.PNG)

When I click Ctrl+Shift+I, it tells me first that:

> Could not determine type to beautify please choose.

Allows me to choose from:
JS, CSS, HTML.

When I choose JS.

This is result I get:

![2](https://user-images.githubusercontent.com/37333598/40556074-5b7da954-605c-11e8-8c3b-d4e8fdf0a9fb.PNG)

why?

If relevant, OS is Windows.

**Comment by helloanil** [comment]
+1

**Comment by Waymoot** [comment]
+1

**Comment by HookyQR** [comment]
Bye default, js-beautify doesn't support jsx. Add `"e4x": true` to your `.jsbeautifyrc` file if you're using one, or to your `"beautify.config"` setting in your vs-code user or workspace settings.

It hasn't identified the type because you have it set to *JavaScript React* which is not handled by default. Add:
```json
  "beautify.language": {
    "js": {
      "type": [
        "javascript",
        "json",
        "javascriptreact"
      ]
    }
  }
```

**Comment by theblang** [comment]
@HookyQR After having added both the `beautify.config` change and `beautify.language` change, I'm still not seeing my "JavaScript React" files be processed by beautify. I wonder if there's anything else I might be missing?

**Comment by HighSoftWare96** [comment]
Using this extension with react or react native even with the settings reported above is almost impossible..

**Comment by HookyQR** [comment]
With
```json
{
  "beautify.language": {
    "js": {
      "type": [
        "javascript",
        "json",
        "jsonc",
        "javascriptreact"
      ]
    }
  },
  "beautify.config": {
    "e4x": true
  }
}
```
And input of:
```jsx
import React, { Component } from 'react';

export default class TempInput extends Component {
  render() {
    return (
      <div>
        <input
        value={temp}
        onChange={this.handleChange}
        />
      </div>
    )
  }
}
```
I get
```jsx
import React, { Component } from 'react';

export default class TempInput extends Component
{
    render()
    {
        return (
            <div>
        <input
        value={temp}
        onChange={this.handleChange}
        />
      </div>
        )
    }
}
```

**Comment by HookyQR** [comment]
Unfortunately, it only formats the javascript, leaving the XML tags as they were. The white space leading up to the first tag is considered to be part of the javascript, which is why you get the odd indenting.
