### ISSUE TITLE
dynamic import problem

### ISSUE THREAD

**Issue by toobull** [HookyQR/VSCodeBeautify#236]
* **Operating System (+Version)**: OSX 10.13.3
* **VS Code Version**:  1.22.2
* **beautify Version**: 1.3.0

**NOTE:** Please provide code snippets instead of screen shots. Your issue needs to be replicated, and we need the failing code (text) to do this.

Provide the settings you use: 
(VS Code workspace and user settings, .jsbeautifyrc, .editorconfig)
eg.:
.jsbeautifyrc
```javascript
{
	"eol": "\n",
        "preserve_newlines": true,
        "brace_style": "collapse",
        "max_preserve_newlines": 10,
        "wrap_line_length": 0,
        "break_chained_methods": false,
        "comma_first": false,
        "e4x": false,
        "indent_level": 0,
        "jslint_happy": false,
        "keep_array_indentation": true,
        "keep_function_indentation": false,
        "operator_position": "before-newline",
        "space_after_anon_function": true,
        "space_before_conditional": true,
        "space_in_empty_paren": false,
        "space_in_paren": false,
        "unescape_strings": false,
        "unindent_chained_methods": true
}
```
## Action performed
Format javascript file with `HookyQR.beautifyFile` command
_provide example code_

```javascript
    import(`./abcd`)
```

## Expected results
Expected ... to ...
_provide example (expected) output_

```javascript
    // I hope between `import` and `(` with no space.
    import(`./abcd`)
```
## Actual results
Details of what happened ...
_provide example (actual) output_

```javascript
    // Actual, There is a space between `import` and `(`.
    import (`./abcd`)
```
I don't know it a feature or a bug?
And is there any way don't add space  between `import` and `(`?

**Comment by HookyQR** [comment]
import is a keyword statement with specific syntax, not a method, so it should be followed by a space, you can drop the brackets though.
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

**Comment by toobull** [comment]
import() is a proposal:
https://github.com/tc39/proposal-dynamic-import

But actually, webpack & babel etc. support it, maybe we should support it.

Webpack need no space between `import` & `(`.

**Comment by HookyQR** [comment]
Yep, I'm just telling you why. I don't write the formatter, just the extension that uses it. Have a look at https://github.com/beautify-web/js-beautify
