### ISSUE TITLE
Copy/Paste adds new line

### ISSUE THREAD

**Issue by hpawe01** [HookyQR/VSCodeBeautify#237]
* **Operating System (+Version)**: Win10
* **VS Code Version**: 1.23.1
* **beautify Version**:  1.3.0

Provide the settings you use: 
.jsbeautifyrc
```javascript
{
  "indent_char": " ",
  "indent_size": 2,
  "preserve_newlines": true,
  "end_with_newline": true,
  "js": {
    "allowed_file_extensions": ["ts", "js", "json", "jshintrc", "jsbeautifyrc"],
    "space_before_conditional": true,
    "space_after_anon_function": true,
    "keep_function_indentation": true,
    "keep_array_indentation": true,
    "max_preserve_newlines": 2
  }
}
```
## Action performed
Copy selection (part of a line) -> insert selection somewhere

## Expected results
Selection is inserted.

## Actual results
Selection is inserted and a new line is added below the line where the selection was pasted.

When I deactivate Beautify Extension, it works as expected.

This issue is a copy of https://github.com/Microsoft/vscode/issues/49662 but as it seems to be an Beautify-related issue I added the issue here.

**Comment by lardissone** [comment]
I can confirm this issue. Disabling the extension the new line is not inserted.

**Comment by grumar** [comment]
+1

**Comment by rathishrms** [comment]
i dont have the beautify extension, but still the issue persists. Any pointers?

**Comment by Darzwaitz** [comment]
@rathishrms - Hey there - did you find a solution for this?
I have not got the beautify extension either, and an extra new line is added when I copy & paste.
Tried changing 'Format on paste' in settings, no change if true or false (in User and Workspace settings)
