### ISSUE TITLE
fails to parse .jsbeautifyrc if $schema specified

### ISSUE THREAD

**Issue by af4jm** [HookyQR/VSCodeBeautify#239]
* **Operating System (+Version)**: Microsoft Windows [Version 10.0.15063]
* **VS Code Version**: 1.23.1
* **beautify Version**: 1.3.0

.jsbeautifyrc
```javascript
{
    "$schema": "http://json.schemastore.org/jsbeautifyrc",
    ...
}
```

## Action performed
Format json file with `HookyQR.beautifyFile` command

## Expected results
File is formatted

## Actual results
Error...

> Found a .jsbeautifyrc file [c:\src\MyRepo\\.jsbeautifyrc], but it didn't parse correctly.

Removing the $schema line from .jsbeautifyrc results in expected behavior.

**Comment by HookyQR** [comment]
It's a parsing issue in the comment removal regex. Fixing it now.

**Comment by jcklpe** [comment]
@HookyQR  Is it still the case that comments will cause the .jsbeautifyrc file to fail to parse?

I like to put comments throughout my settings files so keep notes on things, in addition to finding it useful to marking out certain kinds of settings temporarily as I experiment with different settings. 

I also have completely removed the comments from my file and it still fails to parse. Could it be because I have the following in my vscode settings?

```
 "files.associations": {
    ".jsbeautifyrc": "jsonc",
    "*.json": "jsonc"
  },
```

this is the .jsbeautifyrc I got off a gist that I was trying to use
```
{
    "html": {
        "allowed_file_extensions": [
            "htm",
            "html",
            "xhtml",
            "shtml",
            "xml",
            "svg"
        ],
        "brace_style": "end-expand",
        "end_with_newline": false,
        "indent_char": " ",
        "indent_handlebars": false,
        "indent_inner_html": true,
        "indent_scripts": "separate",
        "indent_size": 4,
        "max_preserve_newlines": 0,
        "preserve_newlines": true,
        "unformatted": [
            "pre",
            "sub",
            "sup",
            "em",
            "strong",
            "b",
            "u",
            "strike",
            "big",
            "small",
            "pre",
        ],
        "wrap_line_length": 0
    },
    "css": {
        "allowed_file_extensions": [
            "css",
            "scss",
            "sass",
            "less"
        ],
        "end_with_newline": false,
        "indent_char": " ",
        "indent_size": 4,
        "newline_between_rules": true,
        "selector_separator": " ",
        "selector_separator_newline": true
    },
    "js": {
        "allowed_file_extensions": [
            "js",
            "json",
            "jsonc",
            "jshintrc",
            "jsbeautifyrc",
            "jsx"
        ],
        "brace_style": "expand",
        "break_chained_methods": false,
        "e4x": true,
        "end_with_newline": true,
        "indent_char": " ",
        "indent_level": 0,
        "indent_size": 4,
        "indent_with_tabs": false,
        "jslint_happy": false,
        "keep_array_indentation": false,
        "keep_function_indentation": false,
        "max_preserve_newlines": 2,
        "preserve_newlines": true,
        "space_after_anon_function": false,
        "space_before_conditional": true,
        "space_in_empty_paren": false,
        "space_in_paren": false,
        "unescape_strings": false,
        "wrap_line_length": 0
    }
}
```

I've found that if I just use 

```
{
    "indent_size": 4,
    "indent_char": " ",
    "css": {
      "indent_size": 2
    }
  }
```

It will parse correctly. 

Which makes me think the gist settings I copied weren't properly set up json but it all looks correct formatting to me. 

Does the vscode jsbeautify only implement a subset of the total jsbeautify settings?

**Comment by armchairdeity** [comment]
Same problem... this is so annoying.

**Comment by tamilvendhank-helptap** [comment]
In my case, there was a trailing comma `,`!!!

**Comment by tamilvendhank-helptap** [comment]
Few years later:
@jcklpe, you have a trailing comma at `"pre",`
