### ISSUE TITLE
end_with_newline not respected

### ISSUE THREAD

**Issue by laggingreflex** [HookyQR/VSCodeBeautify#245]
* **Operating System (+Version)**:  Win 10
* **VS Code Version**: 1.24.1
* **beautify Version**: 1.7.5

**NOTE:** Please provide code snippets instead of screen shots. Your issue needs to be replicated, and we need the failing code (text) to do this.

Provide the settings you use: 
(VS Code workspace and user settings, .jsbeautifyrc, .editorconfig)
eg.:
VS Code:
```javascript
{
	"editor.formatOnSave": true
}
```
.jsbeautifyrc
```javascript
{
	"end_with_newline": true
}
```
## Action performed
Format javascript file with `HookyQR.beautifyFile` command

```
var a = 'a';

```
(newline at the end)
## Expected results
Expected ... to ...

```
var a = 'a';

```
(not change)

## Actual results

```
var a = 'a';
```
(removes the newline from the end)

This only seems to happen with the VS Code extension. Running `js-beautify` independently from command-line works as expected.

**Comment by laggingreflex** [comment]
Ah, nevermind. I was using the wrong keyboard shortcut- `HookyQR.beautify` when instead I should've been using `HookyQR.beautifyFile`. 

I see that `HookyQR.beautify` has been fixed recently to avoid inserting a new line when doing beautification on partial code -- which is exactly what "broke" my (incorrect) usage (i.e. I was using it on the entire file, and so the newline being inserted seemed correct to me).

Anyways 🍻 awesome extension.

**Comment by mjd507** [comment]
good job
