### ISSUE TITLE
Editorconfig should override VS Code workspace/user settings

### ISSUE THREAD

**Issue by GrimLink** [HookyQR/VSCodeBeautify#246]
* **OSX (10.13.4)**: 
* **VSCode v1.24.1**: 
* **Beautify v1.3.2**: 

When I use Beautify with no `.jsbeautifyrc`and user settings related to Beautify the tabSize is still affected by this.
I understand that a default is set.
But like the VSCode default workspace/user settings, this should be capable to be overridden by Editorconfig files.

Please change the order of the detection of settings.

From;

1. When not using a multi-root workspace:
2. When using a multi-root workspace:
3. Settings are translated from your VS Code workspace/user settings.
4. Any open editor settings (indent spaces/tabs) for the specific file are merged in.
5. Editorconfig settings are searched for (See http://editorconfig.org/) and are merged in.

To;

1. When not using a multi-root workspace:
2. When using a multi-root workspace:
3. Editorconfig settings are searched for (See http://editorconfig.org/) and are merged in.
4. Settings are translated from your VS Code workspace/user settings.
5. Any open editor settings (indent spaces/tabs) for the specific file are merged in.

**Comment by HookyQR** [comment]
editorconfig settings override VS Code and editor settings already.

tabSize is only related to the display width and nothing to do with actual file format. If you wish to use a specific number of spaces per indent, use `indent_style = space` and `indent_size = 4` (eg) instead. Beautify doesn't control the editor.

Sorry it took sooooooo long to get on to this.

**Comment by GrimLink** [comment]
@HookyQR no problem for the late reply 😉
I forgot that I even had this issue open.

Did a test just now and it looks like everything is working as expected.
So I am closing the issue.
