### ISSUE TITLE
Single Quotes (auto format) not working

### ISSUE THREAD

**Issue by borriej** [HookyQR/VSCodeBeautify#247]
* **OS X 10.13.5 **: 
* **VS Code 1.24.1**: 
* **Beautify 1.3.2**: 

Hi,

Thanks for this plug-in. 

I also have Prettier 1.5.0 installed

I have multiple files with styling settings:

* .editorconfig
```
# Editor configuration, see http://editorconfig.org
root = true

[*]
charset = utf-8
indent_style = space
indent_size = 2
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
max_line_length = off
trim_trailing_whitespace = false
```

* .jsbeautifyrc
```
{
  "tab_size": 2,
  "indent_size": 2,
  "indent_with_tabs": false,
  "editor.formatOnSave": false,
  "wrap_attributes": "force-aligned",
  "wrap_line_length": 120,
  "preserve_newlines": true,
  "end_with_newline": true,
  "newline_between_rules": true,
  "ignore": ".ftl",
  "singleQuote": true,
  "css": {
    "space_around_combinator": true
  }
}
```

* VS Code User Settings
```
{
  "editor.detectIndentation": false,
  "editor.formatOnPaste": true,
  "editor.formatOnSave": false,
  "editor.insertSpaces": true,
  "editor.tabSize": 2,
  "files.insertFinalNewline": true,
  "html.format.endWithNewline": true,
  "html.format.preserveNewLines": true,
  "html.format.wrapAttributes": "force-aligned",
  "prettier.printWidth": 120,
  "typescript.updateImportsOnFileMove.enabled": "always",
  "window.zoomLevel": 0,
  // "tslint.autoFixOnSave": true,
}
```

*Problem 1*
- When I autoformat a *.ts file with ```'CMD + SHIFT + F'``` ... this:

```
import { AppFooterComponent } from './components/app-footer/app-footer.component';
```

becomes:
```
import { AppFooterComponent } from "./components/app-footer/app-footer.component";
```

I would expect that the singleQuote would remain a singleQoute... because of ```"singleQuote": true,```

in my .jsbeautifyrc ... instead my singleQuote becomes a doubleQuote :(

I thought my .jsbeautifyrc would overwrite ALL formatting settings.

*Work around*
When add this to my VS Code Setting file:
```
  "prettier.singleQuote": true,
```
It does work...

Im really confused. SingleQoutes is true... 

*Problem 2*

- Overall... it's unclear to me which formatting plug-ins I should install...
- And how formatting rules are used... do they extend? or overwrite? which formatting sheets work together? 
- In the past i've had some .jsbeautifyrc properties being ignored.. So I disabled the plugin and autoformat on save

**Comment by ArthurBrito** [comment]
See #192. If you use prettier and format on save, the .jsbeautifyrc will be not read. But you can still use F1 and Beautify.  So you should use Prettier or VSCodeBeautify, not both.

**Comment by HookyQR** [comment]
Prettier is doing this , not Beautify. Beautify isn't pushy about your quote style like Prettier is.
You're mixing your settings files and content too. 
`"editor.formatOnSave"`, `"ignore"`, and `"singleQuote"` are not valid settings in your `.jsbeautifyrc` file.
