### ISSUE TITLE
Inline Space Between tag ending > and tag starting is not detected!

### ISSUE THREAD

**Issue by DanielOX** [HookyQR/VSCodeBeautify#248]
For Example If if i beautify 

```html
   <li>
       <ul>
        <li>
</li>
        <li></li>

        <li> </li>
 
        <li></li>
                           <li></li>
        </ul>
    </li>

    <li>
      </li>
           <li>
                    </li>
 
</body>

</html>
```

VSCodeBeautify works like a charm 

but if with this code if VSCodeBeautify is applied it does not outputs the required
```html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Webpack</title>
</head>

<body>

  <div id="body-content"></div>

  <script src="./script 1.js"></script>
  <ul>
    <li> </li>
    <li>
       <ul>
        <li>
</li>
        <li></li>

        <li> </li>
 
        <li></li>
                           <li></li>
        </ul>
    </li>

    <li>
      <  /li>
           <  li>  // Notice the inline spaces of a tag starting and ending
                    <  /li>  // Notice the inline spaces of a tag starting and ending  
      < /ul> // Notice the inline spaces of a tag starting and ending
</body>

</html>
```
the output is beautified but the spaces which i mentioned doesn't goes off, if issue seems legit then kindly resolve this, else guide me if you have resolved or if i am missing something 

>  Thanks VSCodeBeautify Community For This Awesome Tool.

**Comment by HookyQR** [comment]
The tags with the leading space are invalid, that's why the space isn't being deleted. There's no way for beautify to know if you meant it to be that way, so it leaves it for you, assuming it's a text node.
