### ISSUE TITLE
Extra Spaces added before closing double quotes (RANDOM!)

### ISSUE THREAD

**Issue by slumbergod** [HookyQR/VSCodeBeautify#249]
* **Operating System (+Version)**:  Xubuntu 18.04
* **VS Code Version**:  1.24.1
* **beautify Version**:  1.3.2

I'm getting extra spaces added in before closing quotes in html. It's completely **random** so I can't replicate it but it has been an issue ever since I started using VS Code. Usually, this is triggered after saving a file with an error in the code. VS Code then seems to add in additional spaces as a result.

Since I cannot replicate it at will I don't expect it to be solved and clearly it isn't affecting anyone else enough to report it here. I am posting it here in case it is an issue that is known well enough to have a workaround. 

Adding this in my user settings does not resolve it: "editor.trimAutoWhitespace": true"

**Comment by HookyQR** [comment]
Try the new version.

**Comment by HookyQR** [comment]
No response for a few months now. Closing.
