### ISSUE TITLE
code is broken and uglified onSave

### ISSUE THREAD

**Issue by etinif** [HookyQR/VSCodeBeautify#25]
Why does my code get uglified and broken on auto save?

This:
```
return ( 
    <div>
      <SearchBar />
    </div>
);
```
becomes this:
```
return ( <
    div >
    <
    SearchBar / >
    <
    /div>
  );
```
```
{
    "beautify.onSave": true
}
```

Am I missing something in the settings? Or does it not work with jsx?

Manually formatting with Shift + Opt + F works fine though...

**Comment by HookyQR** [comment]
js-beautify doesn't work with `jsx`. See #23.
