### ISSUE TITLE
command 'HookyQR.beautifyFile' not found

### ISSUE THREAD

**Issue by Kaukov** [HookyQR/VSCodeBeautify#252]
* **Operating System (+Version)**:  ArchLinux (linux 4.17.5-1)
* **VS Code Version**: 1.25.1
* **beautify Version**: 1.3.2

**NOTE:** Please provide code snippets instead of screen shots. Your issue needs to be replicated, and we need the failing code (text) to do this.
Provide the settings you use: 
(VS Code workspace and user settings, .jsbeautifyrc, .editorconfig)
eg.:
VS Code:
```javascript
{
    "files.autoSave": "onFocusChange",
    "editor.tabSize": 2,
    "editor.renderWhitespace": "boundary",
    "editor.find.autoFindInSelection": true,
    "editor.mouseWheelZoom": true,
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
    "html.format.endWithNewline": true,
    "gitlens.advanced.messages": {
        "suppressShowKeyBindingsNotice": true
    },
    "workbench.iconTheme": "material-icon-theme",
    "sync.gist": "16cb3767c28738291aa2f06dc61fff66",
    "sync.host": "",
    "sync.pathPrefix": "",
    "sync.quietSync": false,
    "sync.askGistName": false,
    "sync.removeExtensions": true,
    "sync.syncExtensions": true,
    "sync.autoDownload": false,
    "sync.autoUpload": false,
    "sync.lastUpload": "",
    "sync.lastDownload": "2018-07-09T13:06:59.493Z",
    "sync.forceDownload": false,
    "window.menuBarVisibility": "toggle"
}

```
.jsbeautifyrc
**the file does not exist**
## Action performed
Format javascript file with `HookyQR.beautifyFile` command
```javascript
newGame = {player: {name: 'Player 1',score: 0,deaths: 10,achievements: [10, 20, 1030, 504, 201]},enemy: {name: 'Enemy 1',health: 1000,armor: 100,damageMultiplier: 3}}
```

## Expected results
Expected ... to ...
```javascript
newGame = {
  player: {
    name: 'Player 1',
    score: 0,
    deaths: 10,
    achievements: [
      10, 20, 1030, 504, 201
    ]
  },
  enemy: {
    name: 'Enemy 1',
    health: 1000,
    armor: 100,
    damageMultiplier: 3
  }
}
```

## Actual results
Details of what happened ...
```
Error> command 'HookyQR.beautifyFile' not found
```

This happens when trying to parse any JS file (I haven't tried with other formats, but I guess the result will be the same). This was working a few weeks ago

**Comment by alvsconcelos** [comment]
Same here :(

**Comment by HookyQR** [comment]
Seems like something is failing when loading the extension. This can happen when another extension fails to load. Try disabling other extensions first.

**Comment by HookyQR** [comment]
Closing due to lack of response.

**Comment by xiropot** [comment]
> Seems like something is failing when loading the extension. This can happen when another extension fails to load. Try disabling other extensions first.

In my case, the issue was a **conflict** of your plugin with **_[Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer&ssr=false)_**.

**Bracket Pair Colorizer 2** works as expected!

**Comment by deadlyengineer** [comment]
@tapandagr was right.
But is there any way to use both of them at the same time?
I love both extensions very much!!!
