### ISSUE TITLE
Significant whitespace introduced before an A tag

### ISSUE THREAD

**Issue by OpinionatedGeek** [HookyQR/VSCodeBeautify#255]
* **Operating System (+Version)**: 
MacOS High Sierra
* **VS Code Version**: 
1.25.1
* **beautify Version**: 
1.3.2

## Provide the settings you use: 
None - this happens with the default settings. (I do have VSCode's Format On Save enabled though.)

## Action performed
I have Format On Save enabled. I try to save an HTML file with the following:
```
(<a href="/link">text</a>)
```

## Expected results
I expected it to leave it alone, or reformat in a way that maintained the same appearance as the original HTML:
```
(<a href="/link">text</a>)
```

## Actual results
Beautify introduced significant whitespace after the opening bracket, before the link:
```
(
<a href="/link">text</a>)
```

I just want the text to appear as `(text)`, not the 'beautified' version with a space after the opening bracket: `( text)`.

I've tried:
```
"html.format.enable": false
```
Which didn't work.

I've tried disabling the VSCodeBeautify extension, which didn't work.

The only thing that worked (so far) is both:
```
"html.format.enable": false
```
*and* disabling the VSCodeBeautify extension.

I've tried wrapping the brackets in a SPAN tag and adding SPAN to content_unformatted in my workspace settings:
```
{
    "html.format.enable": false,
    "beautify.options": {
        "content_unformatted": [
            "pre",
            "span"
        ]
    },
}
```
But that had no effect - it just turns:
```
<span>(<a href="/link">text</a>)</span>
```
into:
```
<span>(
    <a href="/link">text</a>)</span>
```
Using `unformatted` instead of `content_unformatted` didn't make any difference here either. I don't think I really know how to make the required changes to the workspace settings file and I can't see any examples - can you point any out to me?

It all does seem to be an [issue with js-beautify](https://github.com/beautify-web/js-beautify/issues/1304), but until they fix that I'm at a loss how to get the HTML I want without disabling either Format On Save or disabling both VSCodeBeautify+VSCode's own beautify.

I've tried reading the settings for VSCodeBeautify and js-beautify, but I don't know which setting I need to change and I'm not clear how to change it in the workspace settings file (I'd rather avoid a .jsbeautifyrc file). Is there a simple incantation I can use to get the behaviour I want?

Many thanks,

Geoff

**Comment by bitwiseman** [comment]
@OpinionatedGeek This has been fixed in the latest release.

**Comment by OpinionatedGeek** [comment]
@bitwiseman Excellent - many thanks!
