### ISSUE TITLE
Unexpect `import(...)` to be formatted `import (...)`

### ISSUE THREAD

**Issue by fengxinming** [HookyQR/VSCodeBeautify#257]
# Description
In my codes I use `import(...)` dynamically import JS file with webpack, when I beautify my codes with `js-beautify`, I unexpect `import(...)` to be formatted `import (...)`, for example:

# Input
```

const report = () => import(/* webpackChunkName: "report" */ './report/report.vue');

```

# Expected Output
```

// nothing happens
const report = () => import(/* webpackChunkName: "report" */ './report/report.vue');

```

# Actual Output
```

const report = () =>
    import (/* webpackChunkName: "report" */ './report/report.vue');

```

# Steps to Reproduce

## Environment
OS: Macbook Air

## Settings
Vscode for example:
```json
{
    "editor.tabSize": 2,
    "editor.formatOnSave": true,
    "prettier.singleQuote": true,
    "git.autofetch": true,
    "files.insertFinalNewline": true
}
```

**Comment by HookyQR** [comment]
Disable `prettier` and let me know if you still have the same issue.

**Comment by guobing1993** [comment]
same problem，didn't install prettier

**Comment by fengxinming** [comment]
@HookyQR Yes, I still disabled prettier, js-beauty team has been fixed this bug, you may upgrade this plugin

**Comment by HookyQR** [comment]
OK. The js-beautify version that 'fixes' this is a release candidate. Until a full release is issued, the extension will stay as it is. The RC may break more than it fixes. 🤞we get a full release soon.

**Comment by HookyQR** [comment]
New version released.
