### ISSUE TITLE
Scss file containing @import of mixin gets weirdly formatted

### ISSUE THREAD

**Issue by ControlTheBit** [HookyQR/VSCodeBeautify#260]
* **Operating System (+Version)**: Mac OSX 10.13.6
* **VS Code Version**: 1.26.0
* **beautify Version**: 1.3.2

Provide the settings you use:
VS Code:
```javascript
{
    "editor.formatOnSave": true,
    "workbench.iconTheme": "vscode-icons"
}
```
.jsbeautifyrc
_No special settings, just the default extension settings_

## Action performed
Format .scss file with the following line somewhere on line 100 (not at the beginning of the file):
`@include box-shadow(0, 5px, 8px, rgba(0, 0, 0, 0.1));`

box-shadow is a mixin that is defined in a different file.

## Expected results
`@include box-shadow(0, 5px, 8px, rgba(0, 0, 0, 0.1));`

## Actual results
```
	@include box-shadow(0,
	5px,
	8px,
	rgba(0,
	0,
	0,
	0.1));
```

**Comment by HookyQR** [comment]
Fixed in new version.
