### ISSUE TITLE
How to update js-beautify version?

### ISSUE THREAD

**Issue by klmdb** [HookyQR/VSCodeBeautify#262]
js-beautify has recently been updated to fix a bunch of issues that have been mentioned here multiple times:

https://github.com/HookyQR/VSCodeBeautify/issues/194
https://github.com/HookyQR/VSCodeBeautify/issues/195
https://github.com/HookyQR/VSCodeBeautify/issues/244

How can have Beautify use the more recent js-beautify version (1.8.x) please?

**Comment by HookyQR** [comment]
New version published. Enjoy.
