### ISSUE TITLE
Formatting exponentially creates newlines after each self closing tag with 1.4.2 update

### ISSUE THREAD

**Issue by susedan** [HookyQR/VSCodeBeautify#263]
* **Operating System (+Version)**: MacOS 10.12.6
* **VS Code Version**:  1.26.1
* **beautify Version**: 1.4.2

VS Code settings:
```javascript
{
    
    "editor.formatOnSave": true,
    "editor.wordWrap": "on",
    "html.format.wrapLineLength": 0, // no wrap
    "html.format.unformatted": "a, abbr, acronym, b, bdo, big, br, button, cite, code, dfn, em, i, img, input, kbd, label, li, map, object, q, samp, select, small, span, strong, sub, sup, textarea, tt, var, script, p, head, style, /html",
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "html.autoClosingTags": false,
    "editor.renderControlCharacters": true,
    "editor.renderWhitespace": "none"
}
```
## Action performed
Format on save, no changes expected
```html
<div>
    <img src="example.gif" alt="">
</div>

<div>
    <a><img src="example.gif" alt=""></a>
</div>_
```

## Actual results
All self-closing elements have a new line added after the element. 
```html
<div>
    <img src="example.gif" alt="">

</div>

<div>
    <a><img src="example.gif" alt=""></a>
</div>_
```

## Additional notes
- This began immediately after the 1.4.2 update.
- Self-closing elements contained within another non-closing element (e.g. within second div content) the new line is not added.
- Every save results in additional lines. The second save adds two new lines. Third save adds 4, and so on.
- If the plugin is disabled, the behaviour stops.
- If I comment out "html.format.unformatted" in settings this behavior stops.

**Comment by HookyQR** [comment]
I've set up an environment with exactly your settings, and I can't replicate the issue. There have been cases where multiple formatters interact poorly with each other. Perhaps try disabling any other extensions which may providing a formatter (such as Prettier) and enabling beautify again. Sorry you're having this issue.

**Comment by AmandaFoster** [comment]
This is a upstream issue with the beautifier. It should be resolved now with this [issue](https://github.com/beautify-web/js-beautify/issues/1534).

**Comment by HookyQR** [comment]
Try latest version? Have rolled in new upstream.

**Comment by susedan** [comment]
That did the trick! Thanks
