### ISSUE TITLE
Indentation is forced to 4 tabs if `"brace_style": "collapse,preserve-inline"` is used

### ISSUE THREAD

**Issue by rap2hpoutre** [HookyQR/VSCodeBeautify#264]
* **Operating System (+Version)**: MacOS (current)
* **VS Code Version**: 1.26.1
* **beautify Version**: 1.4.2

**VS code config**
```javascript
"beautify.config": { 
    "brace_style": "collapse,preserve-inline",
},
```

## Action performed

Format javascript with `alt`+`shift` + `f`

## Expected results
It should indent with two spaces (configured in VS code with: `"[javascript]": { "editor.tabSize": 2 }`
) like this :
```
db.things.find({}).forEach(actor => {
  // Do something
})
```

## Actual results
It indents with 4 spaces (no clue why)

```
db.things.find({}).forEach(actor => {
    // Do something
})
```

The weird thing is if I remove this:

```javascript
"beautify.config": { 
    "brace_style": "collapse,preserve-inline",
},
```

It works, the actual result **is** the expected result.

**Comment by HookyQR** [comment]
It's forced to 4 because you're now using a `.jsbeautifyrc` setting effectively. The default is 4. If you wan't to not use that, add the `indent_size: 2` setting.

**Comment by rap2hpoutre** [comment]
thanks!
