### ISSUE TITLE
js-beautify `await` causing unnecessary indents (upstream issue)

### ISSUE THREAD

**Issue by qguv** [HookyQR/VSCodeBeautify#267]
There's [an issue upstream](https://github.com/beautify-web/js-beautify/issues/1517) with the new version of js-beautify that was just pulled into version 1.4.3 of this extension. Code to reproduce the problem is provided in the linked issue description.

In the meantime, users can downgrade to an older version of `js-beautify` which doesn't have this issue by disabling the auto-update feature in VS Code and installing [this VSIX](https://hookyqr.gallery.vsassets.io/_apis/public/gallery/publisher/hookyqr/extension/beautify/1.3.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage) manually.

**Comment by HookyQR** [comment]
Thanks @qguv, I'll keep an eye on the upstream for a fix. This may be the same issue with alignment of the function body from a class method with a computed property name per #258.

**Comment by bitwiseman** [comment]
Fixed in 1.8.3-rc2.

**Comment by HookyQR** [comment]
Thanks @bitwiseman. Have stepped upstream to 1.8.4.
