### ISSUE TITLE
[Feature request] Add support to beautify Typescript code

### ISSUE THREAD

**Issue by elebetsamer** [HookyQR/VSCodeBeautify#27]
Seeing as how Visual Studio Code is such a great Typescript editor, it'd be great to be able to beautify Typescript files.

**Comment by Jakobud** [comment]
I just add "ts" to my Beautify settings and it seems to work fine:

```
"beautify.JSfiles": [
        "js",
        "json",
        "jsbeautifyrc",
        "jshintrc",
        "ts"
    ]
```

**Comment by HookyQR** [comment]
It works *ok* for Typescript. If you get into using some of the funkier structural syntax of TS, you may get caught out though. Since `js-beautify` doesn't state support for Typescript, I won't hard code it as a capability. @Jakobud's setting is the right way to do it FYI.
