### ISSUE TITLE
can not support less format，wish css、less、sass Single line formatting 

### ISSUE THREAD

**Issue by ayin86** [HookyQR/VSCodeBeautify#271]
can not support less format，wish css、less、sass Single line formatting 
![image](https://user-images.githubusercontent.com/25238537/45935561-2427cb00-bfdf-11e8-9390-621524c66641.png)

For me (and many developpers), it's far easier to read and to work on css formatted that way.

**Comment by HookyQR** [comment]
Not supported by the upstream formatter: https://github.com/beautify-web/js-beautify
