### ISSUE TITLE
CSS formatting, can I  disable extra new line before last comment?

### ISSUE THREAD

**Issue by Gennady-G** [HookyQR/VSCodeBeautify#278]
* **Operating System (+Version) Win Server 2012 R2**: 
* **VS Code Version 1.29.1**: 
* **beautify Version 1.4.7**: 

**NOTE:** Please provide code snippets instead of screen shots. Your issue needs to be replicated, and we need the failing code (text) to do this.

Provide the settings you use: 
(VS Code workspace and user settings, .jsbeautifyrc, .editorconfig)
eg.:
Workspace Settings:
```{
    "git.ignoreMissingGitWarning": true,
    "window.zoomLevel": -1,
    "workbench.sideBar.location": "right",
    "files.autoSave": "off",
    "editor.cursorStyle": "underline",
    "liveServer.settings.donotShowInfoMsg": true,
    "liveServer.settings.donotVerifyTags": true,
    "html.format.contentUnformatted": "pre,code,textarea,li",  
    "emmet.preferences": { "format.forceIndentationForTags": [ "div" ] },
    "liveServer.settings.port": 5558
}
```
## Action performed
Format javascript file with `HookyQR.beautifyFile` command

```
@media screen and (min-width: 992px) and (max-width: 1200px) {
  // .. 
}
/* Media 992-1200px ended */   /*  <--- here is comment, right after code */

```
## Expected results
Expected ... to ...
```
@media screen and (min-width: 992px) and (max-width: 1200px) {
  // .. 
}
/* Media 992-1200px ended */   /*  <--- I want comment here, all to be the same */
```

## Actual results
```
Details of what happened ...
@media screen and (min-width: 992px) and (max-width: 1200px) {
  // ..
}
/* <---------------       but it adds new line here   */
/* Media 992-1200px ended */  /*  Can I  disable this extra new line?..   */
```

**Comment by HookyQR** [comment]
Add `"newline_between_rules": false` to your `.jsbeautifyrc` file, or `beautify.config` VSCode settings.

**Comment by Gennady-G** [comment]
I want this global. Where is this setting, "html.format.newline_between_rules" or what?..

![2019-02-01_101227](https://user-images.githubusercontent.com/5569346/52105885-f0525700-2609-11e9-9e5f-f277c56e0865.png)

**Comment by HookyQR** [comment]
Nope, it's a `js-beautify` setting, so to put it in your VS Code settings use:
```json
"beautify.config": { "newline_between_rules": false }
```

**Comment by Gennady-G** [comment]
Wow, perfect!
Thank You much, @HookyQR! :-)
