### ISSUE TITLE
Space after colon

### ISSUE THREAD

**Issue by juninhodeluca** [HookyQR/VSCodeBeautify#280]
I wonder if theres some way to add something like "space_after_colon": true, to CSS, JS and JSON and maybe style HTML attribute, just like space_in_paren works

CSS BEFORE:
```
.row {
    width:200px
}

```
CSS AFTER:
```
.row {
    width: 200px
}
```

JSON/JS BEFORE:
```
let obj = {
    settings:{
         width:100,
         height:300
    }
}
```

JSON/JS AFTER:
```
let obj = {
    settings: {
         width: 100,
         height: 300
    }
}
```

Suggestion (if "wrap_attribtes": "force-aligned")
HTML Style attr BEFORE:
`<div id="myDiv" class="myClass" style="width:300px;height:200px">Hello</div>`

HTML Style attr AFTER:
```
<div id="myDiv" 
     class="myClass" 
     style="width: 300px;
            height: 200px">
    Hello
</div>
```

* **Operating System (+Version)**:  Windows 10
* **VS Code Version**:  1.30
* **beautify Version**:  1.4.7

**Comment by HookyQR** [comment]
The support for options would need to be provided in https://github.com/beautify-web/js-beautify

This extension wraps that project into a VS Code extension.

**Comment by HookyQR** [comment]
Other than the style attribute version, the space gets inserted always, so there would only be a need for this if you wanted it not to happen this way.
