### ISSUE TITLE
PHP blade syntax produces error after format "->" becomes "- >"

### ISSUE THREAD

**Issue by amitshahc** [HookyQR/VSCodeBeautify#282]
* **Operating System (+Version)**: Windows 10
* **VS Code Version**: 1.30.1
* **beautify Version**: 1.4.7

**NOTE:** Please provide code snippets instead of screen shots. Your issue needs to be replicated, and we need the failing code (text) to do this.

Provide the settings you use: 
(VS Code workspace and user settings, .jsbeautifyrc, .editorconfig)
eg.:
VS Code:
```javascript
{
	"editor.formatOnSave": true
}
```
.jsbeautifyrc
```javascript
{
	"max_preserve_newlines": 2,
	"preserve_newlines": true,
	"end_with_newline": true,
	"brace_style": "collapse-preserve-inline",
}
```
## Action performed
Format html file with `HookyQR.beautifyFile` command 
F1 + Beautify file + HTML

## Expected results
Expected ... to ...
@foreach($employee -> services as $service) // Before: the blade php code in html template

## Actual results
Details of what happened ...
@foreach($employee - > services as $service) // After: Blade php syntax error..

**Comment by mohnjatthews** [comment]
I believe there's an extension you can get for Blade files. Take a look at this [StackOverflow answer](https://stackoverflow.com/a/49184672/2878626). It looks like you have to install [Laravel Blade Snippets](https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade).

**Comment by HookyQR** [comment]
Try with the latest version. Seems to workout fine now. ;)

**Comment by HookyQR** [comment]
WOMM and no response from Issue opener.
