### ISSUE TITLE
"html.format.extraLiners": "", doesn't work

### ISSUE THREAD

**Issue by elgs** [HookyQR/VSCodeBeautify#284]
* **Operating System (+Version)**: 
Linux archlinux 4.20.0-arch1-1-ARCH #1 SMP PREEMPT Mon Dec 24 03:00:40 UTC 2018 x86_64 GNU/Linux

* **VS Code Version**: 
1.30.1

* **beautify Version**: 
1.4.7

**NOTE:** Please provide code snippets instead of screen shots. Your issue needs to be replicated, and we need the failing code (text) to do this.

Provide the settings you use: 
(VS Code workspace and user settings, .jsbeautifyrc, .editorconfig)
eg.:
VS Code:
```javascript
{
	"html.format.extraLiners": "",
}
```
.jsbeautifyrc
none

## Action performed
Format javascript file with `HookyQR.beautifyFile` command to format:
```html
<!DOCTYPE html>
<html><head></head><body></body></html>
```

## Expected results
```html
<!DOCTYPE html>
<html>
<head></head>
<body></body>
</html>
```
## Actual results
```html
<!DOCTYPE html>
<html>

<head></head>

<body></body>

</html>
```

**Comment by elgs** [comment]
It seems this setting is completely ignored, even if I pretend to replace to value to `div`, it doesn't add new line between `div`s in the html.

`"html.format.extraLiners": "div",`

**Comment by HookyQR** [comment]
Turns out there's a typo in the options converter. Working on it now.

**Comment by ghost** [comment]
Hi,
I have the same issue as well. 
Beautify version: 1.4.10: 20 Mar 2019
VS version: January 2019 (version 1.31)

Comment before <body> tag is now an extra line above it. It was not before. No extra VS settings.
