### ISSUE TITLE
HTML head and body not indented by default

### ISSUE THREAD

**Issue by DanJ210** [HookyQR/VSCodeBeautify#286]
* **Operating System (+Version)**: 1709
* **VS Code Version**: 1.30.2
* **beautify Version**: 1.4.7

> Maybe I'm unsure of the proper HTML indent formatting but I thought the hierarchical structure standard was to indent between the `<html>` tags.

Provide the settings you use: 
(VS Code workspace and user settings, .jsbeautifyrc, .editorconfig)
eg.:
VS Code:
```javascript
{
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
    "editor.formatOnType": false,
}
```

## Action performed
Formatting an HTML file that's indented properly like below on save.
```html
<!DOCTYPE html>
<html>
      <head>
        <title>TypeScript Greeter</title>
      </head>

      <body>
        <script src="greeter.js"></script>
      </body>
</html>
```

## Expected results
I'm expecting that the formatting stays the same or adds a new line between respective tags.
```html
<!DOCTYPE html>
<html>

  <head>
    <title>TypeScript Greeter</title>
  </head>

  <body>
    <script src="greeter.js"></script>
  </body>

</html>
```

## Actual results
Everything gets pushed to the left except `<title>` and `<script>`.
```html
<!DOCTYPE html>
<html>

<head>
  <title>TypeScript Greeter</title>
</head>

<body>
  <script src="greeter.js"></script>
</body>

</html>
```

**Comment by HookyQR** [comment]
by default `head` and `body` are not indented. You can change this by setting:
```json
"indent_inner_html": false
```
In either your `.jsbeautifyrc` file, or as an object under `"beautify.config"` in your VS Code settings.
