### ISSUE TITLE
How to set "inline" option for HTML

### ISSUE THREAD

**Issue by f3oall** [HookyQR/VSCodeBeautify#287]
* Ubuntu 16.04: 
* 1.30.2: 
* 1.4.7: 

Seems like there is no `html.format.inline` option to  configure. 
It was added not long ago to JSBeautify: [merge request](https://github.com/beautify-web/js-beautify/pull/1407/commits/0e9ad61dba19722f0c4f2b5aabe41b8f10bc884e#diff-e697c50f16270c0b96dcdf2c3cbd79d7R242)

**Comment by HookyQR** [comment]
the `html.format` options belong to VS Code. For js-beautify options, use
```json
"beautify.config": {
  "html": { "inline": ["span", "a", "whateva"] },
}
```
