### ISSUE TITLE
Broken intellisense for .jsbeautifyrc file

### ISSUE THREAD

**Issue by tanathos** [HookyQR/VSCodeBeautify#288]
* Windows 10: 
* VSCode 1.30.2: 
* beautify 1.4.7: 

.jsbeautifyrc
```javascript
{
	"preserve_newlines": true,
	"wrap_attributes": "preserve-aligned", // line incriminated
	"indent_inner_html": false,
	"extra_liners": []
}
```
## Action performed
Just configuring the .jsbeautifyrc 

## Expected results
The intellisense should recognize all the supplied values, because it is actually working 😁

## Actual results
I'm getting an intellisense error "Value is not accepted. Valid values: "auto", "force", "force-aligned", "force-expand-multiline", "align-multiple"." for the "wrap_attributes" property.
As I said before, the configuration IS working, the only problem is that the intellisense does not recognize the "preserve-aligned" value, I just found out it was existing reading the CLI options of js-beautify project.

**Comment by HookyQR** [comment]
this settings are not valid for the release version of js-beautify. As soon as they're out of beta, they'll get added in. A PR has been submitted to include them already. 👍
