### ISSUE TITLE
Cannot disable JavaScript formatting with beautify.language

### ISSUE THREAD

**Issue by CreativeTechGuy** [HookyQR/VSCodeBeautify#289]
* **Operating System (+Version)**: Windows 10.0.17763
* **VS Code Version**: 1.31.0
* **beautify Version**: 1.4.8

**NOTE:** Please provide code snippets instead of screen shots. Your issue needs to be replicated, and we need the failing code (text) to do this.

Code Snippet:
```javascript
function example(user) {
    return { error: false, user: user };
}
```

VS Code Settings:
```json
"beautify.language": {
    "html": [
        "htm",
        "html"
    ],
    "css": [],
    "js": {}
}
// -- OR --
"beautify.language": {
    "html": [
        "htm",
        "html"
    ]
}
```
## Action performed
Right click on JavaScript file and click "Format Document".

## Expected results
Expected to do nothing since the `beautify.language` was disabled for js.

## Actual results
Beautify did format the file to become the following:
```javascript
function example(user) {
    return {
        error: false,
        user: user
    };
}
```

## Additional Information
I am trying to use Beautify for HTML formatting and Prettier for JS/CSS formatting. This seemed to be working up until the latest 1.31.0 VS Code update when this started to happen. The testing above happened when Prettier was disabled for a clean test. When I am using both, they seem to fight over the file and have inconsistent behavior (sometimes it'll format with Prettier, sometimes Beautify, sometimes nothing). It seems like I've narrowed it down to Beautify not respecting the `beautify.language` setting which is why I am posting this issue here.

**Comment by HookyQR** [comment]
Try `"js": null`. Let me know how that goes.

**Comment by CreativeTechGuy** [comment]
Very weird. That does seem to work. The thing I'll note now is that the `settings.json` file will give a warning about that null value.

```
Incorrect type. Expected one of object, array.
Array of language types, or an object containing types, extensions and filenames to associate
```

So far it seems to be solved, but this is a fairly unintuitive solution. If this is the intended solution it should be documented somewhere visible.

Thanks for the attention to this issue!

**Comment by HookyQR** [comment]
It's not a solution. It's a workaround. Will fix the base issue. 👍

**Comment by CreativeTechGuy** [comment]
Oh interesting. I'll be very interested to see the fix for this.

Thanks again!

**Comment by HookyQR** [comment]
Seem it can only be 'unset' with either 'null' or an empty array. Using an empty object allows VS Code to merge in the defaults still, so that can't be fixed.
