### ISSUE TITLE
Beautify removes new lines between LESS rules

### ISSUE THREAD

**Issue by herrherrmann** [HookyQR/VSCodeBeautify#29]
Hey there,

although I defined `"newline_between_rules": true` in my .jsbeautifyrc, the Beautify extension removes those new lines and thus would transform this
```
.state:hover {
	.btn-variant();

	&.state-lead {
		.btn-variant(warning);
	}
	
	&.state-proposed {
		.btn-variant(info);
	}
}
```
into this:
```
.state:hover {
	.btn-variant();
	&.state-lead {
		.btn-variant(warning);
	}
	&.state-proposed {
		.btn-variant(info);
	}
}
```
… which is not what I wanted, of course. Did I configure something wrong or is this a bug?

Here's my complete `.jsbeautifyrc`:
```
{
	"end_with_newline": true,
	"indent_level": 0,
	"indent_with_tabs": true,
	"max_preserve_newlines": 2,
	"preserve_newlines": true,
	"wrap_line_length": 0,
	"js": {
		"brace_style": "collapse",
		"break_chained_methods": false,
		"indent_with_tabs": true,
		"jslint_happy": false,
		"jslint_happy_align_switch_case": false,
		"space_after_anon_function": false,
		"space_before_conditional": true,
		"space_in_empty_paren": false,
		"space_in_paren": false
	},
	"html": {
		"brace_style": "collapse",
		"wrap_attributes_indent_size": 4,
		"unformatted": ["a", "sub", "sup", "b", "i", "u"]
	},
	"css": {
		"convert_quotes": "single",
		"newline_between_rules": true,
		"selector_separator_newline": true,
		"space_around_selector_separator": true
	}
}
```

**Comment by Jakobud** [comment]
It does this for Ses as well. I would love to know how to fix this problem. It's really really annoying. I put white space in my code for a reason and this strips it out.

**Comment by HookyQR** [comment]
I think that the back end process only preserves new lines between top level rules. Will check this tonight.

**Comment by HookyQR** [comment]
`max_preserve_newlines` and `preserve_newlines` are only valid for **js** and **html** unfortunately.

**Comment by Jakobud** [comment]
https://github.com/beautify-web/js-beautify/issues/657

Confirmed this is a JS Beautify problem.

**Comment by danieloprado** [comment]
+1
