### ISSUE TITLE
beautify  removes parentheses around code

### ISSUE THREAD

**Issue by Zamio77** [HookyQR/VSCodeBeautify#293]
*Before Beautify
this.height = (Math.random() * 5 )+ 3;
  this.speed = Math.random() * 6 + 3;

*After Beautify
this.height = Math.random() * 5 + 3;
  this.speed = Math.random() * 6 + 3;

Beautify does not allow me to save code with parentheses not tied to a function. The this.height needs parentheses for the function to process the way I need it to. However, whenever I try to save the file with beautify code active, it will remove the parentheses around that line as there isn't a function tied to them.

The trick I found toe keep the parentheses I need is the below

this.y = 1 * (Math.random() * 80) - 80;
  this.height = 1 * (Math.random() * 5) + 3;

now when saving, the parentheses remain.

**Comment by HookyQR** [comment]
What other extensions do you have installed? Beautify shouldn't remove any characters from your code. Try calling the "Beautify file" command and see if the same happens. (My guess is it won't)

**Comment by HookyQR** [comment]
Closing as can't reproduce + no response.
