### ISSUE TITLE
Code in ASP, aspas ABRE!!!!

### ISSUE THREAD

**Issue by marmmc** [HookyQR/VSCodeBeautify#295]
Hello, DEVELOPERS!

I use VSCODE, however, when using the ASP code with BEAUTIFY, it simply saves it, it OPENS the quotes, type:

<% = strVAR ("id")%> the normal would be like this, but when saving, it opens the quotation marks, generating error, thus:

<% = strVAR ("id")%>

Is there any solution to implement in the beaufity configuration itself to get around this problem?

**Comment by HookyQR** [comment]
I'm not sure what you're asking for. The two tags you have provided are the same. Please provide a code block example _before_ formatting, _after_ formatting, and what the _expected_ result after formatting should be.

**Comment by marmmc** [comment]
ok, vamos lá...
Quando utilizo o ASP no HTML, utilizo assim: <% = strVAR ("id")%> isso é o correto para a tag.
Mas quando utilizo o BEAUTIFY no vscode do HOOKYQR, ele simplesmente fica assim:

<% = strVAR ("   id")%>

Ele separa entre as aspas, não deveria, tem como acertar isso.
Senão cada vez que utilizo, tenho que reformatar o código e juntar novamente o ID???

**Comment by HookyQR** [comment]
Do you have any other extensions enabled? Try disabling all extensions, then enable beautify and try again. I can't replicate the problem.

**Comment by marmmc** [comment]
olá.
usando este bloco de código agora, sem extensão nenhuma inclusa, apenas ASP e BEAUTIFY, não encontro erro nenhum.

`<div class="col-lg-12 col-md-12 col-sm-4 col-xs-12 pull-left">
                                <%
                                SET strEmails = conexao.execute("SELECT * FROM setores ORDER BY id ASC")
                                %>
                                <label class="control-label" for="campo_setor">Setor</label>
                                <select id="campo_setor" name="campo_setor" autocomplete="" class="form-control" placeholder="">
                                    <option value="">Selecione um Setor</option>
                                    <option value=""></option>
                                    <%
                                    DO WHILE NOT strEmails.EOF                      
                                        Response.Write "<option value=""" & strEmails("id") & """>"& strEmails("setor") &"</option>"
                                        strEmails.MoveNext
                                            loop
                                    SET strEmails = Nothing
                                    %>
                                </select>
                            </div>`

Isso, tanto selecionando SELECT LANGUAGE no rodapé, como HTML e ASP.
Agora, com todas as extensões ativadas, o mesmo também continua exato agora....

Apenas modifiquei uma extensão que tinha instalado de ASP, e troquei por outra.
Com este funcionou: https://github.com/bradrobertson/sublime-packages/tree/master/ASP 

No demais, então, te agradeço.
A extensão estava ótima, talvez foi mesmo fazer estes ajustes em cima, para resolver e ver onde estava o problema da formatação.

Obrigado amigo.
Grato ....

**Comment by HookyQR** [comment]
Good luck.

**Comment by marmmc** [comment]
Hello...
I have a situation that I could not find the right way to adjust, I have the following situation using its component VSCODE, BEAUTIFY - HOOKIE.

I have a JS script, using ajax, for bootpag paging, where it needs to redeem within a variable the value of PHP, ASP, or etc ...

But when he saves the file, he keeps separating the code ....

how can i fix it, is there any setting i can do so that this doesn't happen in the script ....

Follow example SCRIPT:

$ (document) .ready (function () {
$ (". bootpag-content"). load ("form / form_ajax_noticias.asp");
$ (". bootpag-pagination"). bootpag ({
total: <% = total_pages%>,

when saving the script, it always separates the ASP tag, always like this ...

**<% = total_pages%>**
so the script does not run ..

I also tried like this:
create a variable, like

var tagASP = '**<% = total_pages%>**';
this works, however, in bootpag, it cannot contain single quotes, which doesn't work either ...

the right thing would have to avoid when saving using beauty formatting, not separating the asp tags ....

I ask, can you configure not to perform asp formatting on this, or just that. ????
