### ISSUE TITLE
How does vetur relate to VSCodeBeautify

### ISSUE THREAD

**Issue by cooper1x** [HookyQR/VSCodeBeautify#296]
* **Operating System (+Version)**: Windows 10 x64 1809
* **VS Code Version**: 1.31.1
* **beautify Version**: 1.4.9

**NOTE:** Please provide code snippets instead of screen shots. Your issue needs to be replicated, and we need the failing code (text) to do this.

Provide the settings you use: 
(VS Code workspace and user settings, .jsbeautifyrc, .editorconfig)
eg.:
VS Code:
```javascript
// A path to a file, or an object containing the configuration options for js-beautify. If the .jsbeautifyrc file exists in project root, it overrides this configuration.
  "beautify.config": null,

  // List of paths to ignore when using VS Code format command, including format on save. Uses glob pattern matching.
  "beautify.ignore": [],

  // Link file types to the beautifier type
  "beautify.language": {
    "js": {
      "type": [
        "javascript",
        "json",
        "jsonc"
      ],
      "filename": [
        ".jshintrc",
        ".jsbeautifyrc"
      ]
    },
    "css": [
      "css",
      "less",
      "scss"
    ],
    "html": [
      "htm",
      "html"
    ]
  }

```
```
"vetur.format.defaultFormatter.html": "js-beautify-html",
  "vetur.format.defaultFormatterOptions": {
    "js-beautify-html": {
      "wrap_attributes": "auto"
    },
    "prettyhtml": {
      "printWidth": 100,
      "singleQuote": false,
      "wrapAttributes": false,
      "sortAttributes": false
    }
  },
```

## Action performed
Press the shortcut key to format automatically

## Expected results
`.vue` file was formatted smoothly.

## Actual results
![image](https://user-images.githubusercontent.com/9080789/53693237-8da2d580-3dd8-11e9-94b9-2411a195989b.png)

**Comment by HookyQR** [comment]
The vetur extension has nothing to do with the beautify extension. It looks like it uses the same backend as we do here. To use beautify as your formatter for `vue` add `"vue"`to the `"html"`array under the `"beautify.language"` option. This will not pick up the settings in the `"vetur.format.defaultFormatterOptions"` as they're unrelated.

**Comment by HookyQR** [comment]
This question is void with the formatter selector capability was introduced into VS Code.
