### ISSUE TITLE
How to config "wrap each JSX attribute in a new single line"?

### ISSUE THREAD

**Issue by imageslr** [HookyQR/VSCodeBeautify#298]
Hello! I'm using Beautify in VS Code now. I want to format my JSX code as followling:

```JSX
// From...
<SearchBar value={this.state.value} onChange={this.onChange.bind(this)} focus onConfirm={this.onSearch.bind(this)} />

// To...
<SearchBar
  value={this.state.value}
  onChange={this.onChange.bind(this)}
  focus
  onConfirm={this.onSearch.bind(this)}
/>
```
When I using Prettier, it will format my code as shown above. Could you please tell me how to change Beautify config? Thanks for helping me!

**Comment by HookyQR** [comment]
Beautify doesn't format html(ish) code embedded in javascript. Sorry.

**Comment by HookyQR** [comment]
Also, note that this code creates two new methods every time it is run (which is likely every time it is rendered). You should bind your callbacks in your constructor to avoid this.

See the paragraph directly before this anchor: https://reactjs.org/docs/handling-events.html#passing-arguments-to-event-handlers

**Comment by imageslr** [comment]
Thanks for your advice! I have never noticed that. That's helpful. 😄
