### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by notte** [HookyQR/VSCodeBeautify#305]
- Issue Type: `Performance`
- Extension Name: `beautify`
- Extension Version: `1.4.11`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/YAO/HookyQR.beautify-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by HookyQR** [comment]
:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/YAO/HookyQR.beautify-unresponsive.cpuprofile.txt`

**Comment by HookyQR** [comment]
Duplicate of #300
