### ISSUE TITLE
Preserve destructuring in javascript as single line statement

### ISSUE THREAD

**Issue by mclusky** [HookyQR/VSCodeBeautify#306]
Hi,

Is there an option to preserve object destructuring on one line in javascript?
When you save, everything is indented.

Chris

**Comment by HookyQR** [comment]
Using `"brace_style": "collapse,preserve-inline"` in either your `.jsbeautifyrc` or inside the `"beautify.config": {` `}` setting in VS Code.

**Comment by mclusky** [comment]
Perfect, thank you.
