### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by preet10** [HookyQR/VSCodeBeautify#309]
- Issue Type: `Performance`
- Extension Name: `beautify`
- Extension Version: `1.5.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Puneet\HookyQR.beautify-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by HookyQR** [comment]
Still waiting for someone to supply the file.
:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Puneet\HookyQR.beautify-unresponsive.cpuprofile.txt`

Duplicate of #300
