### ISSUE TITLE
Ident span, h1, small html tags too

### ISSUE THREAD

**Issue by calebeaires** [HookyQR/VSCodeBeautify#31]
How can I configure it to don on those tags as it is done on div and others.
```
        <span>
         <span>
          <span>This is a </span>
         </span>
        </span>
```

**Comment by HookyQR** [comment]
There is a large list of tags that are not formatted by default. `span` is one of them. Add the `"unformatted"` key to your `.jsbeautifyrc` file, and it will automatically put all of those tags in the array for you - thus matching the default setup. Just remove the ones you want to format from the list.
