### ISSUE TITLE
[feature request]replace the builtin format command 

### ISSUE THREAD

**Issue by zzzgit** [HookyQR/VSCodeBeautify#320]
Why replace the built-in format command with Beautify?

I don't want to type another command or define a new shortcut.

What I mean is just like [this plugin](https://github.com/prettier/prettier-vscode).

![image](https://user-images.githubusercontent.com/1060733/59480075-c6e7e880-8e91-11e9-9130-a571ea954720.png)

**Comment by HookyQR** [comment]
It already does this. You just have to set vs code to use beautify as your default formatter. If you already have one set when you install it, it probably won't ask, so you'll have to remove the setting for the default formatter, then, format again and it should ask which one you want as your default.
