### ISSUE TITLE
Keyboard shortcut.

### ISSUE THREAD

**Issue by mrkongo** [HookyQR/VSCodeBeautify#34]
Why I haven't any keyboard shortcut (Alt+Shift+F doesn't work) in my VSCode?

**Comment by 0915240** [comment]
i haven't found it either.

you can use like this:
```
F1 -> beautify
```

**Comment by HookyQR** [comment]
You can add your own key bindings pretty easily. I use Cmd+B myself, but that conflicts with VS Code built its, so I didn't include it.

Go to *Preferences > Keyboard Shortcuts* and add an element to the array like this: 
```
{
  "key": "cmd+b",
  "command": "HookyQR.beautify",
  "when": "editorFocus"
}
```

**Comment by HookyQR** [comment]
The default formatting shortcut **Shift+Alt+F** will now work for full file formatting. It wasn't possible before because VS Code refused to relinquish the shorcut.
