### ISSUE TITLE
Update to actual js-beautify version?

### ISSUE THREAD

**Issue by HanabishiRecca** [HookyQR/VSCodeBeautify#346]
Last update of the extension was already a year ago. Why you not updating it?

**Comment by laggingreflex** [comment]
In the meantime you can update manually by running `npm update` in the extension directory: `%USERPROFILE%\.vscode\extensions\hookyqr.beautify-1.5.0`

I think VSCode should have an option to do this automatically or let the user do it easily. 

Latest js-beautify version is well within the semver range specified (^1.9.0 -> 1.11.0)

**Comment by moscoso** [comment]
Thanks @laggingreflex  i had to manually update the version thanks to you.
