### ISSUE TITLE
Can't only beautify the selected code

### ISSUE THREAD

**Issue by silenaker** [HookyQR/VSCodeBeautify#35]
can't only beautify the selected code like atom, instead it will beautify the whole file

**Comment by HookyQR** [comment]
If you like the way Atom works, you're welcome to keep using it ;)

**Comment by silenaker** [comment]
I was so sad I did not notice that the built-in format code command could do this. I'm new to vscode, the formatting configuration style is great the extension provide, hope this extension could do so.

**Comment by HookyQR** [comment]
It can for some types, but the VS Code engine doesn't let me take over the range formatting for Javascript or JSON, sorry. The code to make it happen is actually in the extension, it just gets ignored.
