### ISSUE TITLE
Can't Correct  format .ejs <% %>

### ISSUE THREAD

**Issue by SvenZhao** [HookyQR/VSCodeBeautify#36]
Can't Correct  format .ejs <% %>

**Comment by HookyQR** [comment]
Can you please provide more details, and/or an example.

**Comment by SvenZhao** [comment]
@HookyQR 
format ejs before
![1](https://cloud.githubusercontent.com/assets/11209750/17877597/05223306-6917-11e6-9f21-28e7e5187bb4.png)
format ejs after
![2](https://cloud.githubusercontent.com/assets/11209750/17877625/36797e00-6917-11e6-9618-6533a24d07cb.png)

<%%>There will be spaces in the back.

<%%>Cannot align


but {{}} is ok
![3](https://cloud.githubusercontent.com/assets/11209750/17877686/abcba796-6917-11e6-903e-b94687b5c60c.png)

**Comment by HookyQR** [comment]
Would have been nice if I had a text block I could copy, but thanks for your examples. I've replicated the problem. Unfortunately js-beautify considers `<%` to be an *underscore.js* comment, but still decides to indent it after that. It might be worth submitting an issue to the [js-beautify](https://github.com/beautify-web/js-beautify) project.

**Comment by SvenZhao** [comment]
@HookyQR  thinks
