### ISSUE TITLE
Using js formatting for typescript

### ISSUE THREAD

**Issue by AkashGutha** [HookyQR/VSCodeBeautify#38]
I was testing js beautify on typescript files .
the results were pretty good.

in the pr #37 i solved the issue of manually selecting js for formatting every time.

without this ,it would always popup a selector menu to select from js , html & css.

**Comment by HookyQR** [comment]
Hi @AkashGutha, because js-beautify isn't strictly compatible with `typescript`, I won't be making the code change. You can set the extension up to always run the `js` version for you `typescript` files by adding the following to your user settings:
```javascript
"beautify.JSfiles": [
    "js",
    "json",
    "jsbeautifyrc",
    "jshintrc",
    "ts"
    ]
```
This will stop the selector menu from popping up.

**Comment by AkashGutha** [comment]
thatnks !
@HookyQR are there any plans to include support for typescript in near future ?

**Comment by HookyQR** [comment]
The work is really done by [js-beautify](http://jsbeautifier.org/), and I'm not working on adding any extra formatting systems at the moment.

**Comment by AkashGutha** [comment]
okk. thanks !

**Comment by tomdavidson** [comment]
the only snag i have run into with ts is with optional parameters:
 `Body?: string;` becomes `Body ? : string;`   

How do we override this behavior for ts files?

**Comment by endquote** [comment]
It looks like the above setting is deprecated, but this seems to work:

```
  "beautify.language": {
    "js": {
      "type": ["javascript", "json"],
      "filename": [".jshintrc", ".jsbeautify"],
      "ext": ["js", "json", "ts"]
    }
  },
```

Agreed that "proper" TS support from js-beautify would be nice... surprised MS isn't providing it.
