### ISSUE TITLE
Unreadable content after beautify when using Vash (expressjs view engine)

### ISSUE THREAD

**Issue by dehghani-mehdi** [HookyQR/VSCodeBeautify#39]
Hi, thanks for your extension. it's really useful.

But there is a problem, I'm using [Vash](https://github.com/kirbysayshi/vash) and I defined `.vash` extension to be an `html` file (*because vscode doesn't support vash yet*). also I using your extension as well.

In `vash` file when I try to `beautify`, the js blocks combines together. (I know it's not a real bug, but not really good for me), btw when I try to  `beautify` the same content using [jsbeautifier.org](http://jsbeautifier.org/), the result is too better and more readable (of course the result is not perfect).

Is there any way to prevent combining `vash blocks` on `beautify`?

Example of `vash` (that I wish after `beautify` still I see this structure)

```
@html.extend('layout',function(model){
	@html.block('body',function(model){
		<h1>@model.title</h1>
		<p>@model.content</p>
    })
})
```

Result (using **VSCodeBeautify**)

```
@html.extend('layout',function(model){ @html.block('body',function(model){
<h1>@model.title</h1>
<p>@model.content</p>
}) })
```

Result (using [**jsbeautifier.org**](http://jsbeautifier.org/))

```
@html.extend('layout', function(model) {
    @html.block('body', function(model) { <
        h1 > @model.title < /h1> <
            p > @model.content < /p>
    })
})
```

For more complex structure the result will be really unreadable.

**Comment by HookyQR** [comment]
@dehghani-mehdi: This extension is not likely to work with Vash.

**Comment by dehghani-mehdi** [comment]
@HookyQR So that means there is no way to add this ability?

**Comment by HookyQR** [comment]
Not at this stage, although I'm interested in getting more than what `js-beautify` provides, but contributing to that repo is a little tedious. I'm looking into creating a whole new backend, which will also enable adding new file structures more easily in the future. I'll keep you posted.
