### ISSUE TITLE
Is this still being maintained or...

### ISSUE THREAD

**Issue by jrbgit** [HookyQR/VSCodeBeautify#407]
Is this project no longer being maintained?
7,810,646 Installs
and doesn't support virtual workspaces.

What has everyone moved on to?
Should we fork and update this?
Last release was May 07, 2016

Oh well, time to find a new extension to replace this one...

**Comment by colinjcahill** [comment]
yeah I am trying to figure out how to point this to a newer version of js-beautify since this is super out of date.

update:  pointing to a newer version of `js-beautify` in `~/.vscode/extensions/hookyqr.beautify-1.5.0/package.json` and restarting VS Code gave me what I needed.

**Comment by georgiai1** [comment]
@jrbgit did you find a suitable replacement?

**Comment by iSpid3r** [comment]
Found an alternative?

**Comment by gtedavid** [comment]
Hi
Idk if this is the right place to ask, but on Visual Studio Code Extensions Marketplace, it's labelled as no longer maintained 
![image](https://user-images.githubusercontent.com/60758334/178971329-a9b9f2b6-0ac5-4d69-9a2e-80a93fc6292f.png)
Is it really the case or has there been a fork/change of repo which is still waiting to be validated by Microsoft to be available on the marketplace ?

**Comment by alainburindi** [comment]
For anyone looking for alternatives I have used prettier in the last couple of years and it works just great.

But also it looks like the VS Code built-in formatter does the job. This article talks about it and how to do the configuration: https://dev.to/robole/vs-code-you-dont-need-a-formatting-extension-prettier-and-friends-26cm

**Comment by zm-cttae** [comment]
I am actually forking it for what its worth - over at @vsce-toolroom.
So that full `.jsbeautifyrc` can be supported.

**Comment by zm-cttae** [comment]
https://marketplace.visualstudio.com/items?itemName=vsce-toolroom.vscode-beautify
