### ISSUE TITLE
No support for SASS/SCSS

### ISSUE THREAD

**Issue by MehdiDehghani** [HookyQR/VSCodeBeautify#41]
Hi,

Seems like your extension doesn't support `SASS/SCSS` files, right, or I missed something?

I'm using latest version of `VSCode` & `VSCodeBeautify`

Thanks !

**Comment by HookyQR** [comment]
The extension supports `scss` (Sassy CSS) files (automatically with the extension `.scss`) but VS Code calls this `Sass` when indicating the highlighting used.

The extension does not support `sass` files, which have a Haml syntax rathar than a `css`'ish syntax.

**Comment by MehdiDehghani** [comment]
Thanks for the answer.
So, if I got you correctly, I should use another ext. for formatting `sass/scss` files, right?

And have you any plan to add supporting `scss` to your extension?

**Comment by mrmlnc** [comment]
@MehdiDehghani,

For `SCSS` you can use [csscomb](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-csscomb) or [stylefmt](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-stylefmt).

**Comment by HookyQR** [comment]
If your SCSS looks like like: 
```
// Variable
!primary-color= hotpink

// Mixin
=border-radius(!radius)
    -webkit-border-radius= !radius
    -moz-border-radius= !radius
    border-radius= !radius

.my-element
    color= !primary-color
    width= 100%
    overflow= hidden

.my-other-element
    +border-radius(5px)
```

then those ones don't look like they'll do the job either. If it looks like:
```
// Variable
$primary-color: hotpink;

// Mixin
@mixin border-radius($radius) {
    -webkit-border-radius: $radius;
    -moz-border-radius: $radius;
    border-radius: $radius;
}

.my-element {
    color: $primary-color;
    width: 100%;
    overflow: hidden;
}

.my-other-element {
    @include border-radius(5px);
}
```
then my extension will work fine. If it looks like the latter, and you're still having problems, let me know. 

If it looks like the first version, you may be better of using a Haml or Yaml style formatter.

**Comment by MehdiDehghani** [comment]
Nope, there is no problem with second way, your extension works great with that.
