### ISSUE TITLE
.vscode folder

### ISSUE THREAD

**Issue by Mikael-Sundstrom** [HookyQR/VSCodeBeautify#42]
It would be good if I could place the .jsbeautifyrc-file in the .vscode-folder together with other extension files. The root would be cleaner.

However I'm not sure if .vscode is a standard folder but "Spelling and Grammar Checking" by Sean McBreen is using that path.

**Comment by HookyQR** [comment]
The extension is setup the way it is to follow how the command line version of `js-beautify` works. Having said that, I've just added the ability to have the `.jsbeautifyrc` file in your home directory as a fallback.

**Comment by HookyQR** [comment]
There are now several fallbacks, including using your workspace settings for much of the required config. Have a look at the read me for all the goods.
