### ISSUE TITLE
How does this work with SCSS files? Is .jsbeautifyrc ignored?

### ISSUE THREAD

**Issue by Jakobud** [HookyQR/VSCodeBeautify#44]
I'm trying to figure out why this extension seems to ignore my `.jsbeautifyrc` file settings for scss files. Right now, I have this:

```
{
	"end_with_newline": true,
	"indent_level": 0,
	"indent_with_tabs": true,
	"max_preserve_newlines": 2,
	"preserve_newlines": true,
	"wrap_line_length": 0,
	"newline_between_rules": true,
	"convert_quotes": "single",
	"js": {
		"brace_style": "collapse",
		"break_chained_methods": false,
		"indent_with_tabs": true,
		"jslint_happy": false,
		"jslint_happy_align_switch_case": false,
		"space_after_anon_function": false,
		"space_before_conditional": true,
		"space_in_empty_paren": false,
		"space_in_paren": false
	},
	"html": {
		"brace_style": "collapse",
		"wrap_attributes_indent_size": 4,
		"unformatted": ["a", "sub", "sup", "b", "i", "u"]
	},
	"css": {
		"convert_quotes": "single",
		"newline_between_rules": true,
		"selector_separator_newline": true,
		"space_around_selector_separator": true,
		"indent_size": 16
	}
}
```

So I have `newline_between_rules` set to true by default. But when I save my scss file, it removes all the new lines. Also it doesn't convert my quotes to single quotes. I have the `.jsbeautifyrc` file in the same directory as my .scss file. What am I doing wrong?

Also, this extension seems to be Beautifying my .scss files on save even if I remove them from the array:

```
"beautify.CSSfiles": [
    "css"
],
```

Also I tried this:

```
"beautify.onSaveIgnore": [
        //don't beautify any file in any 'minified' directory, at any depth:
        "**/minified/**",
        //don't minify any file that contains '.min.', '_min.', '-min.' in the filename (This is the default ignore setting):
        "**/*+(.|_|-)min.*",
        "scss"
    ]
```

And my SCSS files are STILL being Beautified on save.

Can anyone give me some insight here? Am I hitting some bugs or just completely misunderstanding how this thing works?

**Comment by HookyQR** [comment]
I should be able have a look in a few hours. In the meantime, try "*.scss" in your `"beautify.onSaveIgnore"`.

**Comment by Jakobud** [comment]
`*.scss` did not work but this did: `**/*.scss`.

**Comment by HookyQR** [comment]
Awesome, glad you got it sorted @Jakobud.
