### ISSUE TITLE
Support for custom onSave values

### ISSUE THREAD

**Issue by Christilut** [HookyQR/VSCodeBeautify#45]
I tried adding the `.vue` extension to `beautify.onSave` but this warns me that this isnt an acceptable value and it won't auto beautify vue files on save. Manually running beautify does work.

**Comment by HookyQR** [comment]
`beautify.onSave` uses the VS Code file type to determine if the file should be beautified. VS Code identifies a `.vue` file as `html`. So you can set `beautify.onSave` to `true` or `["html"]` to get the result you're after.
