### ISSUE TITLE
Support 'force-aligned'

### ISSUE THREAD

**Issue by gegana** [HookyQR/VSCodeBeautify#46]
https://github.com/beautify-web/js-beautify/pull/1015/commits/b58562b756d0d6941800bc10571166f8e66749ec

They should have made this the default instead of 'force' or 'auto'.

**Comment by HookyQR** [comment]
As soon as it hits a release, I'll include it. Seems it just missed 1.6.4.

**Comment by rseniuta** [comment]
When it will be released?

**Comment by HookyQR** [comment]
That merge missed the latest version by one day. As soon as it is in a release I'll update the extension.

**Comment by hneuer** [comment]
There has been a new realease of js-beautify. Just to let you know :-)

**Comment by ipatalas** [comment]
There are even 4 new releases by now... can't wait for new version of the extension to use those features.

**Comment by HookyQR** [comment]
Sorry folks. New years break. Adopting 1.6.8 now.

**Comment by kf-ireneuszpatalas** [comment]
No worries, real life comes first :) Thanks for the update.
