### ISSUE TITLE
Beautify semantic.min.css

### ISSUE THREAD

**Issue by csakis** [HookyQR/VSCodeBeautify#47]
I tried to unminify the deafult semantic.min.css from semantic-ui.com. After 5 minutes of trying VSCode just crashed. 
It's a big 537 kb css file though
[semantic.min.css.txt](https://github.com/HookyQR/VSCodeBeautify/files/480897/semantic.min.css.txt)

**Comment by HookyQR** [comment]
Hmm, I seem to be able to process it fine. Took about 3 seconds on my machine. Perhaps you're hitting some memory limit on your machine. Sorry I couldn't replicate the problem.

You can find the un-minified version on their CSS repo though: https://github.com/Semantic-Org/Semantic-UI-CSS/blob/master/semantic.css
