### ISSUE TITLE
Global .jsbeautifyrc file?

### ISSUE THREAD

**Issue by Arrow7000** [HookyQR/VSCodeBeautify#48]
I've had a look through the documentation and the issues here but I can't seem to find how to add a single global .jsbeautifyrc file for all projects. Is this possible? In particular I prefer no space between an anonymous function and its parentheses. Thank you

**Comment by khyamay** [comment]
yup looking for same thing for same reason..

**Comment by HookyQR** [comment]
Version 0.2.0 just released enables a `.jsbeautifyrc` in your home directory as a global default.

**Comment by Arrow7000** [comment]
Awesome, thanks! What is the home directory? The directory that VSCode is in?

**Comment by HookyQR** [comment]
Your users directory. On linux or OS X, that's `$HOME`: often `/Users/{username}/` or `/users/home/{username}/`. On Windows, it's generally `%USERPROFILE%`: often `C:\\Users\{username}\`.

**Comment by Arrow7000** [comment]
Thank you!
