### ISSUE TITLE
Cannot disable Beautify for JavaScript files

### ISSUE THREAD

**Issue by anvish** [HookyQR/VSCodeBeautify#49]
Adding `"beautify.JSfiles": []` to settings.json doesn't stop Beautify from formatting js files

**Comment by HookyQR** [comment]
@anvish, to confirm, you want to use the VS Code default formatter for javascript, but use beautify for html and css, (and potentially json?)

**Comment by anvish** [comment]
@HookyQR, right. To be able to turn it off for certain file extensions.

**Comment by HookyQR** [comment]
@anvish, this should be possible now. Checkout the new config settings, remove 'javascript' (or just drop the 'js' group) and you should be good to go.

**Comment by rattrayalex-stripe** [comment]
In my case, adding `"beautify.ignore": ["*.js", "*.jsx"],` to `.vscode/settings.json` worked.
