### ISSUE TITLE
Unable to beautify the js code in html files

### ISSUE THREAD

**Issue by krishnathota** [HookyQR/VSCodeBeautify#53]
Versions:
beautify - 0.4.1
vsCode - 1.5.2

Settings:
```
"beautify.onSave": true,
    "beautify.JSfiles": [
        "html",
        "js",
        "json",
        "jsbeautifyrc",
        "jshintrc"
    ]
```
Before Formatting:
![image](https://cloud.githubusercontent.com/assets/2134619/19427075/0e83ce00-945f-11e6-83e8-1911c3a7d166.png)

After Formatting:
![image](https://cloud.githubusercontent.com/assets/2134619/19427117/67076ae6-945f-11e6-86e8-541b3928373f.png)

As you can see, the alignment/formatting of js code inside the html file is not working. Where as if its in a .js file, its working like charm.

**Comment by HookyQR** [comment]
Please elaborate. I'm not sure what you're trying to do, or how you're trying to do it.

**Comment by acmilank22** [comment]
me too

vs code 1.6.0

beautify 0.4.0

settings
"beautify.onSave": true,
"beautify.onSaveIgnore": [
        "**/*+(.|_|-)min.*"
    ],
"beautify.JSfiles": [
        "js",
        "json",
        "jsbeautifyrc",
        "jshintrc"
    ],
"beautify.HTMLfiles": [
        "htm",
        "html"
    ],
"beautify.CSSfiles": [
        "css",
        "scss"
    ]

js code in <srcipt> is not work

0.1.10 is work

**Comment by HookyQR** [comment]
Thanks for the info @acmilank22, can you drop your `.jsbeautify` file in as well please.

**Comment by acmilank22** [comment]
I don't use .jsbeautify file .....

**Comment by HookyQR** [comment]
I don't seem to have the same problem. Could you provide an example please. If you're trying to select the javascript and do it that way, it won't work. The beautifier determines the type from the file, which would be `html` and tried to beautify it that way. If you have nothing selected, it should try to beautify the whole file. If you select all of the javascript *AND* the script tag, it should work as js-beautify will farm the formatting out to the javascript formatter from the html formatter. (Because it can work out what it is at that point)

**Comment by acmilank22** [comment]
This is my settings.json and html file.

I don't use .jsbeautify file.

It didn't beautify the javascript code in <script> when I saved the html file.

the vscode version is 1.6.1, the extension version is 0.4.1.

**Comment by HookyQR** [comment]
If you don't use a `.jsbeautifyrc` file, we use your vscode settings. Unfortunately, the default for `"html.format.unformatted"` includes `script`. Add this setting to you user settings and remove the `script, ` from the list.

The default:
  `"html.format.unformatted": "a, abbr, acronym, b, bdo, big, br, button, cite, code, dfn, em, i, img, input, kbd, label, map, object, q, samp, script, select, small, span, strong, sub, sup, textarea, tt, var"`

**Comment by acmilank22** [comment]
@HookyQR 

Thank you very much!

My problem has been solved.

**Comment by HookyQR** [comment]
You're welcome.
