### ISSUE TITLE
cannot just select the text i want to beautify 

### ISSUE THREAD

**Issue by MiguelQueiroz** [HookyQR/VSCodeBeautify#54]
I would like to just select the text i want , and then apply just to that selection the beautify.

**Comment by HookyQR** [comment]
You can now!! 0.4.0 released.

**Comment by cty8998** [comment]
@HookyQR  Can I define several format style binding to different shortcut, for e.g.   make section css/scss compact or expended, and it will be awsome.

**Comment by HookyQR** [comment]
@cty8998 You could set one key binding for beautify, and one for [minify](https://marketplace.visualstudio.com/items?itemName=HookyQR.minify). Minify can change the code content though, so you would have to make sure your settings would stop it from doing that.

**Comment by cty8998** [comment]
@HookyQR Cool! it really does a smarter way. Maybe you can add  your minify's link to beautify‘s repository.
