### ISSUE TITLE
comments tag into a new line

### ISSUE THREAD

**Issue by carlosdv4** [HookyQR/VSCodeBeautify#55]
Hi, when I use beautify in visual studio code on mac the comment tag goes into the line, I would like to have inline as the current code. Is possible to change it? Any ideas?

current:
```
</li><!-- /Dropdown -->
```
after beautify
```
</li>
<!-- /Dropdown -->
```

**Comment by HookyQR** [comment]
Yep, it does that, There is no control over it in `js-beautify` so we can't provide anything to solve it here. (While we're using `js-beautify`)
