### ISSUE TITLE
Format javascript code with shift+alt+f adds new blank lines

### ISSUE THREAD

**Issue by DennisAhaus** [HookyQR/VSCodeBeautify#58]
VSCode Version: Code 1.6.0 (e52fb0b, 2016-10-10T18:37:40.189Z)
OS Version: Windows_NT ia32 10.0.10586
Extensions: alefragnani.project-manager-0.10.0, dbaeumer.vscode-eslint-1.0.7, donjayamanne.githistory-0.1.0, DotJoshJohnson.xml-1.6.0, eg2.vscode-npm-script-0.0.20, HookyQR.beautify-0.4.0, humao.rest-client-0.8.5, ms-vscode.cpptools-0.9.2, msjsdiag.debugger-for-chrome-1.1.0, sandy081.todotasks-0.4.0, waderyan.gitblame-1.3.0
Steps to Reproduce:
1. Open vs code
2. Open javascript file
3. Press format code (shift+alt+f)

In my vs code editor each line (LF) will have additional blank line after pressing these buttons. If i have 10 lines before, i have 20 lines after

See issue https://github.com/Microsoft/vscode/issues/13591

**Comment by HookyQR** [comment]
@DennisAhaus: This is happening because of a mismatch of settings. The default setting for line endings on windows is CRLF, but you've set your file line ending to LF. beautify is using the default setting to format the code, and when the edit is applied, VS Code is changing the CRLF to LFLF, giving you double line endings. (It only does this on Windows)

If you're using a `.jsbeautifyrc` file, add `"eol": "\n"`.
If you're using editorconfig, add `end_of_line = lf`.
If you're not using any of these, add a workspace (or user global) setting of `"files.eol": "\n"`.

**Comment by johnunclesam** [comment]
It would be beautiful if beautify automagically detects editorconfig. I'm on Windows, have LF lines also settings in VSCode and if I don't write `"beautify.editorconfig": true` it add double white lines each line. Such a mess!

**Comment by DennisAhaus** [comment]
@HookyQR thanks for the replay. I already have a `.editorconfig` file with the config `end_of_line = lf`

**Comment by johnunclesam** [comment]
@DennisAhaus, you have to add "beautify.editorconfig": true in VSCode settings (user or workspace). My request is to automagically detect it.

**Comment by hubbergit** [comment]
Instead of automagically detect the presence of a editorconfig, why can't beautify just detect which line endings are used in a file and act accordingly. VS Code seems to do exactly that.

Setting "files.eol": "\n" obviously has the effect that all new files created will have now the none-standard line endings "\n" instead of "\r\n" on windows. If you have already a lot of files with that default line endings, you end with mixed line endings between the files in your project.

**Comment by HookyQR** [comment]
@hubbergit it does, kind of. The only time it won't 'automatically' select the editor's line ending is if there is a specific setting for the line ending. Any setting (from editorconfig, or jsbeautify) will override the line endings of the editor. In fact, if (as you say) VS Code was automatically determining the line endings, it should change its setting when a full file update happens, not change the line endings (incorrectly) afterwards.

**Comment by hubbergit** [comment]
@HookyQR: I'm not sure, if I am right, however having looked into the sources, it seems like the EOL option of the current editor is overwritten by the workspace option (assuming that there is no other setting in neither in editorconfig nor in jsbeautifyrc).

```
const optionsFromVSCode = (doc, formattingOptions, type) => {
const config = vscode.workspace.getConfiguration();
if (!formattingOptions) {
		formattingOptions = vscode.workspace.getConfiguration('editor');
		//if this document is open, use the settings from that window
		vscode.window.visibleTextEditors.some(editor => {
			if (editor.document && editor.document.fileName === doc.fileName) {
				return (formattingOptions = editor.options);
			}
		});
	}
	const options = {
		indent_with_tabs: formattingOptions.insertSpaces === undefined ? true : !formattingOptions.insertSpaces,
		indent_size: formattingOptions.tabSize,
		indent_char: ' '
	};
options.eol = config.files.eol;
```

**Comment by HookyQR** [comment]
The formattingOptions of the current editor doesn't have an eol field: https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nameformattingoptionsaspan-classcodeitem-id702formattingoptionsspan

I guess that explains why it's not coming through from there. I'll have a look tonight.

**Comment by HookyQR** [comment]
Turns out I didn't get time, and I've dropped the ball a bit here. If the current editor exposed an `eol` setting, this would be doable.

**Comment by hubbergit** [comment]
After having read the docs (where the link you have provided points to), I agree that the `eol` setting does not seem to be part of the formatting options.

However it seems to be a property of the document itself.

Is it an option to take it from there?

**Comment by HookyQR** [comment]
I've logged an issue to hopefully get the problem resolved: https://github.com/Microsoft/vscode/issues/15385

Unfortunately, the `eol` property isn't on the document, it's set on the editor, and that isn't passed to the extension when using the *DocumentFormattingEdits* callbacks.

Until VS Code fixes the inconsistent behaviour, there's not much I can do. I suggest setting up a Keyboard Shortcut to use the `HookyQR.beautifyFile` command and using that instead.

**Comment by HookyQR** [comment]
@DennisAhaus, @johnunclesam, @hubbergit. Release 0.6.2 should solve this issue.
