### ISSUE TITLE
Adopt formatOnSave changes

### ISSUE THREAD

**Issue by jrieken** [HookyQR/VSCodeBeautify#59]
Since we now have the `editor.formatOnSave`-setting and the `onWillSaveTextDocument` event, [this code](https://github.com/HookyQR/VSCodeBeautify/blob/master/extension.js#L253) should be updated. Using the new infrastructure will prevent unnecessary fs-operations, event cascades, and potential for endless write-event-write loops.

See https://code.visualstudio.com/updates#_format-on-save, https://github.com/Microsoft/vscode/issues/12449, and https://github.com/Microsoft/vscode/issues/239 for more details

**Comment by HookyQR** [comment]
Thanks for the nudge @jrieken. I'm on it. 🛠

**Comment by HookyQR** [comment]
@jrieken: Something that I have found to be lacking in the docs, at what version does this kick in? I'm guessing it's at 1.6.0, but it would be nice if an 'as of' was mentioned in the api docs.

**Comment by jrieken** [comment]
Understood - what we do is to fetch the version of `vscode.d.ts` according to the `engine`-property in your package.json file.

**Comment by HookyQR** [comment]
@jrieken, I mean, at https://code.visualstudio.com/docs/extensionAPI/vscode-api it would be nice if each of the methods had a reference to the version in which they became/become available.

**Comment by HookyQR** [comment]
Done in v0.5.0
