### ISSUE TITLE
endWithNewline and preserveNewLines not honored

### ISSUE THREAD

**Issue by epicbugs** [HookyQR/VSCodeBeautify#60]
This issue appears on beautify `v0.4.1`, VS Code `v1.6.1` and Windows10 Professional `v1607`.

Neither the beautify command nor the format command nor saving the file adds any ending newlines except for `.html` files, although the configuration appears to mandate that it should.

I have the following user settings file:

```
{
    "files.eol": "\n",
    "files.autoSave": "onFocusChange",
    "editor.tabSize": 4,
    "editor.formatOnSave": false,
    "editor.trimAutoWhitespace": false,
    "files.trimTrailingWhitespace": false,
    "html.format.endWithNewline": true,
    "html.format.preserveNewLines": true,
    "beautify.onSave": true
}

```

No other code formatting extensions are installed, there is no `.jsbeautifyrc` and the workspace settings keep the directives untouched, so everything ought be controlled by the above configuration.

Yet, the ending newlines are not only failing to get generated, they are being actively purged.

**Comment by HookyQR** [comment]
Seems I forgot to convert the endWithNewline option to the `js-beautify` equivalent, so I'll add that in. Not sure why the preserve isn't being honoured. It may be because the `"html.format.maxPreserveNewLines"` default is null, and the `js-beautify` equivalent is zero.

**Comment by HookyQR** [comment]
@epicbugs I can't duplicate the error unfortunately, I used exactly the settings you provided above. Check that there are no `.jsbeautifyrc` files anywhere in the tree of the path, or in your home directory (eg `C:\Users\epicbugs\.jsbeautifyrc`). Unless you have `"beautify.editorconfig"` set to true, an editorconfig file shouldn't affect it.

**Comment by HookyQR** [comment]
Not fixed. I can't seem to duplicated it on my machine, but the test is failing on Travis and Appveyor.

**Comment by HookyQR** [comment]
Interestingly, it works on x64, but not on x86 for some reason.

**Comment by HookyQR** [comment]
Tests pass on local, but not on Appveyor for x86.

**Comment by epicbugs** [comment]
> @epicbugs I can't duplicate the error unfortunately, I used exactly the settings you provided above.

@HookyQR Different file extensions behave differently for some reason: `.html` files work as they should, in `.js` and `.less` files VS Code doesn't add the newline if it is missing, but in `.json` files the newlines are being actively purged.

Which file extensions did you test with?

**Comment by HookyQR** [comment]
I was using HTML. This is the only format that these settings are applied to (because they're settings on `html.format`). If you want to handle the formatting for `js` and `css` file types, you'll have to use either an `editorconfig` file or a `.jsbeautifyrc` file. Both search up the path and have a means of globally applying settings (somewhere in your users directory), so you should still be able to use them without tainting your project.
