### ISSUE TITLE
"beautify.onSave": false is overriden by "editor.formatOnSave": true

### ISSUE THREAD

**Issue by hubbergit** [HookyQR/VSCodeBeautify#61]
Files are formatted even though "beautify.onSave" is false. This only happens, if "editor.formatOnSave" is true.

My propsal would be to activate beautify only and only if editor.formatOnSave is set to true. Change beautify.onSave so that setting it to true/false is not allowed, but only setting the file types is allowed:

Don't allow:
`"beautify.onSave": true | false`

Only allow:
`"beautify.onSave": ["js","css"]`

**Comment by HookyQR** [comment]
Yep. This is caused by the changes mentioned in #59. I'll be implementing the formatOnSave to look at the `onSave` setting exactly has you've described.

**Comment by HookyQR** [comment]
v0.5.0 ignores `"beautify.onSave": true | false` in favour of `editor.formatOnSave`. `"beautify.onSave": [ ... ]` is checked when formatOnSave is true.

**Comment by hubbergit** [comment]
@HookyQR just tried it and works well. Thanks!

Just a minor issue: When I update/install the beautify extension, then the file with the global default VS Code options/settings still contains

`"beautify.onSave": false`

which is not valid anymore.

Shall I create an issue for that?

**Comment by garygreen** [comment]
FYI - You can limit `editor.formatOnSave` to specific languages (this is a vs-code built in feature):

```json
{
    "[less]": {
        "editor.formatOnSave": true
    }
}
```

This will only format `.less` files on save.
