### ISSUE TITLE
Scss config / rules

### ISSUE THREAD

**Issue by saltcod** [HookyQR/VSCodeBeautify#64]
Hey there!

This ext seems to work great out of the box. I'm wondering if there's anywhere I can add some rules? I'd just like to add some spaces after nested elements. Example:

Instead of this:

``` sass
.selector {
    margin-top: 5px;
    a {
        padding 10px;
        &:after {
            style
        }
    }
}
```

I'd love to see line breaks after the nested parts:

``` sass
.selector {
    margin-top: 5px;

    a {
        padding 10px;

        &:after {
            style
        }
    }
}
```

Thanks very much for your time and efforts with this!

ps: screenshot in case the code doesn't look too good:   https://dl.dropboxusercontent.com/s/vn80fwk1vc5f4df/2016-10-24%20at%2011.19%20PM.png

**Comment by HookyQR** [comment]
The actual changes are done by [js-beautify](https://github.com/beautify-web/js-beautify). Any changes to how the formatting works would need to be discussed int that repo. You're not the first to ask, so I would expect there to be some others with the same request over there.

**Comment by saltcod** [comment]
aaaah gotcha. Ok will follow up there. Appreciate the reply!  Thank you
