### ISSUE TITLE
可否考虑支持下weex的.we文件？

### ISSUE THREAD

**Issue by jingxin2015** [HookyQR/VSCodeBeautify#66]
如题，发现beautify更新很快，可否考虑把.we文件加入支持，谢谢。

weex相关介绍：https://github.com/alibaba/weex

**Comment by HookyQR** [comment]
You can add support yourself by including the extension in the html `"beautify.language"` setting:
```javascript
"beautify.language": {
    "html": {
        "type": ["htm", "html"],
        "ext": ["we"]
    }
}
```
