### ISSUE TITLE
How do I make beautify not add newline for each js import? 

### ISSUE THREAD

**Issue by Nikki1993** [HookyQR/VSCodeBeautify#67]
I have the following line of code

```
import { RecipeService } from '../recipe.service';
import { Component, OnInit, EventEmitter, Output } from '@angular/core';
import { Recipe } from '../recipe';
```

I'd like 'beautify' not to beautify it to or switch it to newline when soft wrapping only.

```
import { RecipeService } from '../recipe.service';
import {
  Component,
  OnInit,
  EventEmitter,
  Output
} from '@angular/core';
import {
  Recipe
} from '../recipe';
```
How do I do that?

**Comment by HookyQR** [comment]
Use: `"brace_style": "collapse-preserve-inline"` in your `.jsbeautifyrc`.

You can also use:
```javascript
/* beautify preserve:start */
import { RecipeService } from '../recipe.service';
import { Component, OnInit, EventEmitter, Output } from '@angular/core';
import { Recipe } from '../recipe';
/* beautify preserve:end */
```

**Comment by MarkPieszak** [comment]
How can we do this when using the Beautify extension in VSCode? Tried workspace settings but it breaks beautity completely, strange.

**Comment by Nikki1993** [comment]
@MarkPieszak But this is the method for VSCode extension. have a, jsbeautifyrc and add the brace_style as per @HookyQR suggestion.

**Comment by Howsky** [comment]
@HookyQR "brace_style" doesn't change anything. Preserving is some solution, but rather makeshift. There's no way to fix that?

**Comment by elucidsoft** [comment]
This is now 
`"brace_style": "collapse,preserve-inline"`

**Comment by hoangngk** [comment]
@HookyQR 
is there any way to break new lines only import is too long ?

**Comment by 8Observer8** [comment]
If you don't want to run VSCode for quick formatting you can install `js-beautify` globally: `npm i -g js-beautify` and run this command from terminal: `js-beautify -n main.js -o main.js -b "collapse, preserve-inline"` or this: `js-beautify -n *.js -b "collapse, preserve-inline"`
