### ISSUE TITLE
User Setting for indent_size?

### ISSUE THREAD

**Issue by psrivongse** [HookyQR/VSCodeBeautify#68]
Is there anyway to set the `indent_size` for User Settings?

I've set `"editor.tabSize": 2`, however it does not respect it. 
But when I add a `.jsbeautifyrc` in the project root with:

    { 
       "indent_size": 2
    }

It works fine.

Thanks.

**Comment by HookyQR** [comment]
Without the `.jsbeautifyrc` you would have to also set: `"editor.insertSpaces": true` in you VSCode settings.

**Comment by psrivongse** [comment]
I believe it has to do with the project I'm working in. I've set those settings in `User Settings`, I don't have any `Workspace Settings` or `.jsbeautifyrc.`. I've created a new project and HTML file and it indents just fine.
 ¯\_(ツ)_/¯


UserSettings: 

    "editor.tabSize": 2,
    "editor.insertSpaces": true,
