### ISSUE TITLE
beautify.language not working correctly

### ISSUE THREAD

**Issue by jon-heller** [HookyQR/VSCodeBeautify#69]
I've tried the following in my .jsbeautifyrc file (which, besides this setting, is correctly working)

```
"beautify.language": {
      "html": {
        "type": ["htm", "html"],
        "ext": ["twig"]
      }
    }
```

Also have tried

```
"beautify.language": {
      "html": ["twig", "htm", "html"]
    }
```

But when attempting to beautify I am still prompted with the following:

![screen shot 2016-11-10 at 10 43 53 am](https://cloud.githubusercontent.com/assets/3852999/20183226/a04387b4-a732-11e6-8f35-c676afaeb112.png)

**Comment by HookyQR** [comment]
Hi @jon-heller, the setting needs to go in your VS Code user or workspace settings, not the `.jsbeautifyrc` file.

**Comment by jon-heller** [comment]
Thank you! Didn't even think of that, but now it works fine.

I assumed it was the .jsbeautifuyrc file just because the previous paragraph in the instructions were talking about it.

**Comment by C0deZLee** [comment]
I went into this problem too, the document is very unclear about this, maybe need to update

**Comment by mjd507** [comment]
same problem, now it's ok, really recommend to update the doc.
