### ISSUE TITLE
Compatibility with 1.8 Insiders

### ISSUE THREAD

**Issue by bfulop** [HookyQR/VSCodeBeautify#70]
Hello,

Is it possible that Beautify is not yet compatible with the 1.8 Insiders version (as of 15th November)?

I'm syncing my Code setup between 1.7 and 1.8 so the settings etc. are the same between 1.7 and 1.8.
In 1.7 Beautify works great, however in 1.8, format on save doesn't work. If I launch the beautify command manually, Beautify is asking me each time to select the file type (JS/CSS/HTML) even for a simple js or css files.

So my guess is that in 1.8 it doesn't recognise the file types correctly?

**Comment by HookyQR** [comment]
I'll have to pull the insiders build to have a look. Hackdays at work tomorrow, so I'll have plenty of time.

**Comment by HookyQR** [comment]
This is a regression error at the VS code end, but I'll change the setting lookup mechanism to get around the current failure incase it isn't fixed.

**Comment by HookyQR** [comment]
Fixed in 0.5.5.

**Comment by bfulop** [comment]
Thank you HookyQR for fixing this so quickly, even if the bug didn't come from your end!

I can confirm, beautify is working perfectly on 1.8!
