### ISSUE TITLE
HTML beautify should not format <pre> body

### ISSUE THREAD

**Issue by maxrahder** [HookyQR/VSCodeBeautify#71]
Thanks for the nice formatter, but I have a suggestion:

I have an HTML page with a \<pre> and the beautifier indents the contents. The point of a \<pre> is to use the literal content. Beautifying it means the content gets indented, etc., which is very bad. Anything in a \<pre> should *not* be formatted.

**Comment by HookyQR** [comment]
Hey @maxrahder, what version of VS Code are you using?
None of the default settings will allow a `<pre>` tag to be beautified.

If you're using a `.jsbeautifyrc` file (at any depth in your path, or in you home directory), check that
the `"unformatted"` array includes `"pre"`.

If you're not, check that your VS Code settings includes `pre` in the `"html.format.unformatted"` comma separated string.

**Comment by HookyQR** [comment]
Closing as there has been no response. Assuming you got it working correctly.
