### ISSUE TITLE
[.jsbeautifyrc] "brace_style" configuration for the Object doesn't work

### ISSUE THREAD

**Issue by u3u** [HookyQR/VSCodeBeautify#72]
.jsbeautifyrc:
``` JSON
"js": {
  "allowed_file_extensions": [ "js", "json", "jshintrc", "jsbeautifyrc" ],
  "brace_style": "none"
}
```

My code: 
``` JAVASCRIPT
  // raw:
  show({title='',body=''}={}){
  }

  // i need:
  show ( { title = '', body = '' } = {} ) {
    
  }

  // but, the format result too ugly:
  show ( { 
    title = '', 
    body = '' 
  } = {} ) {
    
  }
```

I think, for instance Object, should make the following adjustments:
Already in the same row, should not be forced a newline, only add Spaces
Not in the same row, use the format specification now

**Comment by HookyQR** [comment]
`"brace_style": "collapse-preserve-inline"` is what you're after. If you don't put any body in the last brace set, that will be collapsed as well.

**Comment by u3u** [comment]
Thank you very much!
Excuse me, where's the detailed configuration can see?
@HookyQR

**Comment by HookyQR** [comment]
They're not very well documented, but if you edit your `.jsbeautifyrc` file with VS Code it should give you code completion for each of the settings. I'll add a config help file on the next release. The basic config details are here: [js-beautify options](https://github.com/beautify-web/js-beautify#options)

**Comment by u3u** [comment]
Ok, thank you very much!
