### ISSUE TITLE
Beautifying scss files removes empty lines

### ISSUE THREAD

**Issue by jfily** [HookyQR/VSCodeBeautify#74]
Hi,

When I beautify scss files, new lines between blocks are removed even if i force "selector_separator_newline" (it's working for css files)

```
.a {
  prop: value;

  .b {}
}

.c {}

becomes

.a {
  prop: value;
  .b {}
}
.c [}
```

Here is my .jsbeautifyrc file
```
{
    "indent_size": 4,
    "indent_char": " ",
    "eol": "\n",
    "indent_level": 0,
    "indent_with_tabs": false,
    "preserve_newlines": true,
    "max_preserve_newlines": 2,
    "jslint_happy": true,
    "space_after_anon_function": true,
    "brace_style": "collapse",
    "keep_array_indentation": false,
    "keep_function_indentation": false,
    "space_before_conditional": true,
    "break_chained_methods": false,
    "eval_code": false,
    "unescape_strings": false,
    "wrap_line_length": 0,
    "wrap_attributes": "auto",
    "wrap_attributes_indent_size": 4,
    "end_with_newline": true,
    "space_in_paren": false,
    "newline_between_rules": true,
    "space_around_combinator": true,
    "selector_separator_newline": true
}
```

**Comment by HookyQR** [comment]
Hi @jfily, this is a known issue. It's a problem with the upstream process. See https://github.com/beautify-web/js-beautify/issues/657

**Comment by jfily** [comment]
Oups, sorry, I should have checked the "main" repo before.

**Comment by HookyQR** [comment]
Looks like the fix for this is due for release soon. https://github.com/beautify-web/js-beautify/pull/1117

**Comment by TimvdEijnden** [comment]
Yep I really wanted it too, hope I see this fix in my VSCode soon! ⌛️

**Comment by HookyQR** [comment]
It was merged today. Should be a release soon. 🤞

**Comment by TimvdEijnden** [comment]
Great! 😎

**Comment by HookyQR** [comment]
New version released. Enjoy.

**Comment by Barterr** [comment]
newline_between_rules for scss is not working still
