### ISSUE TITLE
"beautify.onSave" is not working with v0.6.1 or v0.6.2.

### ISSUE THREAD

**Issue by renzhaozhao** [HookyQR/VSCodeBeautify#75]
if set "editor.formatOnSave:true",".jsbeautifyrc" is not working.
please fix this problem.

**Comment by HookyQR** [comment]
`"beautify.onSave"` is no longer used by the extension. The functionality it provided doesn't work with the `"editor.formatOnSave"` function. Please provide your settings (VS Code `settings.json` and `.jsbeautifyrc`) files. Knowing what operating system you're on will help too, as well as what version of VS Code you're using.

**Comment by renzhaozhao** [comment]
VS Code version 1.7.2
OS win10

setting.json
```
{
    "editor.fontSize": 18,
    "typescript.check.tscVersion": false,
    "editor.wrappingColumn": 0,
    "editor.formatOnSave": true,
    "beautify.onSave": ["js"],
    "typescript.check.workspaceVersion": false
}
```
.jsbeautifyrc
```
{
    "max_preserve_newlines": 2,
    "brace_style": "end-expand",
    "end_with_newline": true
}
```

**Comment by HookyQR** [comment]
`"beautify.onSave": ["js"]` has no affect any more.
From these settings v0.6.2 should be working fine. Are there any errors in the console? (Help-> Toggle Developer Tools -> Console)

Some notes: 
* VS Code won't trigger a save action if the file has no changes.
* Formatting is not called when auto save is enabled.

**Comment by HookyQR** [comment]
Are you trying to use formatOnSave for typescript? If so, add this to your VS code settings:
```javascript
    "beautify.language": {
        "js": {
            "type": [ "javascript", "json", "typescript" ],
            "filename": [ ".jshintrc", ".jsbeautify" ]
        }
    }
```
