### ISSUE TITLE
Not able to format JSON selection

### ISSUE THREAD

**Issue by sjelfull** [HookyQR/VSCodeBeautify#76]
* **VSCode Version**: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
* **OS Version**: Darwin x64 16.1.0
* **beautify Version**: 0.6.2

Provide the settings you use: 
I'm using the default settings (aka, no manual overrides)

## Action performed
Format unsaved/untitled JSON selection with `HookyQR.beautifySelection` command

	{"smoke_alarm_count":"1","home_generalActivity":4,"neighbourhood_generalActivity":4,"social_generalActivity":4,"sparetime_generalActivity":4,"summaryHelp":false,"summaryMaintain":true,"unsafe_home":false,"maintain_personalBody":true,"maintain_cooking":true,"maintain_health":true,"maintain_medicines":true,"maintain_relationships":true,"maintain_physicalActivity":true,"sensor_type":false,"undefined":false,"unsafe_falling":false,"unsafe_activities":false,"unsafe_stayAtHome":false,"unsafe_health":false,"unsafe_forgetful":false,"unsafe_network":false,"unsafe_work":false,"unsafe_forgetful_road":false,"unsafe_annet":false,"maintain_home":false,"maintain_shopAlone":true,"maintain_doctorVisit":true,"maintain_walking":false,"maintain_work":false,"maintain_learning":false,"maintain_volunteerWork":false,"maintain_devices":false,"maintain_culture":false}

## Expected results
Expected selection to to be beautified

	{
		"smoke_alarm_count": "1",
		"home_generalActivity": 4,
		"neighbourhood_generalActivity": 4,
		"social_generalActivity": 4,
		"sparetime_generalActivity": 4,
		"summaryHelp": false,
		"summaryMaintain": true,
		"unsafe_home": false,
		"maintain_personalBody": true,
		"maintain_cooking": true,
		"maintain_health": true,
		"maintain_medicines": true,
		"maintain_relationships": true,
		"maintain_physicalActivity": true,
		"sensor_type": false,
		"undefined": false,
		"unsafe_falling": false,
		"unsafe_activities": false,
		"unsafe_stayAtHome": false,
		"unsafe_health": false,
		"unsafe_forgetful": false,
		"unsafe_network": false,
		"unsafe_work": false,
		"unsafe_forgetful_road": false,
		"unsafe_annet": false,
		"maintain_home": false,
		"maintain_shopAlone": true,
		"maintain_doctorVisit": true,
		"maintain_walking": false,
		"maintain_work": false,
		"maintain_learning": false,
		"maintain_volunteerWork": false,
		"maintain_devices": false,
		"maintain_culture": false
	}

## Actual results
The selection was left untouched, without any feedback

**Comment by HookyQR** [comment]
I can't duplicate the problem unfortunately, I get correctly formatted results. Can you check that there are no errors in the console please. (Help->Toggle Developer Tools. Then select the console tab)

**Comment by HookyQR** [comment]
If you have a `.jsbeautifyrc` file, check that `"brace_style"` is not set to `"collapse-preserve-inline"`, or `"none"`. Otherwise, I'm back to not being able to reproduce.

**Comment by sjelfull** [comment]
I think this is back to working now. The file that it worked on is a unsaved file that is opened on it's own, and not inside another project. That is the only difference I can think of. There might have been a `.jsbeautifyrc` file in the previous project I tried this inside.

Thanks, let's assume it's fine if/until it reappears.
