### ISSUE TITLE
Latest 0.7.2 update is listed as 0.7.1 in changelog

### ISSUE THREAD

**Issue by JoeArizona** [HookyQR/VSCodeBeautify#87]
* **Operating System (+Version)**: Windows 10 Home 64-bit
* **VS Code Version**:  1.8.1
* **beautify Version**:  0.7.2, probably

Minor issue: Tonight's update is identified as 0.7.2 by VS Code in the Extensions pane, but in beautify's own changelog, it's listed as 0.7.1 ~ the second consecutive 0.7.1 release, differentiated only by date.

**Comment by HookyQR** [comment]
Thanks for the info. Was trying to get it out quick. Copy-paste error.
