### ISSUE TITLE
"force-aligned" wrap-attributes enum value in Schema

### ISSUE THREAD

**Issue by schmuli** [HookyQR/VSCodeBeautify#88]
* **Operating System (+Version)**:  Win10
* **VS Code Version**:  1.9.0-Insider
* **beautify Version**:  0.7.2

According to the documentation available on JSBeautifier's Github page, the correct values for the `wrap-attributes` setting can be:

    [auto|force|force-aligned|force-expand-multiline]

However in the [VSCode Schema file](https://github.com/HookyQR/VSCodeBeautify/blob/master/schema/beautifyrc.json#L96), these appear as:

    "enum": ["auto", "force", "force-align", "force-expand-multiline"]

**Comment by HookyQR** [comment]
@schmuli, you're right about the missing `ed`. I took the value from the change log for js-beautify which dropped it as well. Fixing now.

**Comment by HookyQR** [comment]
Fixed in 0.7.3.
