### ISSUE TITLE
Beautify on save isn't triggered with additional configured extensions

### ISSUE THREAD

**Issue by jayrosen1576** [HookyQR/VSCodeBeautify#9]
let refType = doc.languageId;

	if (refType === 'javascript') refType = 'js';
	if (['json', 'js', 'html', 'css'].indexOf(refType) === -1) return;

It looks like the above lines of code need to be altered to used the "beautify.HTMLfiles", "beautify.CSSfiles", "beautify.JSfiles" user settings. I have the following in my settings file but the saving the handlebars file does not run the beautifier:

	"beautify.HTMLfiles": [
		"htm",
		"html",
		"hbs"
	]

**Comment by jayrosen1576** [comment]
Nice! works great!

**Comment by HookyQR** [comment]
It was ignoring these. Also it wouldn't have been loaded in situations where the file type wasn't recognised by VS Code. I've altered this so it loads always now, but runs only when saving the file types it can handle (or has been told to handle). Released version 0.1.1.

Thanks for staying involved.
