### ISSUE TITLE
Not respecting JS standard for 'eol-last'

### ISSUE THREAD

**Issue by SherlockStd** [HookyQR/VSCodeBeautify#90]
* **Operating System (+Version)**: Ubuntu (16.04)
* **VS Code Version**: 1.8.1
* **beautify Version**: 0.7.3

## Action performed
Format javascript file with `HookyQR.beautifyFile` command

## Expected results
Expected to have a blank line at end of file

## Actual results
And there's not ...
Please fix this

## PS

You're tool is amazing, saving a lot of time, thanks !!

**Comment by HookyQR** [comment]
The default is to not include a new line at the end of the file. You can change this in your settings (depending on which settings you're using):

VS code settings: `"html.format.endWithNewline": true` _(Only for html files)_
`.jsbeautifyrc`: `"end_with_newline": true`
Editor config file: `insert_final_newline = true`

**Comment by SherlockStd** [comment]
VS code settings:

```
// When enabled, insert a final new line at the end of the file when saving it.
"files.insertFinalNewline": false
```
