### ISSUE TITLE
Ruby files (.rb, .erb)?

### ISSUE THREAD

**Issue by johnunclesam** [HookyQR/VSCodeBeautify#92]
Ruby files (.rb, .erb)?

**Comment by HookyQR** [comment]
Take a look at: https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby

You can set that up to do formatting for `.rb` files using rubocop as a handler.

**Comment by johnunclesam** [comment]
I'm working also on Windows... :(

**Comment by HookyQR** [comment]
That shouldn't be a problem. The Ruby extension is cross platform, and I'm pretty sure you can still install rubocop.

**Comment by johnunclesam** [comment]
I'm sorry. For rubocop I need the `gem rubocop` to be installed on my machine. But for that gem I need ruby environment, which, on Windows is a mess. I just need formatting and linter. Maybe an npm package?

**Comment by HookyQR** [comment]
So you're doing Ruby dev, on a windows machine with no Ruby installed? Have you tried using [RubyInstaller](https://rubyinstaller.org/)? It will make your life way easier.

**Comment by johnunclesam** [comment]
Yes, because I don't deploy on Windows, I just use Windows for writing code.

**Comment by HookyQR** [comment]
Wow, I wish you luck then. I'd still drop a ruby instance on the dev machine if I were you, but each to their own.

**Comment by johnunclesam** [comment]
So, no luck for beautify for Ruby on Windows without gems?

**Comment by HookyQR** [comment]
Nup, not at this stage, and not likely in the near future.
