### ISSUE TITLE
Any way for eslint-happy?

### ISSUE THREAD

**Issue by peterwang1996** [HookyQR/VSCodeBeautify#97]
Hi, I'm using the plug-in and it works out just fine. Thx for your awesome work.

But there's only one problem that when I'm working on others' code, I have to follow the code spec for the original project. Even the project provided `.eslintrc.js` to check the format, the plugin cannot read it, so I have to either write my own `.jsbeautifyrc` that fits the spec or beautify the code bu myself. If there's a way that the plugin could read `.eslintrc.js` in the project root directory, that would make the plugin more easy to use. So is there any plan for you to add this function? Or the function has already existed but I haven't discovered that?

RSVP & Thx ~ :)

**Comment by HookyQR** [comment]
It's a lot of work to interpret a `.eslintrc.js` file into `.jsbeautifyrc` settings. I'll give it a go at some stage though. Sorry for the delay in responding.

**Comment by peterwang1996** [comment]
Thx a lot for your reply anyway.
