### ISSUE TITLE
Option to have css properties on the same line

### ISSUE THREAD

**Issue by Zmove** [HookyQR/VSCodeBeautify#98]
Hello,

I'm one of those developper that like to have css properties on the same line. 

For example :

    .btn-primary { background:#fff; color:#aaa; border:1px solid #aaa;  }

It seems there is no options to allow that, could it be possible to add one ? I believe many developpers prefers to see css formatted that way.

Best regards,

Alex

**Comment by HookyQR** [comment]
Doesn't seem to be a way at this stage. Sorry. You could look at contributing to https://github.com/beautify-web/js-beautify to make it an option.
