### ISSUE TITLE
issue with phonegap and <%= ... %>(ejs)

### ISSUE THREAD

**Issue by bondarenkod** [HookyQR/VSCodeBeautify#99]
* **Operating System (+Version)**: win10 and osx
* **VS Code Version**: 1.9.1
* **beautify Version**: 0.7.3

Provide the settings you use:
default settings.

## Action performed
code formatting via 'f1 - Beautify File'
```html
<img class="cache-image float-left margin-right-1_5" src="<%= ns.common.host + Image.replace(" {0} ","118 ").replace("{1}","158 ") %>" alt="" />
```

## Expected results
```html
<img class="cache-image float-left margin-right-1_5" src="<%= ns.common.host + Image.replace(" {0} ","118 ").replace("{1}","158 ") %>" alt="" />
```

## Actual results
```html
<img class="cache-image float-left margin-right-1_5" src="<%= ns.common.host + Image.replace(" {0} ","118 ").replace("{1}
									","158 ") %>" alt="" />
```
There is incorrect formatting of ejs code. How I can fix or avoid it?

**Comment by HookyQR** [comment]
I can't seem to find a way. Sorry.

**Comment by HookyQR** [comment]
You can change your wrapping line length, but that seems to force spaces around the `{1}` which is also going to break your code.
